### ISSUE TITLE
SQL: `ORDER BY` alters result type (in sub-query)

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1046]
### JDK Version: Running on Mac OS X 12.6.4 - OpenJDK 64-Bit Server VM Homebrew

It seems using `ORDER BY` (in a sub-query) changes or does not preserve the result type.

### Expected behavior
```
[{"num":1},{"num":2},{"num":3},{"num":4},{"num":5}]
```

### Actual behavior

<details> <summary>Error on command execution (PostCommandHandler)</summary>

```
java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, com.arcadedb.query.sql.parser.SimpleNode
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.ArrayList.toArray(ArrayList.java:433)
	at com.arcadedb.query.sql.parser.OrderBy.getCacheableElements(OrderBy.java:83)
	at com.arcadedb.query.sql.parser.SimpleNode.refersToParent(SimpleNode.java:178)
	at com.arcadedb.query.sql.parser.SelectStatement.refersToParent(SelectStatement.java:257)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.extractSubQueries(SelectExecutionPlanner.java:697)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.optimizeQuery(SelectExecutionPlanner.java:414)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.createExecutionPlan(SelectExecutionPlanner.java:132)
	at com.arcadedb.query.sql.parser.SelectStatement.createExecutionPlan(SelectStatement.java:212)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:206)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:97)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1264)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:421)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:92)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:127)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

### Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
INSERT INTO doc (num) VALUES (1),(3),(5),(2),(4)
```
This fails:
```
SELECT coalesce((SELECT num FROM doc ORDER BY num))
```
while this works:
```
SELECT coalesce((SELECT num FROM doc))
```

**Comment by lvca** [comment]
Reproduced and fixed.

**Comment by gramian** [comment]
I confirm it is working.
