### ISSUE TITLE
SQL: `BACKUP DATABASE` default backup directory missing?

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1069]
### ArcadeDB Version:
`ArcadeDB Server v23.4.1 (build 883f95ecf80cadab0efed640391e8d8b9b95b30f/1683145819920/main)`
### OS and JDK Version:
`Running on Mac OS X 12.6.4 - OpenJDK 64-Bit Server VM 11.0.19 (Homebrew)`

The new release `23.4.1` triggers an error on the SQL `BACKUP DATABASE` command. It seems the default backup directory is not correctly set, see: https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/GlobalConfiguration.java#L270

### Expected behavior
Succesful backup

### Actual behavior

<details> <summary>Error on command execution (PostCommandHandler)</summary>

```
Error on command execution (PostCommandHandler)
java.lang.NullPointerException
	at com.arcadedb.ContextConfiguration$1.resolve(ContextConfiguration.java:40)
	at com.arcadedb.ContextConfiguration$1.resolve(ContextConfiguration.java:34)
	at com.arcadedb.utility.VariableParser.resolveVariables(VariableParser.java:52)
	at com.arcadedb.utility.SystemVariableResolver.resolveSystemVariables(SystemVariableResolver.java:47)
	at com.arcadedb.utility.SystemVariableResolver.resolveSystemVariables(SystemVariableResolver.java:40)
	at com.arcadedb.ContextConfiguration.getVariable(ContextConfiguration.java:212)
	at com.arcadedb.ContextConfiguration.getValueAsString(ContextConfiguration.java:175)
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:64)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:63)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:97)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1281)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:436)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:92)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:127)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

### Steps to reproduce
```
BACKUP DATABASE
```

The error does no occur if the setting `arcadedb.server.backupDirectory=backups` is provided.

**Comment by lvca** [comment]
The problem is with the setting of the global server root path. In case of multiple servers on the same JVM (usually with replication tests only), the setting is saved in the local server configuration and not in the global. The SQL command didn't have a way to access to the server configuration because independent.

I've added a new method signature to provide the configuration so all the commands executed through the server can now pass the server cfg.

**Comment by gramian** [comment]
Works for me. Thank you for this.
