### ISSUE TITLE
Average difference between datetime values is always NULL

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1103]
### ArcadeDB Version:
v23.5.1-SNAPSHOT (build d65cada76caa77742b5ab213b450139b9a4618fa/1684331816646/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)

### Expected behavior
It is possible to apply the SQL function `avg()` to the difference between two DATETIME properties.

### Actual behavior
the average of the difference between two DATETIME values is always NULL, maybe because the difference is expressed as a Duration object which is not an ArcadeDB property type.

### Steps to reproduce
Execute the attached testAverageDifferenceBetweenDateTimeValues test case

[testAverageDifferenceBetweenDateTimeValues.zip](https://github.com/ArcadeData/arcadedb/files/11585207/testAverageDifferenceBetweenDateTimeValues.zip)

**Comment by gramian** [comment]
Maybe you can convert the duration objects to [Unix Time](https://en.m.wikipedia.org/wiki/Unix_time) and then compute the average? I would try the `asInteger` method.

**Comment by vic0824** [comment]
Thank you for the suggestion, but unfortunately it does not seem to work:
`com.arcadedb.exception.CommandSQLParsingException: SELECT avg((pstop - pstart).asInteger()) AS average FROM Order`
I think the conversion only works between two property types recognized by ArcadeDB, but Duration is a Java type for which there is no corresponding ArcadeDB Type.
I have then tried to convert the individual dates to Long before computing the difference but I get a `java.lang.NumberFormatException: For input string: "2023-05-28T19:54:36.501"`, even though according to the manual it should work.
Looking at the source code, it seems that the `asLong()` function only checks if the source type is a Date, so when the new DateTime implementation is used, it cannot convert to a Long target type:
```
  public Object execute(final Object iThis, final Identifiable iCurrentRecord, final CommandContext iContext, Object ioResult, final Object[] iParams) {
    if (ioResult instanceof Number) {
      ioResult = ((Number) ioResult).longValue();
    } else if (ioResult instanceof Date) {
      ioResult = ((Date) ioResult).getTime();
    } else {
      ioResult = ioResult != null ? Long.valueOf(ioResult.toString().trim()) : null;
    }
    return ioResult;
  }
}
```
@lvca , when you implemented https://github.com/ArcadeData/arcadedb/issues/794 you briefly considered returning `<seconds>.<nanos>`  for a difference between datetime values, instead of a Duration. If that would be recognized by the sql parser as a double, maybe the avg() function would work without modifications.
Worst case, I'll write a custom SQL function that computes the difference as an integer number of a specified ChronoUnit.

**Comment by lvca** [comment]
Have you already tried:
- `SELECT avg( ( pstop.asLong() - pstart.asLong() ) ) AS average FROM Order`
- `SELECT avg( pstop.asLong() - pstart.asLong() ) AS average FROM Order`

**Comment by vic0824** [comment]
Yep, `SELECT pstop.asLong() AS tmp FROM Order` produces:
```
java.lang.NumberFormatException: For input string: "2023-05-29T12:13:39.250"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.valueOf(Long.java:1144)
	at com.arcadedb.query.sql.method.misc.SQLMethodAsLong.execute(SQLMethodAsLong.java:47)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:130)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:77)
	at com.arcadedb.query.sql.parser.Modifier.execute(Modifier.java:96)
	at com.arcadedb.query.sql.parser.BaseExpression.execute(BaseExpression.java:153)
	at com.arcadedb.query.sql.parser.Expression.execute(Expression.java:87)
	at com.arcadedb.query.sql.parser.ProjectionItem.execute(ProjectionItem.java:137)
	at com.arcadedb.query.sql.parser.Projection.calculateSingle(Projection.java:126)
	at com.arcadedb.query.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:66)
	at com.arcadedb.query.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:51)
	at com.arcadedb.query.sql.parser.LocalResultSet.next(LocalResultSet.java:76)
	at eu.serco.csrs.persistence.ArcadeDBTest.testAverageDifferenceBetweenDateTimeProperties(ArcadeDBTest.java:336)
```

**Comment by lvca** [comment]
This is definitely a bug, it should be supported from date time to long. Let me check on this.

**Comment by lvca** [comment]
Fixed the issue with `.asLong()`. Now you should be able to do the average.

**Comment by vic0824** [comment]
Tested, it works, thanks.
