### ISSUE TITLE
ArcadeDB-Studio With Gremlin-Server No Longer Accessible Upon Its Docker-Container Restart

### ISSUE THREAD

**Issue by ZachMurray** [ArcadeData/arcadedb#1106]
### ArcadeDB Version:

`ArcadeDB Server v23.3.1-SNAPSHOT (build 0393db01efcce6d393482991ff18b330970081ef/1678969633791/main)`

### OS and JDK Version:

`Running on Linux 5.10.102.1-microsoft-standard-WSL2 - OpenJDK 64-Bit Server VM Temurin-11.0.18+10`

### Expected behavior

ArcadeDB-Studio would be accessible upon startup-restart. 
I expected to see the webpage load like I saw before when I was first using ArcadeDB.

### Actual behavior

Unable to access ArcadeDB-Studio upon its [Docker-container]((https://hub.docker.com/r/arcadedata/arcadedb)) restart. 

```powershell
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

### Steps to reproduce

1. Create a [ArcadeDB-Docker-instance with Gremlin-Server-Plugin turned-on](https://docs.arcadedb.com/#Gremlin-API)
2. Verify [ArcadeDB-Studio](https://docs.arcadedb.com/#Studio) opens up properly 
3. Stop the ArcadeDB 
4. Restart, Stop-Restart, Stop-Start ArcadeDB-container with Docker-UI 
5. See that ArcadeDB-Studio is no longer loading and other APIs aren't working as expected either 

`log output` 
```powershell
2023-05-31 07:34:46  █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
2023-05-31 07:34:46 ██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
2023-05-31 07:34:46 ███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
2023-05-31 07:34:46 ██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
2023-05-31 07:34:46 ██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
2023-05-31 07:34:46 ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
2023-05-31 07:34:46 PLAY WITH DATA                                    arcadedb.com
2023-05-31 07:34:46 removing old pid file /home/arcadedb/bin/arcadedb.pid
2023-05-31 07:34:46 
2023-05-31 07:34:46 2023-05-31 12:34:46.796 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.3.1-SNAPSHOT (build 0393db01efcce6d393482991ff18b330970081ef/1678969633791/main) is starting up...
2023-05-31 07:34:46 2023-05-31 12:34:46.807 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Linux 5.10.102.1-microsoft-standard-WSL2 - OpenJDK 64-Bit Server VM Temurin-11.0.18+10
2023-05-31 07:34:46 2023-05-31 12:34:46.807 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [Redis, MongoDB, Postgres, GremlinServer] ...
2023-05-31 07:34:47 2023-05-31 12:34:46.819 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2023-05-31 07:34:48 2023-05-31 12:34:47.632 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz...
2023-05-31 07:34:48 2023-05-31 12:34:48.312 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format OrientDB (parsingLimitBytes=9.54MB parsingLimitEntries=0)
2023-05-31 07:34:49 Importing OrientDB database from stream to './databases/Imported'
2023-05-31 07:34:49 Creation of the schema: types, properties and indexes
2023-05-31 07:34:49 - Created index UNIQUE on Beer[id]
2023-05-31 07:34:49 - Created index UNIQUE on Brewery[id]
2023-05-31 07:34:49 - Created index UNIQUE on Style[id]
2023-05-31 07:34:49 - Created index UNIQUE on Category[id]
2023-05-31 07:34:49 Creation of records started: creating vertices and documents records (edges on the next phase)
2023-05-31 07:34:49 2023-05-31 12:34:48.312 INFO  [Importer] <ArcadeDB_0> Checking schema...Exception in thread "main" com.arcadedb.exception.CommandExecutionException: Error on importing database
2023-05-31 07:34:49 - Status update: parsed 9,997 (9,997/sec) - 0 documents (0/sec) - 5,417 vertices (5,417/sec) - 0 edges (0/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
2023-05-31 07:34:49     at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:69)
2023-05-31 07:34:49     at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
2023-05-31 07:34:49     at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:52)
2023-05-31 07:34:49     at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:77)
2023-05-31 07:34:49     at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:61)
2023-05-31 07:34:49     at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:104)
2023-05-31 07:34:49     at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1257)
2023-05-31 07:34:49     at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
2023-05-31 07:34:49     at com.arcadedb.server.ArcadeDBServer.loadDefaultDatabases(ArcadeDBServer.java:495)
2023-05-31 07:34:49     at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:139)
2023-05-31 07:34:49     at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:92)
2023-05-31 07:34:49 Caused by: com.arcadedb.integration.importer.ImportException: Error on parsing source 'https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz (compressed=true size=1085781)'
2023-05-31 07:34:49     at com.arcadedb.integration.importer.Importer.load(Importer.java:63)
2023-05-31 07:34:49     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-31 07:34:49     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-05-31 07:34:49     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-31 07:34:49     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-05-31 07:34:49     at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:61)
2023-05-31 07:34:49     ... 10 more
2023-05-31 07:34:49 Caused by: com.arcadedb.exception.DuplicatedKeyException: Duplicated key [1] found on index 'Category[id]' already assigned to record #73:0
2023-05-31 07:34:49     at com.arcadedb.database.TransactionIndexContext.checkUniqueIndexKeys(TransactionIndexContext.java:344)
2023-05-31 07:34:49     at com.arcadedb.database.TransactionIndexContext.checkUniqueIndexKeys(TransactionIndexContext.java:379)
2023-05-31 07:34:49     at com.arcadedb.database.TransactionIndexContext.commit(TransactionIndexContext.java:161)
2023-05-31 07:34:49     at com.arcadedb.database.TransactionContext.commit1stPhase(TransactionContext.java:487)
2023-05-31 07:34:49     at com.arcadedb.database.TransactionContext.commit(TransactionContext.java:114)
2023-05-31 07:34:49     at com.arcadedb.database.EmbeddedDatabase.lambda$commit$2(EmbeddedDatabase.java:356)
2023-05-31 07:34:49     at com.arcadedb.database.EmbeddedDatabase.executeInReadLock(EmbeddedDatabase.java:1326)
2023-05-31 07:34:49     at com.arcadedb.database.EmbeddedDatabase.commit(EmbeddedDatabase.java:351)
2023-05-31 07:34:49     at com.arcadedb.integration.importer.OrientDBImporter.parseRecords(OrientDBImporter.java:341)
2023-05-31 07:34:49     at com.arcadedb.integration.importer.OrientDBImporter.parseInputFile(OrientDBImporter.java:287)
2023-05-31 07:34:49     at com.arcadedb.integration.importer.OrientDBImporter.run(OrientDBImporter.java:176)
2023-05-31 07:34:49     at com.arcadedb.integration.importer.format.OrientDBImporterFormat.load(OrientDBImporterFormat.java:48)
2023-05-31 07:34:49     at com.arcadedb.integration.importer.Importer.loadFromSource(Importer.java:93)
2023-05-31 07:34:49     at com.arcadedb.integration.importer.Importer.load(Importer.java:54)
2023-05-31 07:34:49     ... 15 more
```

`shell command` 
```powershell
docker run -d --name arcadeDb -p 2424:2424 -p 2480:2480 -p 8182:8182 
       --env JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata 
          -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz} 
          -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin " 
          arcadedata/arcadedb:latest
```

**Comment by lvca** [comment]
This happens only from the 2nd time you start the docker container, right?

**Comment by lvca** [comment]
@ZachMurray any chance you can try my last comment?

**Comment by lvca** [comment]
Closing this issue after a while. In case, please comment here to reopen it.
