### ISSUE TITLE
GremlinServer DatabaseOperationException: Found active instance of database './databases/graph' already in use

### ISSUE THREAD

**Issue by ZachMurray** [ArcadeData/arcadedb#1107]
### ArcadeDB Version:
`ArcadeDB Server v23.3.1-SNAPSHOT (build 0393db01efcce6d393482991ff18b330970081ef/1678969633791/main)`
### OS and JDK Version:
`Running on Linux 5.10.102.1-microsoft-standard-WSL2 - OpenJDK 64-Bit Server VM Temurin-11.0.18+10`

### Expected behavior

Following the [Gremlin-API](https://docs.arcadedb.com/#Gremlin-API) docs would result in a clean successful startup. 
This works if you omit `-Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}` in the `JAVA_OPTS.value`. 
Seems like `-Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin` already adds it, even if the output doesn't show this data being added. 

```powershell
2023-06-01 08:20:21 - you can find your new ArcadeDB database in './databases/Imported'
2023-06-01 08:20:21 - Status update: parsed 0 (-5,423/sec) - 0 documents (0/sec) - 7,467 vertices (2,050/sec) - 14,908 edges (14,908/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
```

### Actual behavior
```powershell
2023-06-01 08:12:43 2023-06-01 13:12:43.555 INFO  [ArcadeDBServer] <ArcadeDB_0> - GremlinServer plugin startedException in thread "main" com.arcadedb.exception.DatabaseOperationException: Found active instance of database './databases/graph' already in use
2023-06-01 08:12:43     at com.arcadedb.database.DatabaseFactory.checkForActiveInstance(DatabaseFactory.java:139)
2023-06-01 08:12:43     at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:72)
2023-06-01 08:12:43     at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:399)
2023-06-01 08:12:43     at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:283)
2023-06-01 08:12:43     at com.arcadedb.server.ArcadeDBServer.loadDatabases(ArcadeDBServer.java:421)
2023-06-01 08:12:43     at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:144)
2023-06-01 08:12:43     at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:92)
2023-06-01 08:12:43
```

### Steps to reproduce
Run ArcadeDB-Docs Gremlin-API startup command 
```powershell
docker run -d --name arcadeDb -p 2424:2424 -p 2480:2480 -p 8182:8182 \
       --env JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata \
          -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz} \
          -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin " \
          arcadedata/arcadedb:latest
```

```powershell
2023-06-01 07:32:58 
2023-06-01 07:32:58  █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
2023-06-01 07:32:58 ██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
2023-06-01 07:32:58 ███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
2023-06-01 07:32:58 ██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
2023-06-01 07:32:58 ██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
2023-06-01 07:32:58 ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
2023-06-01 07:32:58 PLAY WITH DATA                                    arcadedb.com
2023-06-01 07:32:58 
2023-06-01 07:32:58 2023-06-01 12:32:58.367 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.3.1-SNAPSHOT (build 0393db01efcce6d393482991ff18b330970081ef/1678969633791/main) is starting up...
2023-06-01 07:32:58 2023-06-01 12:32:58.376 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Linux 5.10.102.1-microsoft-standard-WSL2 - OpenJDK 64-Bit Server VM Temurin-11.0.18+10
2023-06-01 07:32:58 2023-06-01 12:32:58.377 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [GremlinServer] ...
2023-06-01 07:32:58 2023-06-01 12:32:58.389 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2023-06-01 07:32:58 2023-06-01 12:32:58.418 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
2023-06-01 07:32:59 2023-06-01 12:32:58.514 INFO  [ArcadeDBServer] <ArcadeDB_0> Creating default database 'Imported'...
2023-06-01 07:33:00 2023-06-01 12:32:59.071 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz...
2023-06-01 07:33:00 2023-06-01 12:33:00.298 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format OrientDB (parsingLimitBytes=9.54MB parsingLimitEntries=0)
2023-06-01 07:33:01 Importing OrientDB database from stream to './databases/Imported'
2023-06-01 07:33:01 Creation of the schema: types, properties and indexes
2023-06-01 07:33:01 - Created type 'V' with the following properties {}
2023-06-01 07:33:01 - Created type 'Beer' with the following properties {id=INTEGER}
2023-06-01 07:33:01 - Created type 'Brewery' with the following properties {id=INTEGER}
2023-06-01 07:33:01 - Created type 'Category' with the following properties {id=INTEGER}
2023-06-01 07:33:01 - Created type 'E' with the following properties {}
2023-06-01 07:33:01 - Created type 'HasBrewery' with the following properties {}
2023-06-01 07:33:01 - Created type 'HasCategory' with the following properties {}
2023-06-01 07:33:01 - Created type 'HasStyle' with the following properties {}
2023-06-01 07:33:01 - Created type 'Style' with the following properties {id=INTEGER}
2023-06-01 07:33:01 - Created index UNIQUE on Beer[id]
2023-06-01 07:33:02 - Created index UNIQUE on Brewery[id]
2023-06-01 07:33:02 - Created index UNIQUE on Style[id]
2023-06-01 07:33:02 - Created index UNIQUE on Category[id]
2023-06-01 07:33:02 Creation of records started: creating vertices and documents records (edges on the next phase)
2023-06-01 07:33:02 - Creation of records completed: created 7,467 vertices and 0 documents, skipped 14,908 edges (7,467 records/sec elapsed=1 secs)
2023-06-01 07:33:02 Creation of edges started: creating edges between vertices
2023-06-01 07:33:03 - Creation of edges completed: created 14,908 edges {HasStyle=4433, HasBrewery=5901, HasCategory=4574} (14,908 edges/sec elapsed=1 secs)
2023-06-01 07:33:03 Dropping empty 'V' base vertex type (in OrientDB all the vertices have their own class
2023-06-01 07:33:03 Dropping empty 'E' base edge type (in OrientDB all the edges have their own class
2023-06-01 07:33:03 ***************************************************************************************************
2023-06-01 07:33:03 Import of OrientDB database completed in 1 secs with 0 errors and 0 warnings.
2023-06-01 07:33:03 
2023-06-01 07:33:03 SUMMARY
2023-06-01 07:33:03 
2023-06-01 07:33:03 - Records..................................: 7,484
2023-06-01 07:33:03 -- Beer                                    : 5,901 
2023-06-01 07:33:03 -- Brewery                                 : 1,414 
2023-06-01 07:33:03 -- Category                                : 11 
2023-06-01 07:33:03 -- E                                       : 0 
2023-06-01 07:33:03 -- HasBrewery                              : 5,901 
2023-06-01 07:33:03 -- HasCategory                             : 4,574 
2023-06-01 07:33:03 -- HasStyle                                : 4,433 
2023-06-01 07:33:03 -- OFunction                               : 0  (excluded)
2023-06-01 07:33:03 -- OIdentity                               : 0  (excluded)
2023-06-01 07:33:03 -- ORestricted                             : 0  (excluded)
2023-06-01 07:33:03 -- ORole                                   : 3  (excluded)
2023-06-01 07:33:03 -- OSchedule                               : 0  (excluded)
2023-06-01 07:33:03 -- OSecurityPolicy                         : 4  (excluded)
2023-06-01 07:33:03 -- OSequence                               : 0  (excluded)
2023-06-01 07:33:03 -- OTriggered                              : 0  (excluded)
2023-06-01 07:33:03 -- OUser                                   : 3  (excluded)
2023-06-01 07:33:03 -- Style                                   : 141 
2023-06-01 07:33:03 -- V                                       : 0 
2023-06-01 07:33:03 -- _studio                                 : 7  (excluded)
2023-06-01 07:33:03 - Total attributes.........................: 513,424
2023-06-01 07:33:03 ***************************************************************************************************
2023-06-01 07:33:03 
2023-06-01 07:33:03 NOTES:
2023-06-01 07:33:03 - users stored in OUser class will not be imported because ArcadeDB has users only at server level. If you want to import such users into ArcadeDB server configuration, please run the importer with the option -s <securityFileDirectory>
2023-06-01 07:33:03 - you can find your new ArcadeDB database in './databases/Imported'
2023-06-01 07:33:03 - Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 7,467 vertices (1,866/sec) - 14,908 edges (3,727/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
2023-06-01 07:33:03 2023-06-01 12:33:00.299 INFO  [Importer] <ArcadeDB_0> Checking schema...WARNING: An illegal reflective access operation has occurred
2023-06-01 07:33:03 WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/arcadedb/lib/arcadedb-gremlin-23.3.1-SNAPSHOT.jar) to method java.lang.Object.finalize()
2023-06-01 07:33:03 WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
2023-06-01 07:33:03 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2023-06-01 07:33:03 WARNING: All illegal access operations will be denied in a future release
2023-06-01 07:33:03 
2023-06-01 07:33:03 2023-06-01 12:33:03.805 INFO  [DefaultGraphManager] Graph [graph] was successfully configured via [./config/gremlin-server.properties].
2023-06-01 07:33:03 2023-06-01 12:33:03.805 INFO  [ServerGremlinExecutor] Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2023-06-01 07:33:04 2023-06-01 12:33:03.811 INFO  [ServerGremlinExecutor] Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2023-06-01 07:33:04 2023-06-01 12:33:04.286 INFO  [ServerGremlinExecutor] Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2023-06-01 07:33:04 2023-06-01 12:33:04.289 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [g] with graphtraversalsource[arcadegraph[graph], standard]
2023-06-01 07:33:04 2023-06-01 12:33:04.289 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [graph] with graphtraversalsource[arcadegraph[graph], standard]
2023-06-01 07:33:04 2023-06-01 12:33:04.303 INFO  [OpLoader] Adding the standard OpProcessor.
2023-06-01 07:33:04 2023-06-01 12:33:04.449 INFO  [OpLoader] Adding the session OpProcessor.
2023-06-01 07:33:04 2023-06-01 12:33:04.450 INFO  [OpLoader] Adding the traversal OpProcessor.
2023-06-01 07:33:04 2023-06-01 12:33:04.472 INFO  [GremlinServer] Executing start up LifeCycleHook
2023-06-01 07:33:04 2023-06-01 12:33:04.482 INFO  [GremlinServer] Executed once at startup of Gremlin Server.
2023-06-01 07:33:04 2023-06-01 12:33:04.486 INFO  [GremlinServer] idleConnectionTimeout was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2023-06-01 07:33:04 2023-06-01 12:33:04.486 INFO  [GremlinServer] keepAliveInterval was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2023-06-01 07:33:04 2023-06-01 12:33:04.507 INFO  [AbstractChannelizer] Configured application/vnd.graphbinary-v1.0 with org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1
2023-06-01 07:33:04 2023-06-01 12:33:04.522 INFO  [AbstractChannelizer] Configured application/vnd.gremlin-v3.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
2023-06-01 07:33:04 2023-06-01 12:33:04.523 INFO  [AbstractChannelizer] Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
2023-06-01 07:33:04 2023-06-01 12:33:04.526 INFO  [AbstractChannelizer] Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0
2023-06-01 07:33:04 2023-06-01 12:33:04.526 INFO  [AbstractChannelizer] application/json already has org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0 configured - it will not be replaced by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0, change order of serialization configuration if this is not desired.
2023-06-01 07:33:04 2023-06-01 12:33:04.559 INFO  [ArcadeDBServer] <ArcadeDB_0> - GremlinServer plugin startedException in thread "main" com.arcadedb.exception.DatabaseOperationException: Found active instance of database './databases/graph' already in use
2023-06-01 07:33:04 at com.arcadedb.database.DatabaseFactory.checkForActiveInstance(DatabaseFactory.java:139)
2023-06-01 07:33:04 at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:72)
2023-06-01 07:33:04 at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:399)
2023-06-01 07:33:04 at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:283)
2023-06-01 07:33:04 at com.arcadedb.server.ArcadeDBServer.loadDatabases(ArcadeDBServer.java:421)
2023-06-01 07:33:04 at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:144)
2023-06-01 07:33:04 at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:92)
2023-06-01 07:33:04 
2023-06-01 07:33:04 2023-06-01 12:33:04.563 INFO  [GremlinServer] Gremlin Server configured with worker thread pool of 1, gremlin pool of 20 and boss thread pool of 1.
```

**Comment by lvca** [comment]
Just tried with the latest version and works. Please upgrade to 23.5.1 or later.

```

 █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
PLAY WITH DATA                                    arcadedb.com


2023-06-10 03:05:28.122 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.5.1-SNAPSHOT (build 85ef3bcede162398feaf0aa198782d31e11b55b3/1685057519575/vector-model) is starting up...
2023-06-10 03:05:28.140 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Linux 5.15.49-linuxkit - OpenJDK 64-Bit Server VM 11.0.19 (Temurin-11.0.19+7)
2023-06-10 03:05:28.141 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [GremlinServer] ...
2023-06-10 03:05:28.168 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2023-06-10 03:05:28.225 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
2023-06-10 03:05:28.481 INFO  [ArcadeDBServer] <ArcadeDB_0> Creating default database 'Imported'...
2023-06-10 03:05:28.874 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz...
2023-06-10 03:05:30.117 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format OrientDB (parsingLimitBytes=9.54MB parsingLimitEntries=0)
Importing OrientDB database from stream to './databases/Imported'
Creation of the schema: types, properties and indexes
- Created type 'V' with the following properties {}
- Created type 'Beer' with the following properties {id=INTEGER}
- Created type 'Brewery' with the following properties {id=INTEGER}
- Created type 'Category' with the following properties {id=INTEGER}
- Created type 'E' with the following properties {}
- Created type 'HasBrewery' with the following properties {}
- Created type 'HasCategory' with the following properties {}
- Created type 'HasStyle' with the following properties {}
- Created type 'Style' with the following properties {id=INTEGER}
- Created index UNIQUE on Beer[id]
- Created index UNIQUE on Brewery[id]
- Created index UNIQUE on Style[id]
- Created index UNIQUE on Category[id]
Creation of records started: creating vertices and documents records (edges on the next phase)
- Creation of records completed: created 7,467 vertices and 0 documents, skipped 14,908 edges (7,467 records/sec elapsed=1 secs)
Creation of edges started: creating edges between vertices
- Creation of edges completed: created 14,908 edges {HasStyle=4433, HasBrewery=5901, HasCategory=4574} (7,454 edges/sec elapsed=2 secs)
Dropping empty 'V' base vertex type (in OrientDB all the vertices have their own class
Dropping empty 'E' base edge type (in OrientDB all the edges have their own class
***************************************************************************************************
Import of OrientDB database completed in 2 secs with 0 errors and 0 warnings.

SUMMARY

- Records..................................: 7,484
-- Beer                                    : 5,901
-- Brewery                                 : 1,414
-- Category                                : 11
-- E                                       : 0
-- HasBrewery                              : 5,901
-- HasCategory                             : 4,574
-- HasStyle                                : 4,433
-- OFunction                               : 0  (excluded)
-- OIdentity                               : 0  (excluded)
-- ORestricted                             : 0  (excluded)
-- ORole                                   : 3  (excluded)
-- OSchedule                               : 0  (excluded)
-- OSecurityPolicy                         : 4  (excluded)
-- OSequence                               : 0  (excluded)
-- OTriggered                              : 0  (excluded)
-- OUser                                   : 3  (excluded)
-- Style                                   : 141
-- V                                       : 0
-- _studio                                 : 7  (excluded)
- Total attributes.........................: 513,424
***************************************************************************************************

NOTES:
- users stored in OUser class will not be imported because ArcadeDB has users only at server level. If you want to import such users into ArcadeDB server configuration, please run the importer with the option -s <securityFileDirectory>
- you can find your new ArcadeDB database in './databases/Imported'
- Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 7,467 vertices (1,866/sec) - 14,908 edges (3,727/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
2023-06-10 03:05:30.118 INFO  [Importer] <ArcadeDB_0> Checking schema...WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/arcadedb/lib/arcadedb-gremlin-23.5.1-SNAPSHOT.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

2023-06-10 03:05:33.981 INFO  [DefaultGraphManager] Graph [graph] was successfully configured via [./config/gremlin-server.properties].
2023-06-10 03:05:33.982 INFO  [ServerGremlinExecutor] Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2023-06-10 03:05:33.990 INFO  [ServerGremlinExecutor] Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2023-06-10 03:05:34.857 INFO  [ServerGremlinExecutor] Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2023-06-10 03:05:34.861 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [g] with graphtraversalsource[arcadegraph[graph], standard]
2023-06-10 03:05:34.861 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [graph] with graphtraversalsource[arcadegraph[graph], standard]
2023-06-10 03:05:34.871 INFO  [OpLoader] Adding the standard OpProcessor.
2023-06-10 03:05:35.034 INFO  [OpLoader] Adding the session OpProcessor.
2023-06-10 03:05:35.035 INFO  [OpLoader] Adding the traversal OpProcessor.
2023-06-10 03:05:35.065 INFO  [GremlinServer] Executing start up LifeCycleHook
2023-06-10 03:05:35.092 INFO  [GremlinServer] Executed once at startup of Gremlin Server.
2023-06-10 03:05:35.098 INFO  [GremlinServer] idleConnectionTimeout was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2023-06-10 03:05:35.099 INFO  [GremlinServer] keepAliveInterval was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2023-06-10 03:05:35.141 INFO  [AbstractChannelizer] Configured application/vnd.graphbinary-v1.0 with org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1
2023-06-10 03:05:35.166 INFO  [AbstractChannelizer] Configured application/vnd.gremlin-v3.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
2023-06-10 03:05:35.168 INFO  [AbstractChannelizer] Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
2023-06-10 03:05:35.171 INFO  [AbstractChannelizer] Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0
2023-06-10 03:05:35.175 INFO  [AbstractChannelizer] application/json already has org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0 configured - it will not be replaced by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0, change order of serialization configuration if this is not desired.
2023-06-10 03:05:35.220 INFO  [ArcadeDBServer] <ArcadeDB_0> - GremlinServer plugin started
2023-06-10 03:05:35.226 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489 httpsPort=2490-2499)...
2023-06-10 03:05:35.235 INFO  [GremlinServer] Gremlin Server configured with worker thread pool of 1, gremlin pool of 2 and boss thread pool of 1.
2023-06-10 03:05:35.236 INFO  [GremlinServer] Channel started at port 8182.
2023-06-10 03:05:35.369 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480 httpsPort=2490)
2023-06-10 03:05:35.371 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [sqlscript, mongo, gremlin, java, cypher, js, graphql, sql]
2023-06-10 03:05:35.372 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started in 'development' mode (CPUs=2 MAXRAM=2.00GB)
```

**Comment by dijef** [comment]
I tried 23.11.1 and bug is still there. I unpacked database and executed:
`server.bat "-Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin"`
then received this error:
```
ARCADEDB server script path = C:\Workspace\Tools\DB\arcadedb-23.11.1\bin\server.bat
ARCADEDB home directory     = C:\Workspace\Tools\DB\arcadedb-23.11.1

2024-01-02 15:12:15.074 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.11.1 (build 798b2b6f581bb4e6017535815dc3257f72c5fd81/1701318772588/main) is starting up...
2024-01-02 15:12:15.080 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 17.0.8 (Temurin-17.0.8+7)
2024-01-02 15:12:15.084 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [GremlinServer] ...
2024-01-02 15:12:15.084 INFO  [ArcadeDBServer] <ArcadeDB_0> - Metrics Collection Started...

+--------------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION                    |
+--------------------------------------------------------------------+
| This is the first time the server is running. Please type a        |
| password of your choice for the 'root' user or leave it blank      |
| to auto-generate it.                                               |
|                                                                    |
| To avoid this message set the environment variable or JVM          |
| setting `arcadedb.server.rootPassword` to the root password to use.|
+--------------------------------------------------------------------+

Root password [BLANK=auto generate it]: *********
Please type the root password for confirmation (copy and paste will not work): *********

2024-01-02 15:12:22.594 INFO  [DefaultGraphManager] Graph [graph] was successfully configured via [./config/gremlin-server.properties].
2024-01-02 15:12:22.596 INFO  [ServerGremlinExecutor] Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2024-01-02 15:12:22.602 INFO  [ServerGremlinExecutor] Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2024-01-02 15:12:23.325 INFO  [ServerGremlinExecutor] Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2024-01-02 15:12:23.328 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [g] with graphtraversalsource[arcadegraph[./databases/graph], standard]
2024-01-02 15:12:23.329 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [graph] with graphtraversalsource[arcadegraph[./databases/graph], standard]
2024-01-02 15:12:23.344 INFO  [OpLoader] Adding the standard OpProcessor.
2024-01-02 15:12:23.511 INFO  [OpLoader] Adding the session OpProcessor.
2024-01-02 15:12:23.513 INFO  [OpLoader] Adding the traversal OpProcessor.
2024-01-02 15:12:23.529 INFO  [GremlinServer] Executing start up LifeCycleHook
2024-01-02 15:12:23.534 INFO  [GremlinServer] Executed once at startup of Gremlin Server.
2024-01-02 15:12:23.537 INFO  [GremlinServer] idleConnectionTimeout was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2024-01-02 15:12:23.537 INFO  [GremlinServer] keepAliveInterval was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2024-01-02 15:12:23.553 INFO  [AbstractChannelizer] Configured application/vnd.graphbinary-v1.0 with org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1
2024-01-02 15:12:23.563 INFO  [AbstractChannelizer] Configured application/vnd.gremlin-v3.0+json with org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3
2024-01-02 15:12:23.564 INFO  [AbstractChannelizer] Configured application/json with org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3
2024-01-02 15:12:23.566 INFO  [AbstractChannelizer] Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV2
2024-01-02 15:12:23.566 INFO  [AbstractChannelizer] application/json already has org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3 configured - it will not be replaced by org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV2, change order of serialization configuration if this is not desired.
2024-01-02 15:12:23.620 INFO  [ArcadeDBServer] <ArcadeDB_0> - GremlinServer plugin startedException in thread "main" com.arcadedb.exception.DatabaseOperationException: Found active instance of database 'C:\Workspace\Tools\DB\arcadedb-23.11.1\databases\graph' already in use
        at com.arcadedb.database.DatabaseFactory.checkForActiveInstance(DatabaseFactory.java:149)
        at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:74)
        at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:461)
        at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:318)
        at com.arcadedb.server.ArcadeDBServer.loadDatabases(ArcadeDBServer.java:489)
        at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:161)
        at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:106)

2024-01-02 15:12:23.623 INFO  [GremlinServer] Gremlin Server configured with worker thread pool of 1, gremlin pool of 20 and boss thread pool of 1.
2024-01-02 15:12:23.624 INFO  [GremlinServer] Channel started at port 8182.
```

If then stopped and started again, it starts OK.
