### ISSUE TITLE
Composite Index corrupted after UPDATE

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1113]
### ArcadeDB Version:
v23.5.1-SNAPSHOT (build 5412036f00b3f2a91c31c83174a14e032e19b85c/1685452164158/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)

### Expected behavior
After an update, a Select query with a Where clause on a field which is part of a composite index will find the correct record.

### Actual behavior
After an update, a Select query with a Where clause on a field which is part of a composite index cannot find the correct record.

### Steps to reproduce
Execute the attached testWhereAfterUpdate test case.

[testWhereAfterUpdate.zip](https://github.com/ArcadeData/arcadedb/files/11651312/testWhereAfterUpdate.zip)

**Comment by lvca** [comment]
Trying to run your test case but I don't see errors:

```

insert result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#1:0"}
insert result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
update result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"COMPLETED","@cat":"d","@type":"Order","@rid":"#1:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"COMPLETED","@cat":"d","@type":"Order","@rid":"#1:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}

Process finished with exit code 0
```

**Comment by vic0824** [comment]
It's weird, it fails for me:
```
2023-06-07 08:31:35.073 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.5.1-SNAPSHOT (build 5412036f00b3f2a91c31c83174a14e032e19b85c/1685452164158/main) is starting up...
2023-06-07 08:31:35.084 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)
2023-06-07 08:31:35.085 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [] ...
2023-06-07 08:31:35.174 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2023-06-07 08:31:35.387 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489 httpsPort=2490-2499)...
2023-06-07 08:31:35.969 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480 httpsPort=2490)
2023-06-07 08:31:35.970 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [sqlscript, java, js, sql]
2023-06-07 08:31:35.973 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started in 'development' mode (CPUs=8 MAXRAM=3.93GB)
2023-06-07 08:31:35.973 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://172.21.32.1:2480 
insert result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
insert result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:1"}
update result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"COMPLETED","@cat":"d","@type":"Order","@rid":"#2:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"COMPLETED","@cat":"d","@type":"Order","@rid":"#2:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:1"}
Exception in thread "main" org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
	at eu.serco.csrs.persistence.ArcadeDBTest.testWhereAfterUpdate(ArcadeDBTest.java:195)
	at eu.serco.csrs.persistence.ArcadeDBTest.main(ArcadeDBTest.java:67)
```
In my test class, line 195 is: `Assertions.assertTrue(resultSet.hasNext());`

**Comment by vic0824** [comment]
Pulled the latest snapshot, run clean + install, re-compiled my Test class, and it still fails:
```
2023-06-07 08:45:40.746 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.5.1-SNAPSHOT (build 3a5380ee1e5fe0a7514bf74119a901b09380c1e7/1686119608920/main) is starting up...
2023-06-07 08:45:40.754 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)
2023-06-07 08:45:40.756 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [] ...
2023-06-07 08:45:40.837 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2023-06-07 08:45:41.052 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489 httpsPort=2490-2499)...
2023-06-07 08:45:41.573 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480 httpsPort=2490)
2023-06-07 08:45:41.574 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [sqlscript, java, js, sql]
2023-06-07 08:45:41.575 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started in 'development' mode (CPUs=8 MAXRAM=3.93GB)
2023-06-07 08:45:41.575 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://172.21.32.1:2480 
insert result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
insert result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:1"}
update result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"COMPLETED","@cat":"d","@type":"Order","@rid":"#2:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557014764069841000,"vstop":1557014877423797000,"id":1,"status":"COMPLETED","@cat":"d","@type":"Order","@rid":"#2:0"}
select result = {"processor":"SIR1LRM-7.1","vstart":1557015037288211000,"vstop":1557015158236835000,"id":2,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:1"}
Exception in thread "main" org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
	at eu.serco.csrs.persistence.ArcadeDBTest.testWhereAfterUpdate(ArcadeDBTest.java:195)
	at eu.serco.csrs.persistence.ArcadeDBTest.main(ArcadeDBTest.java:67)
```

**Comment by lvca** [comment]
Could you please run the test `com.arcadedb.server.CompositeIndexTest`?

**Comment by vic0824** [comment]
The only difference between my test case and yours is that I create all the database schema objects in a transaction scope, but you don't.
Sure enough, if I move the type and index creation code out of the transaction scope, the test passes.
Why does this happens? The code examples in the manual show how to create types and it is always done inside a transaction.

**Comment by vic0824** [comment]
Tried to remove the transaction from my Project, and it still does not work.
After the update, the select query using `WHERE = 'PENDING'` does not work, however if I modify it to use `WHERE LIKE 'PENDING%'` it works. Does LIKE not use the index?

**Comment by lvca** [comment]
This issue is getting more interesting :-) I'm checking to see what's going on.

**Comment by vic0824** [comment]
Wait, it gets even weirder.
Out of sheer desperation, I have tried changing things that shouldn't have anything to do with the issue.
I have replaced the value PENDING with the value ELIGIBLE and now everything works, with or without transaction.
Is there something special about the way the value PENDING is interpreted by the engine?

**Comment by lvca** [comment]
No, pending is not a keyword... I'm debugging the 1st simple case where you create the schema in a tx.

**Comment by vic0824** [comment]
False alarm, I have tried again and it fails also with ELIGIBLE.

**Comment by lvca** [comment]
I see you use this UPSERT:

```sql
UPDATE Order SET id = ?, processor = ?, vstart = ?, vstop = ?, status = ? UPSERT RETURN AFTER WHERE processor = ? AND vstart = ? AND vstop = ?
```

But it shouldn't be allowed because it requires the WHERE condition to use the index. Look at the docs (UPSERT limitation paragraph):

https://docs.arcadedb.com/#SQL-Update

So I'm surprised the SQL engine swallows the syntax without any error.

**Comment by lvca** [comment]
Checked the OrientDB code and it's the same. I'm wondering if a syntax check is totally missing here.

**Comment by lvca** [comment]
It looks like that constraint was never applied in OrientDB, then ArcadeDB. So nevermind about the UPSERT. The point here is that the failing query is using a composite index with a partial key and fails. Checking on it.

**Comment by lvca** [comment]
Found the issue. The LSMTreeCursor, at build time, checks if the cursor is valid, but when it finds out that the 1st entry has been updated, it didn't continue with the next element. Fixed the issue locally, waiting to check for any regressions.

**Comment by vic0824** [comment]
It works, thanks!
