### ISSUE TITLE
LSMTreeIndexAbstract throws NPE during select after update of indexed property

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#1127]
### ArcadeDB Version:
v23.6.1-SNAPSHOT (build 8d904ae1fe473e0554998e73c0d3fcefb85b0639/1686373991520/main)
### OS and JDK Version:
Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.12 (Corretto-11.0.12.7.1)

### Expected behavior
a select query with a WHERE clause on the first property of a composite index continues to work after the property has been updated.

### Actual behavior
LSMTreeIndexAbstract throws NPE during select after update of indexed property

### Steps to reproduce
Execute the attached testSelectAfterUpdate test case and verify that the result is the following:

```
2023-06-13 08:56:55.288 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489 httpsPort=2490-2499)...
2023-06-13 08:56:55.392 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480 httpsPort=2490)
2023-06-13 08:56:55.393 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [sqlscript, java, js, sql]
2023-06-13 08:56:55.398 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started in 'development' mode (CPUs=8 MAXRAM=3.93GB)
2023-06-13 08:56:55.398 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://172.26.144.1:2480 
insert order 1 = {"id":1,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
update order 1 = {"id":1,"status":"ERROR","@cat":"d","@type":"Order","@rid":"#2:0"}
resubmit order 1 = {"id":1,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
retrieve order 1 by id = {"id":1,"status":"PENDING","@cat":"d","@type":"Order","@rid":"#2:0"}
java.lang.NullPointerException
	at com.arcadedb.index.lsm.LSMTreeIndexAbstract.isDeletedEntry(LSMTreeIndexAbstract.java:182)
	at com.arcadedb.index.lsm.LSMTreeIndexCursor.next(LSMTreeIndexCursor.java:286)
	at com.arcadedb.index.lsm.LSMTreeIndexCursor.next(LSMTreeIndexCursor.java:40)
	at com.arcadedb.index.MultiIndexCursor.next(MultiIndexCursor.java:143)
	at com.arcadedb.index.MultiIndexCursor.next(MultiIndexCursor.java:27)
	at com.arcadedb.query.sql.executor.FetchFromIndexStep.fetchNextEntry(FetchFromIndexStep.java:145)
	at com.arcadedb.query.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:347)
	at com.arcadedb.query.sql.executor.FetchFromIndexStep.processAndBlock(FetchFromIndexStep.java:281)
	at com.arcadedb.query.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:205)
	at com.arcadedb.query.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:189)
	at com.arcadedb.query.sql.executor.FetchFromIndexStep.syncPull(FetchFromIndexStep.java:85)
	at com.arcadedb.query.sql.executor.GetValueFromIndexEntryStep$1.fetchNextItem(GetValueFromIndexEntryStep.java:101)
	at com.arcadedb.query.sql.executor.GetValueFromIndexEntryStep$1.hasNext(GetValueFromIndexEntryStep.java:71)
	at com.arcadedb.query.sql.executor.ParallelExecStep.fetchNext(ParallelExecStep.java:86)
	at com.arcadedb.query.sql.executor.ParallelExecStep$1.hasNext(ParallelExecStep.java:53)
	at com.arcadedb.query.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:93)
	at com.arcadedb.query.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:61)
	at com.arcadedb.query.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:59)
	at com.arcadedb.query.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:97)
	at com.arcadedb.query.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:43)
	at com.arcadedb.query.sql.executor.OrderByStep.init(OrderByStep.java:113)
	at com.arcadedb.query.sql.executor.OrderByStep.syncPull(OrderByStep.java:58)
	at com.arcadedb.query.sql.executor.LimitExecutionStep.syncPull(LimitExecutionStep.java:48)
	at com.arcadedb.query.sql.executor.SelectExecutionPlan.fetchNext(SelectExecutionPlan.java:44)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:45)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:39)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:186)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:77)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:61)
	at com.arcadedb.query.sql.SQLQueryEngine.query(SQLQueryEngine.java:92)
	at com.arcadedb.database.EmbeddedDatabase.query(EmbeddedDatabase.java:1314)
	at com.arcadedb.server.ServerDatabase.query(ServerDatabase.java:463)
	at eu.serco.csrs.persistence.ArcadeDBTest.testSelectAfterUpdate(ArcadeDBTest.java:193)
	at eu.serco.csrs.persistence.ArcadeDBTest.main(ArcadeDBTest.java:76)

2023-06-13 08:56:55.535 INFO  [ArcadeDBServer] <ArcadeDB_0> Shutting down ArcadeDB Server...
2023-06-13 08:56:56.534 INFO  [ArcadeDBServer] <ArcadeDB_0> - Stop JMX Metrics
2023-06-13 08:56:56.534 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server is down
Process finished with exit code 0

```

[testSelectAfterUpdate.zip](https://github.com/ArcadeData/arcadedb/files/11731626/testSelectAfterUpdate.zip)

**Comment by lvca** [comment]
Reproduced.

**Comment by lvca** [comment]
Fixed. Thanks!
