### ISSUE TITLE
Vector: Server hangs after vector import and restart

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1162]
### ArcadeDB Version:
ArcadeDB Server v23.7.1-SNAPSHOT (build 41925cd705ecf0fb0d16df405a98f62303653305/1688933360012/main) is starting up...
Running on Mac OS X 12.6.5 - OpenJDK 64-Bit Server VM 11.0.19 (Homebrew)

Importing a vector database (via studio), shutting down the server and restarting causes ArcadeDB to hang on the restart.

### Expected behavior

Normal start up

### Actual behavior

```
Exception in thread "main" com.arcadedb.exception.DatabaseOperationException: Error on creating new database instance
	at com.arcadedb.database.EmbeddedDatabase.openInternal(EmbeddedDatabase.java:1727)
	at com.arcadedb.database.EmbeddedDatabase.open(EmbeddedDatabase.java:183)
	at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:76)
	at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:446)
	at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:303)
	at com.arcadedb.server.ArcadeDBServer.loadDatabases(ArcadeDBServer.java:471)
	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:138)
	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:99)
Caused by: com.arcadedb.exception.RecordNotFoundException: Record #5:1 not found
	at com.arcadedb.database.RID.asVertex(RID.java:133)
	at com.arcadedb.database.RID.asVertex(RID.java:126)
	at com.arcadedb.index.vector.HnswVectorIndex.<init>(HnswVectorIndex.java:169)
	at com.arcadedb.index.vector.HnswVectorIndex$PaginatedComponentFactoryHandlerUnique.createOnLoad(HnswVectorIndex.java:108)
	at com.arcadedb.engine.ComponentFactory.createComponent(ComponentFactory.java:52)
	at com.arcadedb.schema.EmbeddedSchema.load(EmbeddedSchema.java:167)
	at com.arcadedb.database.EmbeddedDatabase.openInternal(EmbeddedDatabase.java:1699)
	... 7 more
Caused by: com.arcadedb.exception.SchemaException: Bucket with id '5' was not found
	at com.arcadedb.schema.EmbeddedSchema.getBucketById(EmbeddedSchema.java:281)
	at com.arcadedb.database.EmbeddedDatabase.lambda$lookupByRID$13(EmbeddedDatabase.java:652)
	at com.arcadedb.database.EmbeddedDatabase.executeInReadLock(EmbeddedDatabase.java:1354)
	at com.arcadedb.database.EmbeddedDatabase.lookupByRID(EmbeddedDatabase.java:639)
	at com.arcadedb.database.RID.asVertex(RID.java:131)
	... 13 more
```

### Steps to reproduce

1 . `import database file://importer-glove.txt with distanceFunction = 'cosine', m = 16, efConstruction = 128, ef = 128;` (`importer-glove.txt` is the mini test data set from the tests)
2. CTRL+C shutdown ArcadeDB server
3. Restart ArcadeDB server

**Comment by lvca** [comment]
Reproduced. The issue is on database load: the new HNSW index should be initiated AFTER the entire database schema is loaded, otherwise the buckets are not found.
