### ISSUE TITLE
When showing the schema in Studio, labels with ':' aren't shown

### ISSUE THREAD

**Issue by marco-brandizi** [ArcadeData/arcadedb#1169]
### ArcadeDB Version:
23.4.1
### OS and JDK Version:
* macOS 13.4 (22F66)
* openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)
* Browsers: Chrome 114.0.5735.198, Firefox 114.0.2

### Expected behavior
I've uploaded a graphML file using Gremlin, the graph in the file has 'emulated multiple labels', ie, labels like ``Concept:Protein:Resource`` . In the schema visualisation, when I select one of the listed labels, it should show details on the right as usually.

### Actual behavior
the main column on the right of the labels column remains blank, the browser's Javascript console shows: 

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#tab-Concept:Protein:Resource' is not a valid selector.
    at Object.getSelectorFromElement (http://localhost:2480/js/bootstrap.min.js:6:1466)
    at t.show (http://localhost:2480/js/bootstrap.min.js:6:50519)
    at HTMLAnchorElement.<anonymous> (http://localhost:2480/js/bootstrap.min.js:6:52210)
    at Function.each (http://localhost:2480/js/jquery-1.12.4.min.js:2:2881)
    at n.fn.init.each (http://localhost:2480/js/jquery-1.12.4.min.js:2:846)
    at i._jQueryInterface [as tab] (http://localhost:2480/js/bootstrap.min.js:6:52033)
    at HTMLAnchorElement.<anonymous> (http://localhost:2480/js/bootstrap.min.js:6:52367)
    at HTMLDocument.dispatch (http://localhost:2480/js/jquery-1.12.4.min.js:3:12444)
    at r.handle (http://localhost:2480/js/jquery-1.12.4.min.js:3:9173)
```

This is a Javascript/Studio problem, the vertex type and its instance are in the DB, I can query them, i can see them from `select from schema:vertexes`, I can use them in the CLI console.

### Steps to reproduce
Just create a vertex with label `Concept:Protein:Resource` and try to show the details in the Studio.

**Comment by lvca** [comment]
The issue has been fixed in `main` branch.

**Comment by marco-brandizi** [comment]
> The issue has been fixed in `main` branch.
>
Many thanks! You might want to generalise this to all (or most) possible bad characters, see [here](https://stackoverflow.com/questions/2849756)
