### ISSUE TITLE
DbVisualizer with Postgres Driver causes Error on Reconnect

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1177]
### ArcadeDB Version:
ArcadeDB Server v23.7.1-SNAPSHOT (build aac7596ca347179a2ac1b7b7f86214e34b196932/1689712378146/main)
### OS and JDK Version:
Running on Mac OS X 12.6.5 - OpenJDK 64-Bit Server VM 11.0.19 (Homebrew)

### Expected behavior
No error

### Actual behavior

```
Exception in thread "ArcadeDB-postgres//127.0.0.1" Exception in thread "ArcadeDB-postgres//127.0.0.1" com.arcadedb.postgres.PostgresProtocolException: Error on parsing startup message
	at com.arcadedb.postgres.PostgresNetworkExecutor.readStartupMessage(PostgresNetworkExecutor.java:934)
	at com.arcadedb.postgres.PostgresNetworkExecutor.run(PostgresNetworkExecutor.java:96)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at com.arcadedb.network.binary.ChannelBinary.readUnsignedInt(ChannelBinary.java:79)
	at com.arcadedb.postgres.PostgresNetworkExecutor.readStartupMessage(PostgresNetworkExecutor.java:871)
	... 1 more
com.arcadedb.postgres.PostgresProtocolException: Error on parsing startup message
	at com.arcadedb.postgres.PostgresNetworkExecutor.readStartupMessage(PostgresNetworkExecutor.java:934)
	at com.arcadedb.postgres.PostgresNetworkExecutor.run(PostgresNetworkExecutor.java:96)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at com.arcadedb.network.binary.ChannelBinary.readUnsignedInt(ChannelBinary.java:79)
	at com.arcadedb.postgres.PostgresNetworkExecutor.readStartupMessage(PostgresNetworkExecutor.java:871)
	... 1 more
```

### Steps to reproduce
1. Follow the steps in https://docs.arcadedb.com/#_dbvisualizer
2. On the "Connection" tab click "Ping Server", "Connect" and then "Reconnect" (sometimes "Reconnect" needs to be pressed multiple times)

**Comment by menchyshyn** [comment]
I've experienced the same issue with Postgres plugin when running the Docker image. I tried all the Docker images with tags: latest, 23.6.1, 23.5.1, 23.4.1, 23.3.1, 23.2.1, 23.1.2

**Comment by gramian** [comment]
This seems to be fixed now. Please reopen if it persists for you.
