### ISSUE TITLE
Rest API for document does not recognize DB name properly

### ISSUE THREAD

**Issue by mindreframer** [ArcadeData/arcadedb#1210]
### ArcadeDB Version:
`ArcadeDB Server v23.7.1 (build 3213507e324358b3d1af59654e8c3f02f9c894ad/1692053118580/main)`
### OS and JDK Version:
`Running on Mac OS X 12.3.1 - OpenJDK 64-Bit Server VM 17.0.1`

### Expected behavior
Using `http://localhost:2480/api/v1/document` should work properly. 

### Actual behavior
```bash 
arcadedb-23.7.1|⇒ curl -X POST http://localhost:2480/api/v1/document/school \
                           -d '{"@type": "Class", "name": "English", "location": "3rd floor"}' \
                           -H "Content-Type: application/json" \
                           --user root:playwithdata
{"error":"Internal error","detail":"Database \u0027school\u0027 is not available","exception":"com.arcadedb.exception.DatabaseOperationException"}⏎
```

### Steps to reproduce
```
> create database school
> create document type Class
> insert into Class set name = 'English', location = '3rd floor';
```

`<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>`

**Comment by mindreframer** [comment]
Exception log from the server
```bash
com.arcadedb.exception.DatabaseOperationException: Database 'school' is not available
	at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:423)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:62)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:125)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

But the DB is available in console
```bash
arcadedb-23.7.1|⇒ bin/console.sh
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
ArcadeDB Console v.23.7.1 - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)
>
> connect school

Database 'school' connected
{school}>
```

**Comment by mindreframer** [comment]
OK, after restarting the server and stopping the console it seems to be working: 

```bash
$ arcadedb-23.7.1|⇒ curl -X POST http://localhost:2480/api/v1/document/school \
                           -d '{"@type": "Class", "name": "English", "location": "3rd floor"}' \
                           -H "Content-Type: application/json" \
                           --user root:playwithdata
{ "result" : "#1:1"}⏎
```

It is a bit weird that the server does not pick up on newly created databases. Also it is not possible to connect to this DB from the console anymore, is this normal? 

```bash 
arcadedb-23.7.1|⇒ bin/console.sh
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
ArcadeDB Console v.23.7.1 - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)
>
> connect school

ERROR:
com.arcadedb.console.ConsoleException: Database appears locked by server
	at com.arcadedb.console.Console.checkDatabaseIsLocked(Console.java:896)
	at com.arcadedb.console.Console.executeConnect(Console.java:410)
	at com.arcadedb.console.Console.execute(Console.java:249)
	at com.arcadedb.console.Console.parse(Console.java:731)
	at com.arcadedb.console.Console.interactiveMode(Console.java:129)
	at com.arcadedb.console.Console.execute(Console.java:179)
	at com.arcadedb.console.Console.main(Console.java:142)


>
```

**Comment by lvca** [comment]
If you create the database from the console using an embedded connection, it would be created in the local file system. You should rather connect to the server with the console and create the database on the server.

```sql
create database remote:localhost/school root playwithdata;
```

**Comment by mindreframer** [comment]
@lvca Thanks for the explanation! Connecting to remote server works without issues!
