### ISSUE TITLE
cannot restore database

### ISSUE THREAD

**Issue by ChipNowacek** [ArcadeData/arcadedb#123]
## Expected behavior
database restored

## Actual behavior
null pointer exception

## Steps to reproduce
From inside image. Tried without database created, after trying to create from console, and after creating from Studio.
```
/home/arcadedb # pwd
/home/arcadedb
/home/arcadedb # ls
LICENSE                                  bin                                      databases                                questions-backup-20211011-015429344.zip
README.md                                config                                   lib
/home/arcadedb # bin/restore.sh -f /home/arcadedb/questions-backup-20211011-015429344.zip  -database databases/questions
Exception in thread "main" com.arcadedb.integration.restore.RestoreException: Error during restore of database from file '/home/arcadedb/questions-backup-20211011-015429344.zip'
	at com.arcadedb.integration.restore.Restore.restoreDatabase(Restore.java:55)
	at com.arcadedb.integration.restore.Restore.main(Restore.java:42)
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.arcadedb.integration.restore.format.FullRestoreFormat.restoreDatabase(FullRestoreFormat.java:50)
	at com.arcadedb.integration.restore.Restore.restoreDatabase(Restore.java:52)
	... 1 more
/home/arcadedb # ls databases/
/home/arcadedb # ls bin/
arcadedb.pid      backups           console.bat       console.sh        restore.sh        server.bat        server.sh         stresstester.bat  stresstester.sh
/home/arcadedb # bin/console.sh 
ArcadeDB Console v.21.10.2-SNAPSHOT - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)

> create database questions


{questions}> ?

HELP
begin                               -> begins a new transaction
check database                      -> check database integrity
close                               -> closes the database
create database <path>|remote:<url> -> creates a new database
commit                              -> commits current transaction
connect <path>|remote:<url>         -> connects to a database stored on <path>
help|?                              -> ask for this help
info types                          -> print available types
info transaction                    -> print current transaction
rollback                            -> rollbacks current transaction
quit or exit                        -> exits from the console


{questions}> exit
/home/arcadedb # ls databases/
/home/arcadedb # bin/restore.sh -f /home/arcadedb/questions-backup-20211011-015429344.zip  -database databases/questions
Exception in thread "main" com.arcadedb.integration.restore.RestoreException: Error during restore of database from file '/home/arcadedb/questions-backup-20211011-015429344.zip'
	at com.arcadedb.integration.restore.Restore.restoreDatabase(Restore.java:55)
	at com.arcadedb.integration.restore.Restore.main(Restore.java:42)
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.arcadedb.integration.restore.format.FullRestoreFormat.restoreDatabase(FullRestoreFormat.java:50)
	at com.arcadedb.integration.restore.Restore.restoreDatabase(Restore.java:52)
	... 1 more
/home/arcadedb # 

```

**Comment by lvca** [comment]
Reproduced. The problem was in the documentation. The right parameter is `-d` instead of `-database`. Created a PR to throw an exception in case the database path is missing.
