### ISSUE TITLE
SQL: `INSERT INTO ... SET` DOES not work for edges

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1324]
### ArcadeDB Version:
`ArcadeDB Server v23.11.1-SNAPSHOT (build a94b5b08489af67df07b4b83031bb339dc34416d/1699913702726/main)`
### OS and JDK Version:
`Running on Mac OS X 12.7 - OpenJDK 64-Bit Server VM 17.0.9 (Homebrew)`

Inserting an edge via `INSERT INTO <edge> SET @in = rid, @out = rid` fails.

### Expected behavior
Edge can be inserted via `INSERT`

### Actual behavior

<details> <summary>Cannot execute command Encountered <SET></summary>

```
Error on command execution (PostCommandHandler)
java.lang.IllegalArgumentException: Cannot instantiate an edge
	at com.arcadedb.query.sql.executor.CreateRecordStep$1.next(CreateRecordStep.java:74)
	at com.arcadedb.query.sql.executor.SetDocumentClassStep$1.next(SetDocumentClassStep.java:51)
	at com.arcadedb.query.sql.executor.UpdateSetStep$1.next(UpdateSetStep.java:48)
	at com.arcadedb.query.sql.executor.SaveElementStep$1.next(SaveElementStep.java:53)
	at com.arcadedb.query.sql.executor.InsertExecutionPlan.executeInternal(InsertExecutionPlan.java:67)
	at com.arcadedb.query.sql.parser.InsertStatement.execute(InsertStatement.java:124)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:73)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:101)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1328)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:467)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:129)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:96)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:99)
	at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
</details>

### Steps to reproduce
```
CREATE VERTEX TYPE v;
INSERT INTO v SET test = 'a';
INSERT INTO v SET test = 'b'; 
CREATE EDGE TYPE e;
INSERT INTO e SET @in = #1:0, @out #4:0, test = 'test';
```

**Comment by lvca** [comment]
I see you're using the create edge command, not the insert to create edges.

**Comment by gramian** [comment]
🤦

**Comment by lvca** [comment]
I don't think that insert into an edge type was ever supported by OrientDB.  What's the use case why you prefer using the insert instead of the create edge? Is create edge command working?

**Comment by gramian** [comment]
`CREATE EDGE` is working. I was trying an example from the docs and it failed.

**Comment by gramian** [comment]
I will remove the faulty example from the docs then.
