### ISSUE TITLE
Issue on loading multi-page records under heavy load

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1402]
By experimenting with some modifications to the test RandomTestMultiThreadsTest, I was able to reproduce under heavy load a recurrent exception about loading a multi-page record.

**Comment by lvca** [comment]
Another issue is with checking the retrieved UUID is correct. This happens only when a unique index is defined.

**Comment by lvca** [comment]
The error with RandomTestMultiThreadsTest happens only when a unique index is created on `uuid` property.

**Comment by lvca** [comment]
```
Looking for 9 but found 45
Exception in thread "Thread-33" org.opentest4j.AssertionFailedError: 
expected: 9L
 but was: 45L
	at com.arcadedb.RandomTestMultiThreadsTest$1.run(RandomTestMultiThreadsTest.java:127)
	at java.base/java.lang.Thread.run(Thread.java:840)
Looking for 9 but found 1
Exception in thread "Thread-14" org.opentest4j.AssertionFailedError: 
expected: 9L
 but was: 1L
	at com.arcadedb.RandomTestMultiThreadsTest$1.run(RandomTestMultiThreadsTest.java:127)
	at java.base/java.lang.Thread.run(Thread.java:840)
Looking for 9 but found 333
Exception in thread "Thread-20" org.opentest4j.AssertionFailedError: 
expected: 9L
 but was: 333L
	at com.arcadedb.RandomTestMultiThreadsTest$1.run(RandomTestMultiThreadsTest.java:127)
	at java.base/java.lang.Thread.run(Thread.java:840)

Process finished with exit code 0
```

**Comment by lvca** [comment]
Partially fixed, there is still a chance of loading an old page on high MT scenarios with concurrent insert, update and delete. Leaving the issue open for the next release.
