### ISSUE TITLE
NPE on using remote vertices `toMap()`

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1413]
From Discord channel:

I think I found an error. Look at this code:

```java
        db.begin();
        
        RemoteMutableVertex nvSaved = db.newVertex("SimpleVertex");
        nvSaved.set("s", UUID.randomUUID().toString());
        nvSaved.save();
        System.out.println("rs> "+nvSaved.toMap(true));
```

it produce this error:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.arcadedb.schema.DocumentType.getName()" because "this.type" is null
    at com.arcadedb.database.MutableDocument.toMap(MutableDocument.java:100)
    at com.arcadedb.graph.MutableVertex.toMap(MutableVertex.java:190)
    at test.DirectConnect.testInicial(DirectConnect.java:88)
```

**Comment by lvca** [comment]
Fixed.
