### ISSUE TITLE
Error on RemoteMutableVertex getType call.

### ISSUE THREAD

**Issue by mdre** [ArcadeData/arcadedb#1420]
### ArcadeDB Version:  

`23.12.2`

### OS and JDK Version:

`Running on Linux 6.5.0-14-generic -  OpenJDK 64-Bit Server VM 17.0.9`

### Expected behavior
Get the document type

### Actual behavior

```java
Exception in thread "main" java.lang.UnsupportedOperationException: Schema API are not supported in remote database
    at com.arcadedb.remote.RemoteMutableVertex.getType(RemoteMutableVertex.java:116)
    at test.DirectConnect.testInicial(DirectConnect.java:90)
``` 

### Steps to reproduce

```java
        RemoteMutableVertex nvSaved = db.newVertex("SimpleVertex");
        nvSaved.set("s", UUID.randomUUID().toString());
        nvSaved.save();
        System.out.println("type: "+nvSaved.getType());
```

**Comment by lvca** [comment]
Fixed! Sorry, it was super easy to fix but it took a long time.
