### ISSUE TITLE
Edge Creation with RID as input to Parameterized Query Not Working as Expected

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1430]
Edge creation statement as parameterized query fails with exception when RID are provided as inputs for from and to rid

```
       RemoteDatabase db=new RemoteDatabase("localhost", 
                                                    2480, 
                                                    "test_db", 
                                                    "root", 
                                                    "password");

           //The below commented out section generates exception                                         
        /*
        * Exception in thread "main" com.arcadedb.remote.RemoteException: 
        * Error on executing remote operation CREATE EDGE ZEdg FROM :fromRid TO :toRid 
        * (cause:com.arcadedb.exception.CommandExecutionException detail:Invalid vertex for edge creation: #9:0)
        at com.arcadedb.remote.RemoteHttpComponent.manageException(RemoteHttpComponent.java:446)
        at com.arcadedb.remote.RemoteHttpComponent.httpCommand(RemoteHttpComponent.java:170)
        at com.arcadedb.remote.RemoteDatabase.databaseCommand(RemoteDatabase.java:461)
        at com.arcadedb.remote.RemoteDatabase.command(RemoteDatabase.java:398)
        at com.arcadedb.remote.RemoteDatabase.command(RemoteDatabase.java:383)
        at com.optimas.EdgeCreationtest.main(EdgeCreationtest.java:29)
        */
        /*String statement="CREATE EDGE ZEdg FROM :fromRid TO :toRid";

        String fromVtxRid="#9:0";
        String toVtxRid="#33:0";

        Map<String, Object> params=new HashMap<>();
        params.put("fromRid", new RID(null, fromVtxRid));
        params.put("toRid", new RID(null, toVtxRid));

        db.command("sql", statement, params);
        */
        //This section works and creates the edge
        String statement="CREATE EDGE ZEdg FROM #9:0 TO #33:0";
        db.command("sql", statement);

        System.out.println("Done ... ");
```

The exception is coming from CreateEdgesStep [https://github.com/ArcadeData/arcadedb/blob/1a7716d309bbcbfdac089d42adee56b38fe2f6d3/engine/src/main/java/com/arcadedb/query/sql/executor/CreateEdgesStep.java#L252](url)

The above has the routine to do RID specific processing (if statement) which is not engaging. 
I am actually sending an RID object from client, it's getting converted to a Result object on the server side after JSON serialization/deserialization.

**Comment by ironluca** [comment]
Server side trace is given below
```

<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Invalid vertex for edge creation: #9:0
	at com.arcadedb.query.sql.executor.CreateEdgesStep.asVertex(CreateEdgesStep.java:261)
	at com.arcadedb.query.sql.executor.CreateEdgesStep.init(CreateEdgesStep.java:175)
	at com.arcadedb.query.sql.executor.CreateEdgesStep.syncPull(CreateEdgesStep.java:78)
	at com.arcadedb.query.sql.executor.SaveElementStep.syncPull(SaveElementStep.java:44)
	at com.arcadedb.query.sql.executor.SelectExecutionPlan.fetchNext(SelectExecutionPlan.java:44)
	at com.arcadedb.query.sql.executor.InsertExecutionPlan.executeInternal(InsertExecutionPlan.java:62)
	at com.arcadedb.query.sql.parser.CreateEdgeStatement.execute(CreateEdgeStatement.java:67)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:73)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:101)
	at com.arcadedb.database.LocalDatabase.command(LocalDatabase.java:1348)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:472)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:131)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:110)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:100)
	at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lvca** [comment]
Reproduced
