### ISSUE TITLE
DbGate: Neither Postgres nor MongoDB connection working

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1444]
### ArcadeDB Version:

`ArcadeDB Server v23.12.2 (build 3cd54fb02edd0ef1ee36f9fbf70d7f40c3ce6658/1705862786120/main)`

### OS and JDK Version:

`Running on Mac OS X 12.7 - OpenJDK 64-Bit Server VM 17.0.9 (Homebrew)`

### Expected behavior

Connection to database

### Actual behavior

1. Postgres
   * DbGate:
```
error: Error on executing query: Unknown function name 'version'
    at t.Parser.parseErrorMessage (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:17:213256)
    at t.Parser.handlePacket (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:17:209896)
    at t.Parser.parse (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:17:208551)
    at Socket.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:9:142674)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

Error JSON: {
  "length": 78,
  "name": "error",
  "severity": "ERROR",
  "code": "XX000"
}

Connection: {
  "server": "***",
  "engine": "postgres@dbgate-plugin-postgres",
  "useDatabaseUrl": "***",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "databaseUrl": "***",
  "useSshTunnel": false,
  "useSsl": false,
  "user": "***",
  "password": "***",
  "passwordMode": "askPassword",
  "defaultDatabase": "***"
}

Platform: darwin
```
   * ArcadeDB: [No Log entry]

2. Mongo
  * DbGate:
```
MongoServerError: Error on executing MongoDB 'saslStart' command
    at O.onMessage (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:152616)
    at l.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:150438)
    at l.emit (node:events:390:28)
    at e (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:859844)
    at l._write (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:860263)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at l.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:390:28)

Error JSON: {
  "$err": "Error on executing MongoDB 'saslStart' command",
  "ok": 0
}

Connection: {
  "server": "***",
  "engine": "mongo@dbgate-plugin-mongo",
  "useDatabaseUrl": "***",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "databaseUrl": "***",
  "useSshTunnel": false,
  "useSsl": false,
  "user": "***",
  "password": "***",
  "passwordMode": "askPassword",
  "defaultDatabase": "***"
}

Platform: darwin
```
  * ArcadeDB:
```
INFO  [MongoWireProtocolHandler] client [id: 0x311466c4, L:/127.0.0.1:27017 - R:/127.0.0.1:51435] connected
INFO  [MongoWireProtocolHandler] client [id: 0xb5cac945, L:/127.0.0.1:27017 - R:/127.0.0.1:51436] connectedfailed to handle {"saslStart" : 1, "mechanism" : "SCRAM-SHA-1", "payload" : BinData(0, 6E2C2C6E3D726F6F742C723D5049502B4D4F3041536431446C345956565A76614572384E6968706752643958), "autoAuthorize" : 1, "options" : {"skipEmptyExchange" : true}, "$db" : "admin"}
de.bwaldvogel.mongo.exception.NoSuchCommandException: [Error 59] no such command: 'saslStart'
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleAdminCommand(AbstractMongoBackend.java:206)
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:335)
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleMessage(AbstractMongoBackend.java:412)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleMessage(MongoDatabaseHandler.java:73)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:62)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:27)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps to reproduce

DbGate: https://dbgate.org

* Postgres:
  1. Start server with postgres-plugin
  2. Start DbGate
  3. Create Postgres connection with 
     ```
     postgres://root:password@localhost:5432/test?sslmode=disable&preferQueryMode=simple
     ```

* Mongo:
  1. Start server with MongoDB plugin
  2. Start DbGate
  3. Create MongoDB connection with:
    ```
    mongodb://root:password@localhost:27017/test
    ```

**Comment by gramian** [comment]
With https://github.com/ArcadeData/arcadedb/pull/1479 merged, the postgres connector works.
