### ISSUE TITLE
RID as paramer is not recognized in TRAVERSE query for vertex as well as edge

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1445]
Similar/related to issue [1430](https://github.com/ArcadeData/arcadedb/issues/1430)

For traversal queries, for vertex or edge; if RID is provided as a parameter, it is not recognized and exception is generated

```
try{

        db.command("sql", "CREATE VERTEX TYPE TVtx IF NOT EXISTS");
        db.command("sql", "CREATE EDGE TYPE TEdg IF NOT EXISTS");
        RID newVtx0Id=db.command("sql", "CREATE VERTEX TVtx").next().getIdentity().get();
        RID newVtx1Id=db.command("sql", "CREATE VERTEX TVtx").next().getIdentity().get();

        Map<String, Object> params=new HashMap<>();
        params.put("fromRid", newVtx0Id);
        params.put("toRid", newVtx1Id);
        RID newEdgRid=db.command("sql", "CREATE EDGE TEdg FROM :fromRid TO :toRid", params).next().getIdentity().get();

        params.clear();
        params.put("rid", newVtx0Id);
        String traverseQuery="SELECT FROM (TRAVERSE out('TEdg') FROM :rid MAXDEPTH 1)";
        //This also does not recognize RID parameter
        //String traverseQuery="SELECT FROM (TRAVERSE inV() FROM :rid MAXDEPTH 1)";
        db.command("sql", traverseQuery, params);

    }catch(Exception e){e.printStackTrace();}
```
Exception 

```
com.arcadedb.exception.SchemaException: Type with name '#77:0' was not found
        at com.arcadedb.remote.RemoteHttpComponent.manageException(RemoteHttpComponent.java:433)
        at com.arcadedb.remote.RemoteHttpComponent.httpCommand(RemoteHttpComponent.java:170)
        at com.arcadedb.remote.RemoteDatabase.databaseCommand(RemoteDatabase.java:461)
        at com.arcadedb.remote.RemoteDatabase.command(RemoteDatabase.java:398)
        at com.arcadedb.remote.RemoteDatabase.command(RemoteDatabase.java:383)
```
Server Trace
![image](https://github.com/ArcadeData/arcadedb/assets/40290578/a7900423-db3f-446d-88e0-319a1561fe44)

**Comment by lvca** [comment]
Fixed

**Comment by ironluca** [comment]
@lvca  Tested, working perfectly, thanks for the fix

**Comment by lvca** [comment]
Thanks for the report!
