### ISSUE TITLE
com.arcadedb.exception.DatabaseOperationException: Error during read lock

### ISSUE THREAD

**Issue by sionguo** [ArcadeData/arcadedb#1499]
### ArcadeDB Version:

`24.1.1`

### OS and JDK Version:

` Mac OS X 14.3.1 - OpenJDK 64-Bit Server VM 17.0.9 (Corretto-17.0.9.8.1)`

### Actual behavior

com.arcadedb.exception.DatabaseOperationException: Error during read lock
	at com.arcadedb.database.LocalDatabase.executeInReadLock(LocalDatabase.java:1426) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.LocalDatabase.commit(LocalDatabase.java:392) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.LocalDatabase.transaction(LocalDatabase.java:1075) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.LocalDatabase.transaction(LocalDatabase.java:1037) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.server.ServerDatabase.transaction(ServerDatabase.java:338) ~[arcadedb-server-24.1.1.jar:na]
	at com.corilead.arcadedb.ArcadeDbServiceImpl.insertData(ArcadeDbServiceImpl.java:51) ~[classes/:na]
	at com.corilead.arcadedb.ArcadeDbServiceImplDubboWrap4.invokeMethod(ArcadeDbServiceImplDubboWrap4.java) ~[classes/:na]
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:73) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:100) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:55) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.ClassLoaderCallbackFilter.invoke(ClassLoaderCallbackFilter.java:38) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:79) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:44) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:100) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:54) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at com.corilead.dubbo.DubboContextProviderFilter.invoke(DubboContextProviderFilter.java:54) ~[classes/:na]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:192) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:54) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.ProfilerServerFilter.invoke(ProfilerServerFilter.java:58) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:133) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:327) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:194) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:156) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:177) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62) ~[dubbo-3.1.10.jar:3.1.10]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[dubbo-3.1.10.jar:3.1.10]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.OutOfMemoryError: Cannot reserve 200268328 bytes of direct buffer memory (allocated: 8562889078, limit: 8589934592)
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178) ~[na:na]
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121) ~[na:na]
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332) ~[na:na]
	at java.base/sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:243) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:89) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[na:na]
	at java.base/sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:878) ~[na:na]
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:864) ~[na:na]
	at com.arcadedb.engine.WALFile.append(WALFile.java:357) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.engine.WALFile.writeTransactionToFile(WALFile.java:289) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.engine.TransactionManager.lambda$writeTransactionToWAL$2(TransactionManager.java:150) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.engine.WALFile.acquire(WALFile.java:132) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.engine.TransactionManager.writeTransactionToWAL(TransactionManager.java:149) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.TransactionContext.commit2ndPhase(TransactionContext.java:632) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.TransactionContext.commit(TransactionContext.java:123) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.LocalDatabase.lambda$commit$2(LocalDatabase.java:397) ~[arcadedb-engine-24.1.1.jar:na]
	at com.arcadedb.database.LocalDatabase.executeInReadLock(LocalDatabase.java:1415) ~[arcadedb-engine-24.1.1.jar:na]
	... 42 common frames omitted

**Comment by sionguo** [comment]
I am using ten threads to save data, and after running for a period of time, the program throws an OOM

**Comment by sionguo** [comment]
Here is the code for me to start the service

 ```
GlobalConfiguration.SERVER_ROOT_PASSWORD.setValue(properties.getRootPassword());
    GlobalConfiguration.SERVER_ROOT_PATH.setValue(properties.getRootPath());
    ContextConfiguration config = new ContextConfiguration();
    config.setValue(GlobalConfiguration.SERVER_NAME, properties.getServerName());
    config.setValue(GlobalConfiguration.MAX_PAGE_RAM, 1024);
    config.setValue(GlobalConfiguration.FREE_PAGE_RAM, 80);

    ArcadeDBServer server = new ArcadeDBServer(config);
    server.start();
    return server;
```

**Comment by sionguo** [comment]
<img width="989" alt="image" src="https://github.com/ArcadeData/arcadedb/assets/26744630/536baeb8-a755-4dbd-9cd4-573e41f58708">

**Comment by sionguo** [comment]
<img width="1144" alt="image" src="https://github.com/ArcadeData/arcadedb/assets/26744630/783e30fe-6ceb-4417-bda8-252fce8dd789">

**Comment by lvca** [comment]
What's the RAM configured for the JVM where ArcadeDB is running?

**Comment by sionguo** [comment]
4G

**Comment by sionguo** [comment]
> What's the RAM configured for the JVM where ArcadeDB is running?

-Xms4g -Xmx4g

**Comment by lvca** [comment]
Ok, try to allocate more Heap RAM if you can. 4GB can be for many use cases, but for better performances or for high throughput 8GB is suggested.

**Comment by lvca** [comment]
Please let me know if you still have problems with 8GB.
