### ISSUE TITLE
Cypher request formating thru REST in windows causes an error

### ISSUE THREAD

**Issue by ExtReMLapin** [ArcadeData/arcadedb#1517]
### ArcadeDB Version:

`ArcadeDB Server v24.2.1 `

### OS and JDK Version:

`Running on Windows 10 10.0 - Java HotSpot(TM) 64-Bit Server VM 22`
We tested it on ubuntu with previous arcade db version, no issue, cannot update because of pre-production SLA.

When manually formating Cypher request, and sending thru REST, **there is no issue.** thru python rest api or thru web ui
When sending variables in payload + params, for ArcadeDB to auto format them (escape quotes etc), it fails.

```
PLAY WITH DATA                             https://arcadedb.com

ARCADEDB server script path = G:\arcadedb-24.2.1\bin\server.bat
ARCADEDB home directory     = G:\arcadedb-24.2.1

2024-03-21 17:45:35.671 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v24.2.1 (build ce2658d9f43625df903d593f39604003b0512bd5/1710272406173/main) is starting up...
2024-03-21 17:45:35.681 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Windows 10 10.0 - Java HotSpot(TM) 64-Bit Server VM 22
2024-03-21 17:45:35.692 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server in development mode with plugins [] ...
2024-03-21 17:45:35.693 INFO  [ArcadeDBServer] <ArcadeDB_0> - Metrics Collection Started...
2024-03-21 17:45:35.854 SEVER [GraalPolyglotEngine] <ArcadeDB_0> GraalVM Polyglot Engine: no languages found
2024-03-21 17:45:35.955 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489 httpsPort=2490-2499)...
2024-03-21 17:45:36.002 INFO  [undertow] starting server: Undertow - 2.3.12.Final
2024-03-21 17:45:36.009 INFO  [xnio] XNIO version 3.8.8.Final
2024-03-21 17:45:36.016 INFO  [nio] XNIO NIO Implementation Version 3.8.8.Final
2024-03-21 17:45:36.066 INFO  [threads] JBoss Threads version 3.5.0.Final
2024-03-21 17:45:36.178 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480 httpsPort=2490)
2024-03-21 17:45:36.178 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [sqlscript, mongo, gremlin, java, cypher, graphql, sql]
2024-03-21 17:45:36.179 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started in 'development' mode (CPUs=16 MAXRAM=7,98GB)
2024-03-21 17:45:36.197 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://192.168.14.216:2480 <ArcadeDB_0> Error on command execution (PostQueryHandler)
com.arcadedb.exception.CommandParsingException: Error on executing Cypher query
        at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:80)
        at com.arcadedb.cypher.query.CypherQueryEngine.query(CypherQueryEngine.java:64)
        at com.arcadedb.database.LocalDatabase.query(LocalDatabase.java:1378)
        at com.arcadedb.server.ServerDatabase.query(ServerDatabase.java:494)
        at com.arcadedb.server.http.handler.PostQueryHandler.executeCommand(PostQueryHandler.java:38)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:110)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:100)
        at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: com.arcadedb.exception.CommandExecutionException: Error on executing command
        at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:139)
        at com.arcadedb.cypher.ArcadeCypher.execute(ArcadeCypher.java:66)
        at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:77)
        ... 14 more
Caused by: javax.script.ScriptException: java.util.concurrent.ExecutionException: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 66
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:383)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:235)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:212)
        at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:73)
        ... 16 more
Caused by: java.util.concurrent.ExecutionException: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 66
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.getScriptClass(GremlinGroovyScriptEngine.java:572)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:379)
        ... 20 more
Caused by: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 66
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:900)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:258)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.lambda$load$0(GremlinGroovyScriptEngine.java:824)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
        at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.load(GremlinGroovyScriptEngine.java:822)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.load(GremlinGroovyScriptEngine.java:817)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3117)
        at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:144)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1968)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1918)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1966)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1949)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 66
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:83)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:255)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:193)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:175)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:129)
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:773)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:413)
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1264)
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:258)
        at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$3(CompilationUnit.java:207)
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:896)
        ... 45 more

```

python code to reproduce the error : 

```python
import requests

url = "http://localhost:2480/api/v1/query/test_RID2"
import json
json_payload = """{"command": "MERGE(n:NER {subtype: $type, name: $value_property, identity: $value_property}) RETURN ID(n)", "language": "cypher", "params": {"type": "TestNode", "value_property": "led"}}"""
payload = json.loads(json_payload)
headers = {"Content-Type": "application/json"}

response = requests.post(
    url,
    data=json_payload,

    auth=('root', 'rootroot'),
)
print(response.text)

```

chatgpt is being lazy and won't produce me working curl CLI code.

**Comment by lvca** [comment]
This issue is due to:

```
Caused by: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 66
```

Seems the JVM version is different. Could you please check the JVM version between Ubuntu and Windows?

**Comment by ExtReMLapin** [comment]
I'll take a look on monday, when I'm at the office 👍🏻

**Comment by ExtReMLapin** [comment]
Ubuntu : 

```txt

mars 25 07:24:03 cfia01 server.sh[4013958]: 2024-03-25 07:24:03.128 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v24.1.1 (build 48e937e9a860ea97a7f245994a9df8bdb6af56d2/1707162918298/main) is starting up...
mars 25 07:24:03 cfia01 server.sh[4013958]: 2024-03-25 07:24:03.139 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Linux 5.15.0-100-generic - OpenJDK 64-Bit Server VM 11.0.22

```

Windows 
```txt
2024-03-25 08:25:13.167 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v24.2.1 (build ce2658d9f43625df903d593f39604003b0512bd5/1710272406173/main) is starting up...
2024-03-25 08:25:13.177 INFO  [ArcadeDBServer] <ArcadeDB_0> Running on Windows 10 10.0 - Java HotSpot(TM) 64-Bit Server VM 22
```

**Comment by ExtReMLapin** [comment]
After realizing we're running OpenJDK on ubuntu and Oracle implementation on Windows, I moved the windows install to OpenJDK.


This version **DOESN'T WORK** `Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 21.0.2 (Microsoft-8905927)`

This version **DOES WORK** `Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.22 (Microsoft-8909545)`


It could be worth it to mention it in the readme or even showing a warning on windows when running with HotSpot

**Comment by lvca** [comment]
I'm going to update this section with your findings: https://docs.arcadedb.com/#Requirements

Likely, Gremlin is not compatible with the latest Java 21 in general, not only on Windows.
