### ISSUE TITLE
[REST Api][Cypher] Correct way to use params with batch nodes creations

### ISSUE THREAD

**Issue by ExtReMLapin** [ArcadeData/arcadedb#1524]
### ArcadeDB Version:

`Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.22 (Microsoft-8909545)`

### OS and JDK Version:

`Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 11.0.22 (Microsoft-8909545)`

When using the REST API, we can use parameters mapping to let ArcadeDB do the character escaping.

Works great with single node creation.

Now let's say I need to to create arount 5000 nodes. Without using param mapping it would look something like that : 

```python
    nodes_list_str = ', '.join([f"{{subtype: '{label}', name: '{value}', identity: '{value}'}}" for label, value in nodes])
    query = f"""
    UNWIND [{nodes_list_str}] AS node
    MERGE (n:NER {{subtype: node.subtype, name: node.name, identity: node.identity}})
    RETURN ID(n) AS node_id
    """
    res = database.query('cypher', query)
```

If we go dirty mode, we could create a param dictionary/json object with 15000 key-values (because of 5000 node with 3 params each).

The idea is to stick to the param query instead of formating myself the query.
For the sake of simplicity, here we'll create nodes with only one parameter.

For example, generating 10 nodes would look like this : 

```cypher
    UNWIND [{subtype: $type__0}, {subtype: $type__1}, {subtype: $type__2}, {subtype: $type__3}, {subtype: $type__4}, {subtype: $type__5}, {subtype: $type__6}, {subtype: $type__7}, {subtype: $type__8}, {subtype: $type__9}] AS node
    MERGE (n:NER {subtype: node.subtype})
    RETURN ID(n) AS node_id
```

with params :  

```json

{
    "type__0": "TestNode",
    "type__1": "TestNode",
    "type__2": "TestNode",
    "type__3": "TestNode",
    "type__4": "TestNode",
    "type__5": "TestNode",
    "type__6": "TestNode",
    "type__7": "TestNode",
    "type__8": "TestNode",
    "type__9": "TestNode"
}
```

### Now, while it feels quity nasty/dirty and it works, it is the main subject of this issue, is there a better way to do it ?

----------------

Now for the bugs.

While increasing the count of objects to create, still with the REST API, we get those kind of errors : 

* Creating **252** nodes with one param each : NO ISSUE
*  Creating **253** nodes with one param each : REST returns `Error on executing command`

<details>

<summary>details here</summary>

```txt
com.arcadedb.exception.CommandParsingException: Error on executing Cypher query
        at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:80)
        at com.arcadedb.cypher.query.CypherQueryEngine.query(CypherQueryEngine.java:64)
        at com.arcadedb.database.LocalDatabase.query(LocalDatabase.java:1378)
        at com.arcadedb.server.ServerDatabase.query(ServerDatabase.java:494)
        at com.arcadedb.server.http.handler.PostQueryHandler.executeCommand(PostQueryHandler.java:38)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:110)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:100)
        at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.arcadedb.exception.CommandExecutionException: Error on executing command
        at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:139)
        at com.arcadedb.cypher.ArcadeCypher.execute(ArcadeCypher.java:66)
        at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:77)
        ... 14 more
Caused by: javax.script.ScriptException: javax.script.ScriptException: java.lang.IllegalArgumentException: bad parameter count 256
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:383)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:235)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:212)
        at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:73)
        ... 16 more
Caused by: javax.script.ScriptException: java.lang.IllegalArgumentException: bad parameter count 256
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:702)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:381)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: bad parameter count 256
        at java.base/java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:123)
        at java.base/java.lang.invoke.MethodType.checkSlotCount(MethodType.java:180)
        at java.base/java.lang.invoke.MethodType.checkPtypes(MethodType.java:170)
        at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
        at java.base/java.lang.invoke.LambdaForm.methodType(LambdaForm.java:655)
        at java.base/java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:868)
        at java.base/java.lang.invoke.LambdaForm.prepare(LambdaForm.java:829)
        at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:468)
        at java.base/java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:54)
        at java.base/java.lang.invoke.BoundMethodHandle$Species_L.<init>(BoundMethodHandle.java:215)
        at java.base/java.lang.invoke.BoundMethodHandle$Species_L.copyWith(BoundMethodHandle.java:231)
        at java.base/java.lang.invoke.MethodHandles.dropArguments0(MethodHandles.java:3603)
        at java.base/java.lang.invoke.MethodHandles.dropArgumentsToMatch(MethodHandles.java:3707)
        at java.base/java.lang.invoke.MethodHandles.catchException(MethodHandles.java:4504)
        at org.codehaus.groovy.vmplugin.v8.Selector$MethodSelector.addExceptionHandler(Selector.java:877)
        at org.codehaus.groovy.vmplugin.v8.Selector$MethodSelector.setCallSiteTarget(Selector.java:1036)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fallback(IndyInterface.java:360)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.access$000(IndyInterface.java:50)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface$FallbackSupplier.get(IndyInterface.java:282)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.lambda$fromCache$1(IndyInterface.java:304)
        at org.codehaus.groovy.vmplugin.v8.CacheableCallSite.getAndPut(CacheableCallSite.java:70)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.lambda$fromCache$2(IndyInterface.java:301)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.doWithCallSite(IndyInterface.java:376)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:298)
        at Script2.run(Script2.groovy:1)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:679)
        ... 21 more

```

</details>

* Creating **254** nodes with one param each : REST returns `bootstrap method initialization exception`

<details>

<summary> details here </summary>

```
java.lang.BootstrapMethodError: bootstrap method initialization exception
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:194)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
        at Script2.run(Script2.groovy:1)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:679)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:381)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:235)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:212)
        at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:73)
        at com.arcadedb.cypher.ArcadeCypher.execute(ArcadeCypher.java:66)
        at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:77)
        at com.arcadedb.cypher.query.CypherQueryEngine.query(CypherQueryEngine.java:64)
        at com.arcadedb.database.LocalDatabase.query(LocalDatabase.java:1378)
        at com.arcadedb.server.ServerDatabase.query(ServerDatabase.java:494)
        at com.arcadedb.server.http.handler.PostQueryHandler.executeCommand(PostQueryHandler.java:38)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:110)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:100)
        at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.invoke.WrongMethodTypeException: cannot build collector
        at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.asTypeUncached(MethodHandleImpl.java:552)
        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:847)
        at java.base/java.lang.invoke.CallSite.makeUninitializedCallSite(CallSite.java:265)
        at java.base/java.lang.invoke.CallSite.<init>(CallSite.java:106)
        at java.base/java.lang.invoke.MutableCallSite.<init>(MutableCallSite.java:102)
        at org.codehaus.groovy.vmplugin.v8.CacheableCallSite.<init>(CacheableCallSite.java:56)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.realBootstrap(IndyInterface.java:227)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.bootstrap(IndyInterface.java:216)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:224)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:149)
        ... 26 more
Caused by: java.lang.IllegalArgumentException: too many arguments: Object[], length 255
        at java.base/java.lang.invoke.MethodHandleImpl.varargsArray(MethodHandleImpl.java:1680)
        at java.base/java.lang.invoke.MethodHandle.asCollector(MethodHandle.java:1223)
        at java.base/java.lang.invoke.MethodHandle.asCollector(MethodHandle.java:1173)
        at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.asTypeUncached(MethodHandleImpl.java:549)
        ... 35 more

```

</details>

* Creating 255 nodes with one param each : REST returns `java.lang.IllegalArgumentException: bad parameter count 256`

<details>

<summary> details here </summary>

```
java.lang.BootstrapMethodError: java.lang.IllegalArgumentException: bad parameter count 256
        at Script2.run(Script2.groovy:1)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:679)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:381)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:235)
        at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:212)
        at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:73)
        at com.arcadedb.cypher.ArcadeCypher.execute(ArcadeCypher.java:66)
        at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:77)
        at com.arcadedb.cypher.query.CypherQueryEngine.query(CypherQueryEngine.java:64)
        at com.arcadedb.database.LocalDatabase.query(LocalDatabase.java:1378)
        at com.arcadedb.server.ServerDatabase.query(ServerDatabase.java:494)
        at com.arcadedb.server.http.handler.PostQueryHandler.executeCommand(PostQueryHandler.java:38)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:110)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:100)
        at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: bad parameter count 256
        at java.base/java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:123)
        at java.base/java.lang.invoke.MethodType.checkSlotCount(MethodType.java:180)
        at java.base/java.lang.invoke.MethodType.checkPtypes(MethodType.java:170)
        at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
        at java.base/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:376)
        ... 23 more


```

</details>

*  Creating  946 (not 945) nodes with one param each : REST returns `Error on executing command`

  

<details>

  

<summary> details here </summary>

  

```

java.lang.BootstrapMethodError: java.lang.IllegalArgumentException: bad parameter count 256

com.arcadedb.exception.CommandParsingException: Error on executing Cypher  query

at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:80)

at com.arcadedb.cypher.query.CypherQueryEngine.query(CypherQueryEngine.java:64)

at com.arcadedb.database.LocalDatabase.query(LocalDatabase.java:1378)

at com.arcadedb.server.ServerDatabase.query(ServerDatabase.java:494)

at com.arcadedb.server.http.handler.PostQueryHandler.executeCommand(PostQueryHandler.java:38)

at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:110)

at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:100)

at com.arcadedb.server.http.handler.AbstractServerHttpHandler.handleRequest(AbstractServerHttpHandler.java:127)

at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)

at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)

at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)

at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)

at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)

at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)

at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: com.arcadedb.exception.CommandExecutionException: Error on executing command

at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:139)

at com.arcadedb.cypher.ArcadeCypher.execute(ArcadeCypher.java:66)

at com.arcadedb.cypher.query.CypherQueryEngine.command(CypherQueryEngine.java:77)

... 14 more

Caused by: javax.script.ScriptException: java.util.concurrent.ExecutionException: java.lang.StackOverflowError

at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:383)

at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)

at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:235)

at com.arcadedb.gremlin.ArcadeGremlin.executeStatement(ArcadeGremlin.java:212)

at com.arcadedb.gremlin.ArcadeGremlin.execute(ArcadeGremlin.java:73)

... 16 more

Caused by: java.util.concurrent.ExecutionException: java.lang.StackOverflowError

at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)

at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2005)

at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.getScriptClass(GremlinGroovyScriptEngine.java:572)

at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:379)

... 20 more

Caused by: java.lang.StackOverflowError

at org.codehaus.groovy.ast.expr.ConstantExpression.toString(ConstantExpression.java:77)

at java.base/java.lang.String.valueOf(String.java:2951)

at java.base/java.lang.StringBuilder.append(StringBuilder.java:172)

at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:987)

at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:77)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.prepareIndyCall(InvokeDynamicWriter.java:113)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeIndyCall(InvokeDynamicWriter.java:131)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeCachedCall(InvokeDynamicWriter.java:98)

at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:133)

at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:125)

at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:454)

at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:988)

at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:77)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.prepareIndyCall(InvokeDynamicWriter.java:113)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeIndyCall(InvokeDynamicWriter.java:131)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeCachedCall(InvokeDynamicWriter.java:98)

at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:133)

at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:125)

at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:454)

at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:988)

at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:77)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.prepareIndyCall(InvokeDynamicWriter.java:113)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeIndyCall(InvokeDynamicWriter.java:131)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeCachedCall(InvokeDynamicWriter.java:98)

at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:133)

at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:125)

at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:454)

at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:988)

at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:77)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.prepareIndyCall(InvokeDynamicWriter.java:113)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeIndyCall(InvokeDynamicWriter.java:131)

at org.codehaus.groovy.classgen.asm.indy.InvokeDynamicWriter.makeCachedCall(InvokeDynamicWriter.java:98)

[[[KEEPS REPEATING]]]

  

```

  

</details>

**Comment by ExtReMLapin** [comment]
I'm taking the bet the errors are linked to params mapping being turned into some kind of var-arg

**Comment by lvca** [comment]
You're right, there is a hard-coded limit with Groovy and 256 max number of parameters:

https://issues.apache.org/jira/browse/GROOVY-7367

You could create chunks with max 255 keys to bypass this limitation.
