### ISSUE TITLE
SQL: Async SQL command inside async HTTP command fails

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1537]
### ArcadeDB Version:

`ArcadeDB Server v24.2.1 (build 57c5f09424ebc7c8ec19c7775f514c80129245e5/1712181097174/main)`

### OS and JDK Version:

`Running on Mac OS X 12.7.4 - OpenJDK 64-Bit Server VM 17.0.10 (Homebrew)`

Sending an async command like `BACKUP DATABASE` via an async HTTP command (`awaitResponse: false`) causes an error.

### Expected behavior

Succesful database backup with async command. 

### Actual behavior

<details> <summary>Async command in database "test" failed.</summary>

```
SEVER [PostCommandHandler$1] Async command in database "test" failed.
com.arcadedb.exception.CommandExecutionException: Error on backing up database
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:79)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:52)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:65)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:116)
	at com.arcadedb.database.LocalDatabase.command(LocalDatabase.java:1327)
	at com.arcadedb.database.async.DatabaseAsyncCommand.execute(DatabaseAsyncCommand.java:59)
	at com.arcadedb.database.async.DatabaseAsyncExecutorImpl$AsyncThread.run(DatabaseAsyncExecutorImpl.java:134)
Caused by: com.arcadedb.integration.backup.BackupException: Error during backup of database 'test' to file 'test-backup-20240404-112752960.zip'
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:67)
	... 7 more
Caused by: com.arcadedb.integration.backup.BackupException: The backup file '/backups/test/test-backup-20240404-112752960.zip' cannot be created
	at com.arcadedb.integration.backup.format.FullBackupFormat.backupDatabase(FullBackupFormat.java:60)
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:66)
	... 12 more
```
</details>

### Steps to reproduce

Given a `test` database:

```shell
curl -X POST http://localhost:2480/api/v1/command/test -d '{ "language": "sql", "command": "backup database", "awaitResponse": false }' -H "Content-Type: application/json" --user root:arcadedb
```

**Comment by gramian** [comment]
In a more complicated setting the following error is caused:
```
java.lang.NullPointerException: Cannot invoke "com.arcadedb.ContextConfiguration.getValueAsString(com.arcadedb.GlobalConfiguration)" because the return value of "com.arcadedb.query.sql.executor.CommandContext.getConfiguration()" is null
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:62)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:55)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.doExecute(ScriptExecutionPlan.java:97)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.fetchNext(ScriptExecutionPlan.java:61)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:44)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:40)
	at com.arcadedb.query.sql.SQLScriptQueryEngine.executeInternal(SQLScriptQueryEngine.java:218)
	at com.arcadedb.query.sql.SQLScriptQueryEngine.command(SQLScriptQueryEngine.java:119)
	at com.arcadedb.database.LocalDatabase.command(LocalDatabase.java:1327)
	at com.arcadedb.database.async.DatabaseAsyncCommand.execute(DatabaseAsyncCommand.java:59)
```

**Comment by lvca** [comment]
I see in the async mode the server context is not passed. Fixing it.

**Comment by lvca** [comment]
Just pushed a fix. Please let me know if works.

**Comment by gramian** [comment]
Hi,
unfortunately that did not fix it. Here are the new errors:

## SQL

```
SEVER [BackupDatabaseStatement] Found pending transaction. Rolling it back before the backup...
SEVER [PostCommandHandler$1] Async command in database "test" failed.
com.arcadedb.exception.CommandExecutionException: Error on backing up database
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:79)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:52)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:65)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:116)
	at com.arcadedb.database.LocalDatabase.command(LocalDatabase.java:1335)
	at com.arcadedb.database.async.DatabaseAsyncCommand.execute(DatabaseAsyncCommand.java:69)
	at com.arcadedb.database.async.DatabaseAsyncExecutorImpl$AsyncThread.run(DatabaseAsyncExecutorImpl.java:136)
Caused by: com.arcadedb.integration.backup.BackupException: Error during backup of database 'test' to file 'test-backup-20240409-200107863.zip'
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:67)
	... 7 more
Caused by: com.arcadedb.integration.backup.BackupException: The backup file '/backups/test/test-backup-20240409-200107863.zip' cannot be created
	at com.arcadedb.integration.backup.format.FullBackupFormat.backupDatabase(FullBackupFormat.java:60)
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:66)
	... 12 more
```

## SQLscript

```
SEVER [BackupDatabaseStatement] Found pending transaction. Rolling it back before the backup...
SEVER [PostCommandHandler$1] Async command in database "test" failed.
com.arcadedb.exception.CommandExecutionException: Error on backing up database
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:79)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:55)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.doExecute(ScriptExecutionPlan.java:97)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.fetchNext(ScriptExecutionPlan.java:61)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:44)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:40)
	at com.arcadedb.query.sql.SQLScriptQueryEngine.executeInternal(SQLScriptQueryEngine.java:218)
	at com.arcadedb.query.sql.SQLScriptQueryEngine.command(SQLScriptQueryEngine.java:119)
	at com.arcadedb.database.LocalDatabase.command(LocalDatabase.java:1335)
	at com.arcadedb.database.async.DatabaseAsyncCommand.execute(DatabaseAsyncCommand.java:69)
	at com.arcadedb.database.async.DatabaseAsyncExecutorImpl$AsyncThread.run(DatabaseAsyncExecutorImpl.java:136)
Caused by: com.arcadedb.integration.backup.BackupException: Error during backup of database 'test' to file 'test-backup-20240409-200146374.zip'
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:67)
	... 11 more
Caused by: com.arcadedb.integration.backup.BackupException: The backup file '/backups/test/test-backup-20240409-200146374.zip' cannot be created
	at com.arcadedb.integration.backup.format.FullBackupFormat.backupDatabase(FullBackupFormat.java:60)
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:66)
	... 16 more
```

I also don't know where the "pending transaction" comes from. I tested on a fresh database and the first command send to it, is `BACKUP DATABASE`.

**Comment by gramian** [comment]
It seems to be fixed. Great!
