### ISSUE TITLE
Error on fetching multi page record

### ISSUE THREAD

**Issue by ismaeladra** [ArcadeData/arcadedb#1613]
ArcadeDB Version:
24.4.1

OS and JDK Version:
Windows, JDK-11

Issue Description:
I encountered an error while trying to retrieve a specific vertex. Additionally, executing any query that includes this vertex in the result also triggers the same error. I have tried using both Gremlin and Cypher, but the error persists. Below is the exception stack trace:
`com.arcadedb.exception.DatabaseOperationException: Error on fetching multi page record #179:1
	at com.arcadedb.engine.LocalBucket.loadMultiPageRecord(LocalBucket.java:947)
	at com.arcadedb.engine.LocalBucket.getRecordInternal(LocalBucket.java:553)
	at com.arcadedb.engine.LocalBucket.getRecord(LocalBucket.java:131)
	at com.arcadedb.database.ImmutableDocument.checkForLazyLoading(ImmutableDocument.java:179)
	at com.arcadedb.graph.ImmutableVertex.checkForLazyLoading(ImmutableVertex.java:209)
	at com.arcadedb.database.ImmutableDocument.get(ImmutableDocument.java:57)
	at com.arcadedb.gremlin.ArcadeVertex.properties(ArcadeVertex.java:169)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer.test(HasContainer.java:62)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer.internalTestAll(HasContainer.java:182)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer.testAll(HasContainer.java:172)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasStep.filter(HasStep.java:67)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:41)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:55)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.ScalarMapStep.processNextStart(ScalarMapStep.java:39)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:55)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DedupGlobalStep.processNextStart(DedupGlobalStep.java:115)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:47)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.OrderGlobalStep.processAllStarts(OrderGlobalStep.java:83)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.CollectingBarrierStep.processNextStart(CollectingBarrierStep.java:109)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:47)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:110)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:55)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.processNextStart(SelectStep.java:68)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)`
	
	Please provide guidance on how to resolve this issue. Thank you!

**Comment by gramian** [comment]
Can you please provide a minimal example of code to reproduce this?
