### ISSUE TITLE
Upgrading container 23.7.1 -> 24.6.1 resulted "permissions denied" on databases

### ISSUE THREAD

**Issue by artturimatias** [ArcadeData/arcadedb#1679]
### ArcadeDB Version:
24.6.1

### OS and JDK Version:

RHEL 8, rootless podman

### Expected behavior

Upgrading container should continue working with volumes used by previous versions

### Actual behavior

Arcadedb does not start:
`Caused by: com.arcadedb.exception.DatabaseMetadataException: Error on loading dictionary (error=java.io.FileNotFoundException: ./databases/seurankamat/dictionary.0.327680.v0.dict (Permission denied))
`

The problem seems to be that new container is running with differen user id

volume permission with 23.7.1:
`drwxr-xr-x.  4 102000999 102000999   48 May 22 14:53 _data
`
volume permission with 24.6.1:
`drwxr-xr-x.  2 102001000 102001000    6 Jul 24 08:18 _data`

### Steps to reproduce

`podman volume create arcade_test`

`podman run --rm -p 2480:2480 -p 2424:2424 -v arcade_test:/home/arcadedb/databases  -e JAVA_OPTS="-Darcadedb.server.rootPassword=node_master" arcadedata/arcadedb:23.7.1`

Create new database:

 `curl -X POST http://localhost:2480/api/v1/server \
       -d '{ "command": "create database school" }' \
       -H "Content-Type: application/json" \
       --user root:node_master`
       
Shut down the old container and start 24.6.1 with same volume
       
 `podman run --rm -p 2480:2480 -p 2424:2424 -v arcade_test:/home/arcadedb/databases  -e JAVA_OPTS="-Darcadedb.server.rootPassword=node_master" arcadedata/arcadedb:24.6.1`

You'll get permission denied errors:

`2024-08-01 11:33:15.875 WARNI [FileManager] <ArcadeDB_0> Cannot load file './databases/school/dictionary.0.327680.v0.dict'<ArcadeDB_0> Error on WAL file management for file './databases/school/txlog_0.wal'
java.io.FileNotFoundException: ./databases/school/txlog_0.wal (Permission denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
	at com.arcadedb.engine.WALFile.<init>(WALFile.java:91)
	at com.arcadedb.engine.WALFileFactoryEmbedded.newInstance(WALFileFactoryEmbedded.java:25)
	at com.arcadedb.engine.TransactionManager.createWALFilePool(TransactionManager.java:499)
	at com.arcadedb.engine.TransactionManager.<init>(TransactionManager.java:58)
	at com.arcadedb.database.LocalDatabase.openInternal(LocalDatabase.java:1773)
	at com.arcadedb.database.LocalDatabase.open(LocalDatabase.java:195)
	at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:78)
	at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:464)
	at com.arcadedb.server.ArcadeDBServer.getDatabase(ArcadeDBServer.java:318)
	at com.arcadedb.server.ArcadeDBServer.loadDatabases(ArcadeDBServer.java:489)
	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:145)
	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:106)
<ArcadeDB_0> Error on WAL file management for file './databases/school/txlog_1.wal'
java.io.FileNotFoundException: ./databases/school/txlog_1.wal (Permission denied)`

**Comment by lvca** [comment]
Do you mean the UID for the volume/directory/file or the container?

**Comment by artturimatias** [comment]
I mean UID of volume/directory/file.

**Comment by lvca** [comment]
What kind of operations do you do to change the UID(s)? I'd like to add them in the documentation.

**Comment by artturimatias** [comment]
Just normal chown for volume. One can find volume location like this:
` docker/podman volume inspect VOLUME_NAME`

For rootless podman volume is in users home directory:
`sudo chown -R 102001000:102001000 /home/user/.local/share/containers/storage/volumes/VOLUME_NAME/_data
`
In my case UID of files generated by 24.6.1 was 102001000. I'm not sure how that UID is generated.

**Comment by gramian** [comment]
This behavior is unfortunate but I think this cannot be fixed without introducing other inconveniences.
It might be rooted in this change  https://github.com/ArcadeData/arcadedb/commit/7b42b4ca57a92949107899f91573f19885ef5ee0#diff-ee5bdd6fd6551ebaddc404ecef351b661fd0c9b8547819d718feb8b6b5729ae6 (by me) which switches to a non-root user. I think adding this to the "Update" section would be a good solution.

**Comment by lvca** [comment]
@gramian so this issue is only for containers running a version before yo made the change, right?

**Comment by gramian** [comment]
I would guess so, though I haven't checked if the change lines up with the version reported, but it was the first thing that came to mind.

**Comment by lvca** [comment]
It would make sense, from root to arcadedb user the volume can't be accessed.

**Comment by lvca** [comment]
Closing this issue, assuming the problem was with using "root" with old containers
