### ISSUE TITLE
database import of graphson clobbers vertex IDs

### ISSUE THREAD

**Issue by justin2004** [ArcadeData/arcadedb#1714]
given this graphson file:

output.graphson
```json
{"id": "http://www.w3.org/2000/01/rdf-schema#Datatype", "label": "http://www.w3.org/2000/01/rdf-schema#Class", "outE": {"subClassOf": [{"id": "0", "inV": "http://www.w3.org/2000/01/rdf-schema#Class"}], "isDefinedBy": [{"id": "3", "inV": "http://www.w3.org/2000/01/rdf-schema#"}], "type": [{"id": "4", "inV": "http://www.w3.org/2000/01/rdf-schema#Class"}]}, "properties": {"comment": [{"value": "\"The class of RDF datatypes.\""}], "label": [{"value": "\"Datatype\""}]}}
{"id": "http://www.w3.org/2000/01/rdf-schema#", "label": "owl:Thing"}
{"id": "http://www.w3.org/2000/01/rdf-schema#Class", "label": "owl:Thing"}
```

> create database test

Database 'test' created
{test}> import database file:///mnt/output.graphson

then if i run the gremlin query `g.V()` i get:
```csv
"@rid","@type","comment","label","@in","@out"
"#1:0","http://www.w3.org/2000/01/rdf-...","""The class of RDF datatypes.""","""Datatype""","0","0"
"#25:0","owl:Thing","<null>","<null>","0","0"
"#28:0","owl:Thing","<null>","<null>","0","0"
```

notice how the `@rid` column does not have the `id` that was used in the graphson file.
i expect the `id` in the graphson file to be preserved. 

the [gremlin console](https://tinkerpop.apache.org/docs/current/tutorials/the-gremlin-console/) preserves that `id`:
```gremlin
gremlin> graph = TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> reader = GraphSONReader.build().create()
==>org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader@105dc04d
gremlin> is = new FileInputStream('/home/gremlin/data/output.graphson')
==>java.io.FileInputStream@618f627b
gremlin> reader.readGraph(is, graph)
==>null
gremlin> g = traversal().withEmbedded(graph)
==>graphtraversalsource[tinkergraph[vertices:3 edges:0], standard]
gremlin> g.V()
==>v[http://www.w3.org/2000/01/rdf-schema#Datatype]
==>v[http://www.w3.org/2000/01/rdf-schema#Class]
==>v[http://www.w3.org/2000/01/rdf-schema#]
gremlin> g.V('http://www.w3.org/2000/01/rdf-schema#Datatype')
==>v[http://www.w3.org/2000/01/rdf-schema#Datatype]
```

noticed how the gremlin console preserves the `id` in the graphson file.

it seems arcade does not like `id`s that the gremlin console accepts:

```gremlin
Set language to gremlin
{test}> g.V('http://www.w3.org/2000/01/rdf-schema#Datatype')

ERROR:
java.lang.IllegalArgumentException: The RID 'http://www.w3.org/2000/01/rdf-schema#Datatype' is not valid
        at com.arcadedb.database.RID.<init>(RID.java:71)
        at com.arcadedb.gremlin.ArcadeGraph.vertices(ArcadeGraph.java:311)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.lambda$new$0(GraphStep.java:70)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:158)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:155)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
        at com.arcadedb.gremlin.ArcadeGremlin$2.hasNext(ArcadeGremlin.java:112)
        at com.arcadedb.query.sql.executor.IteratorResultSet.hasNext(IteratorResultSet.java:37)
        at com.arcadedb.console.Console.executeSQL(Console.java:625)
        at com.arcadedb.console.Console.execute(Console.java:273)
        at com.arcadedb.console.Console.parse(Console.java:742)
        at com.arcadedb.console.Console.interactiveMode(Console.java:131)
        at com.arcadedb.console.Console.execute(Console.java:185)
        at com.arcadedb.console.Console.main(Console.java:148)
```

running:
ArcadeDB Server v24.8.1-SNAPSHOT
in the docker image

**Comment by lvca** [comment]
When importing GraphSON files with non-RID vertex IDs (like URIs such as http://www.w3.org/2000/01/rdf-schema#Datatype), the original IDs were being completely
  lost because:
  1. ArcadeDB's RID constructor threw IllegalArgumentException for non-RID strings
  2. The import process ignored the original ID and assigned new ArcadeDB RIDs
  3. Edges couldn't be correctly linked because they referenced original IDs that were no longer available
