### ISSUE TITLE
Request for Additon of flag --add-opens java.base/java.nio.channels.spi=ALL-UNNAMED to sever.sh and console.sh

### ISSUE THREAD

**Issue by ironluca** [ArcadeData/arcadedb#1822]
### ArcadeDB Version:

`24.10.1`

### OS and JDK Version:

`Ubuntu 22.04`

The below stack was notices while running console.sh and also on the server during closing of databases. Adding the above flag in console.sh solves it, perhaps it will also solve in server. If this could be added in the next release, it will be helpful.

```
if [ -z "$JAVA_OPTS_SCRIPT" ] ; then
    JAVA_OPTS_SCRIPT="-XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.nio.channels.spi=ALL-UNNAMED -Dpolyglot.engine.WarnInterpreterOnly=false -Djava.awt.headless=true -Dfile.encoding=UTF8 --illegal-access=deny"
fi
```

```
> CREATE DATABASE IF NOT EXISTS schema_test_db;
Couldn't disable close on interrupt
java.lang.reflect.InaccessibleObjectException: Unable to make field private sun.nio.ch.Interruptible java.nio.channels.spi.AbstractInterruptibleChannel.interruptor accessible: module java.base does not "opens java.nio.channels.spi" to unnamed module @6af93788
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.arcadedb.engine.PaginatedComponentFile.doNotCloseOnInterrupt(PaginatedComponentFile.java:216)
	at com.arcadedb.engine.PaginatedComponentFile.open(PaginatedComponentFile.java:208)
	at com.arcadedb.engine.ComponentFile.<init>(ComponentFile.java:50)
	at com.arcadedb.engine.PaginatedComponentFile.<init>(PaginatedComponentFile.java:49)
	at com.arcadedb.engine.FileManager.getOrCreateFile(FileManager.java:188)
	at com.arcadedb.engine.PaginatedComponent.<init>(PaginatedComponent.java:57)
	at com.arcadedb.engine.PaginatedComponent.<init>(PaginatedComponent.java:47)
	at com.arcadedb.engine.PaginatedComponent.<init>(PaginatedComponent.java:42)
	at com.arcadedb.engine.Dictionary.<init>(Dictionary.java:61)
	at com.arcadedb.schema.LocalSchema.create(LocalSchema.java:138)
	at com.arcadedb.database.LocalDatabase.openInternal(LocalDatabase.java:1782)
	at com.arcadedb.database.LocalDatabase.create(LocalDatabase.java:207)
	at com.arcadedb.database.DatabaseFactory.create(DatabaseFactory.java:90)
	at com.arcadedb.console.Console.executeCreateDatabase(Console.java:444)
	at com.arcadedb.console.Console.execute(Console.java:257)
	at com.arcadedb.console.Console.parse(Console.java:742)
	at com.arcadedb.console.Console.interactiveMode(Console.java:131)
	at com.arcadedb.console.Console.execute(Console.java:185)
	at com.arcadedb.console.Console.main(Console.java:148)

Database 'IF NOT EXISTS schema_test_db' created
{IF NOT EXISTS schema_test_db}> 
```

**Comment by gramian** [comment]
This should have been resolved by https://github.com/ArcadeData/arcadedb/issues/1753 and not present in 24.11.1. Please reopen if this is still an issue.
