### ISSUE TITLE
your 5 min installation is not working

### ISSUE THREAD

**Issue by abcnow** [ArcadeData/arcadedb#236]
## Expected behavior
I copied and pasted your 5 min installation code and it is broken.. so I had to adjust it.. and then copied and pasted in my docker terminal and it doesn't finish.. It stays hanging there

----
docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdbOpenBeer.gz}" arcadedata/arcadedb:latest
Password:

 █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
PLAY WITH DATA                                    arcadedb.com
[0.976s][error][gc] Failed to allocate backing file (Cannot allocate memory)
[1.624s][error][gc,init] Not enough space available on the backing filesystem to hold the current max
[1.625s][error][gc,init] Java heap size (2048M). Forcefully lowering max Java heap size to 2046M (100%).

2021-12-12 12:04:04.426 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v21.12.1-SNAPSHOT (build 94c9efa44b0430f8a79bf2e8b572c2fc81a7d50a/1638857567344/main) is starting up...
2021-12-12 12:04:04.427 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [] ...
2021-12-12 12:04:04.502 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2021-12-12 12:04:04.605 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
2021-12-12 12:04:04.941 INFO  [ArcadeDBServer] <ArcadeDB_0> Creating default database 'Imported'...
2021-12-12 12:04:05.486 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdbOpenBeer.gz...- Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 0 vertices (0/sec) - 0 edges (0/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
Exception in thread "main" com.arcadedb.exception.CommandExecutionException: Error on importing database
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:58)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:115)
	at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:53)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:86)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:70)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:90)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1205)
	at com.arcadedb.server.ArcadeDBServer.loadDefaultDatabases(ArcadeDBServer.java:475)
	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:123)
	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:84)
Caused by: com.arcadedb.integration.importer.ImportException: Error on parsing source 'null'
	at com.arcadedb.integration.importer.Importer.load(Importer.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:53)
	... 9 more
Caused by: java.io.FileNotFoundException: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdbOpenBeer.gz
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.arcadedb.integration.importer.SourceDiscovery.getSourceFromURL(SourceDiscovery.java:98)
	at com.arcadedb.integration.importer.SourceDiscovery.getSource(SourceDiscovery.java:81)
	at com.arcadedb.integration.importer.SourceDiscovery.getSchema(SourceDiscovery.java:53)
	at com.arcadedb.integration.importer.Importer.loadFromSource(Importer.java:75)
	at com.arcadedb.integration.importer.Importer.load(Importer.java:50)
	... 14 more

## Actual behavior
after 10 minutes it is still waiting...

## Steps to reproduce
1. copied your 5 min installation link
2. pasted on my terminal (link it is broken)
3. adjusted your link
4. copied the new link and pasted in my terminal
5. installation doesn't finish/stays hanging

**Comment by abcnow** [comment]
I was able to install "arcadedb" with docker (finally) but it is not opening on my localhost:2480... I am not sure what the problem could be...when I open my docker dashboard it shows that the application is running on port 2480 but when I try to access it via the browser nothing really comes up...blank

**Comment by robfrank** [comment]
The link to the OpenBeer is wrong, you missed a **/** before _Open_

https://github.com/ArcadeData/arcadedb-datasets/blob/main/orientdb/OpenBeer.gz

About docker, past the command you expected, please

**Comment by lvca** [comment]
@abcnow also, if you were able to start Docker successfully (please the comment above by @robfrank about the wrong URL), could you please post here your logs so we can have a clue why Studio is now showing up?

**Comment by abcnow** [comment]
thanks guys.. my logs are here:
----

 █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
PLAY WITH DATA                                    arcadedb.com
[0.918s][error][gc] Failed to allocate backing file (Cannot allocate memory)
[1.645s][error][gc,init] Not enough space available on the backing filesystem to hold the current max
[1.646s][error][gc,init] Java heap size (2048M). Forcefully lowering max Java heap size to 2046M (100%).

2021-12-13 21:46:41.564 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v21.12.1-SNAPSHOT (build 4df4265986af4f02be8c06a9461b417d79b412dc/1639375795545/main) is starting up...
2021-12-13 21:46:41.580 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [] ...
2021-12-13 21:46:41.611 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...

+--------------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION                    |
+--------------------------------------------------------------------+
| This is the first time the server is running. Please type a        |
| password of your choice for the 'root' user or leave it blank      |
| to auto-generate it.                                               |
|                                                                    |
| To avoid this message set the environment variable or JVM          |
| setting `arcadedb.server.rootPassword` to the root password to use.|
+--------------------------------------------------------------------+

Root password [BLANK=auto generate it]: *

**Comment by lvca** [comment]
Did you enter the root password to get it started? it asks for the root password only the first time it's installed.

**Comment by abcnow** [comment]
It doesn't allow me to enter the root password.. it exits before I am able to write anything

**Comment by lvca** [comment]
@abcnow I think you missed the `--env arcadedb.server.rootPassword=playwithdata` running docker. With this setting the password is read from environment settings.

**Comment by abcnow** [comment]
this is the command i entered on my terminal (mac):
docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest
--
when the installation finishes I entered "docker ps" and no container is running...I ran the arcadecontainer from the docker dashboard and this is what I am getting.. from the console log:
----
2021-12-14 14:02:38.213 INFO [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v21.12.1-SNAPSHOT (build 461315a1bc9e54d9e126588928b785e2196ff9ca/1639439906541/main) is starting up...


2021-12-14 14:02:41.003 INFO [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [] ...


2021-12-14 14:02:41.475 INFO [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...


+--------------------------------------------------------------------+

| WARNING: FIRST RUN CONFIGURATION |

+--------------------------------------------------------------------+

| This is the first time the server is running. Please type a |

| password of your choice for the 'root' user or leave it blank |

| to auto-generate it. |

| |

| To avoid this message set the environment variable or JVM |

| setting `arcadedb.server.rootPassword` to the root password to use.|

+--------------------------------------------------------------------+




Root password [BLANK=auto generate it]: *

*

*

*

*

*

*

*

*

**Comment by lvca** [comment]
Just tested on my PC and works:

```
 docker run --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest

 █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
PLAY WITH DATA                                    arcadedb.com

2021-12-14 14:56:16.629 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v21.12.1-SNAPSHOT (build 12ae02f54507e40fdc05dd3aa99df8c340135b5a/1639491855448/main) is starting up...
2021-12-14 14:56:16.632 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [] ...
2021-12-14 14:56:16.691 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2021-12-14 14:56:16.832 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
2021-12-14 14:56:17.279 INFO  [ArcadeDBServer] <ArcadeDB_0> Creating default database 'Imported'...
2021-12-14 14:56:17.834 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz...
2021-12-14 14:56:19.952 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format OrientDB (parsingLimitBytes=9.54MB parsingLimitEntries=0)
2021-12-14 14:56:19.952 INFO  [Importer] <ArcadeDB_0> Checking schema...Importing OrientDB database from stream to '../databases/Imported'
Creation of the schema: types, properties and indexes
- Created type 'V' with the following properties {}
- Created type 'Beer' with the following properties {id=INTEGER}
- Created type 'Brewery' with the following properties {id=INTEGER}
- Created type 'Category' with the following properties {id=INTEGER}
- Created type 'E' with the following properties {}
- Created type 'HasBrewery' with the following properties {}
- Created type 'HasCategory' with the following properties {}
- Created type 'HasStyle' with the following properties {}
- Created type 'Style' with the following properties {id=INTEGER}
- Created index UNIQUE on Beer[id]
- Created index UNIQUE on Brewery[id]
- Created index UNIQUE on Style[id]
- Created index UNIQUE on Category[id]
Creation of records started: creating vertices and documents records (edges on the next phase)
- Status update: parsed 1,230 (246/sec) - 0 documents (0/sec) - 1,223 vertices (244/sec) - 0 edges (0/sec) - 4,574 skipped edges - 0 linked edges (0/sec - 0%)
- Creation of records completed: created 7,467 vertices and 0 documents, skipped 14,908 edges (1,866 records/sec elapsed=4 secs)
Creation of edges started: creating edges between vertices
- Status update: parsed 0 (-308/sec) - 0 documents (0/sec) - 7,467 vertices (1,560/sec) - 9,391 edges (2,347/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
- Creation of edges completed: created 14,908 edges {HasStyle=4433, HasBrewery=5901, HasCategory=4574} (2,129 edges/sec elapsed=7 secs)
Dropping empty 'V' base vertex type (in OrientDB all the vertices have their own class
Dropping empty 'E' base edge type (in OrientDB all the edges have their own class
***************************************************************************************************
Import of OrientDB database completed in 8 secs with 0 errors and 0 warnings.

SUMMARY

- Records..................................: 7,484
-- Beer                                    : 5,901
-- Brewery                                 : 1,414
-- Category                                : 11
-- E                                       : 0
-- HasBrewery                              : 5,901
-- HasCategory                             : 4,574
-- HasStyle                                : 4,433
-- OFunction                               : 0  (excluded)
-- OIdentity                               : 0  (excluded)
-- ORestricted                             : 0  (excluded)
-- ORole                                   : 3  (excluded)
-- OSchedule                               : 0  (excluded)
-- OSecurityPolicy                         : 4  (excluded)
-- OSequence                               : 0  (excluded)
-- OTriggered                              : 0  (excluded)
-- OUser                                   : 3  (excluded)
-- Style                                   : 141
-- V                                       : 0
-- _studio                                 : 7  (excluded)
- Total attributes.........................: 513,424
***************************************************************************************************

NOTES:
- users stored in OUser class will not be imported because ArcadeDB has users only at server level. If you want to import such users into ArcadeDB server configuration, please run the importer with the option -s <securityFileDirectory>
- you can find your new ArcadeDB database in '../databases/Imported'
- Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 7,467 vertices (0/sec) - 14,908 edges (5,502/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)

2021-12-14 14:56:29.028 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489)...
2021-12-14 14:56:29.154 INFO  [undertow] starting server: Undertow - 2.2.14.Final
2021-12-14 14:56:29.182 INFO  [xnio] XNIO version 3.8.4.Final
2021-12-14 14:56:29.219 INFO  [nio] XNIO NIO Implementation Version 3.8.4.Final
2021-12-14 14:56:29.303 INFO  [threads] JBoss Threads version 3.1.0.Final
2021-12-14 14:56:29.417 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480)
2021-12-14 14:56:29.420 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [mongo, gremlin, cypher, sql]
2021-12-14 14:56:29.421 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started (CPUs=4 MAXRAM=2.00GB)
2021-12-14 14:56:29.422 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://localhost:2480
```

**Comment by lvca** [comment]
Please try to run it with `-d` option, so in this way you can check if the container is running with `docker ps` and see the logs with `docker logs <container>`

```
run -d --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest
```

**Comment by abcnow** [comment]
thanks for the suggestions.. here you have the results:
---
docker run -d --rm -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" arcadedata/arcadedb:latest
Unable to find image 'arcadedata/arcadedb:latest' locally
latest: Pulling from arcadedata/arcadedb
97518928ae5f: Pull complete 
31849add3d40: Pull complete 
a71d755b1f52: Pull complete 
4fd8d3975d15: Pull complete 
f9ccd9249c1b: Pull complete 
2b76c88285b5: Pull complete 
ff06b61ebe17: Pull complete 
Digest: sha256:d5ca643e8e1076529b2159744b26dd512005a1099d55a189dc429a6cfd90e4e0
Status: Downloaded newer image for arcadedata/arcadedb:latest
c11985d490a2f567118f0d385e85da20e648c5ba6423f95045abecfc521dc51d

ac at ACs-MacBook-Pro in ~
$ docker ps
CONTAINER ID   IMAGE                        COMMAND       CREATED          STATUS          PORTS                                                                                                                                          NAMES
c11985d490a2   arcadedata/arcadedb:latest   "server.sh"   54 seconds ago   Up 51 seconds   0.0.0.0:2424->2424/tcp, :::2424->2424/tcp, 5432/tcp, 6379/tcp, 8182/tcp, 9998-9999/tcp, 0.0.0.0:2480->2480/tcp, :::2480->2480/tcp, 27017/tcp   awesome_torvalds

--
but after a few seconds that container stopped automatically to the point that when I used docker logs <container> there were not logs

**Comment by abcnow** [comment]
do we have another way to install arcadedb that is not with docker?

**Comment by abcnow** [comment]
PS: I was able to install "orientdb" with docker...

**Comment by lvca** [comment]
@abcnow with docker the distribution is the same for everybody, so the Java version and settings.

If you want to run ArcadeDB without Docker, download the latest binaries from GitHub (https://github.com/ArcadeData/arcadedb/releases) or clone the repository and generate your own distribution with `mvn clean install -DskipTests`. The requirement is JDK v11 up to v15.

Once you have a distribution, either way, you can run `bin/server.sh` or `bin/server.bat` on Windows.

**Comment by lvca** [comment]
@abcnow closing the issue because of 2 weeks without a response. In case you still have issues, please comment here.
