### ISSUE TITLE
Cannot create new database, Invalid characters used in database name

### ISSUE THREAD

**Issue by adriancoca** [ArcadeData/arcadedb#243]
### OS: WINDOWS 11 

Instalation from https://github.com/ArcadeData/arcadedb/releases on premise

## Steps to reproduce
When i try to create a new database from studio i have  in console  the message -> 
 Invalid characters used in database name.

---------------------------------------------------------------------------------

com.arcadedb.exception.DatabaseOperationException: Error on creating new database instance
        at com.arcadedb.database.EmbeddedDatabase.<init>(EmbeddedDatabase.java:166)
        at com.arcadedb.database.DatabaseFactory.create(DatabaseFactory.java:83)
        at com.arcadedb.server.ArcadeDBServer.createDatabase(ArcadeDBServer.java:292)
        at com.arcadedb.server.http.handler.PostCreateDatabaseHandler.execute(PostCreateDatabaseHandler.java:46)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:82)
        at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:112)
        at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178)
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
Caused by: java.lang.IllegalArgumentException: Invalid characters used in database name
        at com.arcadedb.database.EmbeddedDatabase.checkDatabaseName(EmbeddedDatabase.java:1499)
        at com.arcadedb.database.EmbeddedDatabase.<init>(EmbeddedDatabase.java:157)
        ... 20 more

**Comment by JusticeN** [comment]
which database name did you give ?

**Comment by adriancoca** [comment]
Tested with:  test , TEST , adrian  ,data   etc.. Nothing with some special characters.

**Comment by lvca** [comment]
What's the full directory path where you have installed ArcadeDB?

**Comment by lvca** [comment]
Checked the code and the only invalid characters are `*` and `..`

**Comment by adriancoca** [comment]
I also tried running as admin thinking is a path access issue but not
C:\zitro\arcadedb-21.11.1-SNAPSHOT\bin

Also I reinstalled as C:\zitro\arcadedb\bin but same issue.

**Comment by lvca** [comment]
@adriancoca I've pushed a small fix that prints the database name in the exception. If you could use the latest 21.12.1-SNAPSHOT you should see the "invalid" database name in the exception itself.

**Comment by adriancoca** [comment]
Where i can find the new build 21.12.1-SNAPSHOT ?
The build is done but https://github.com/ArcadeData/arcadedb/releases/download/21.12.1/arcadedb-21.12.1.zip seems invalid

**Comment by lvca** [comment]
Snapshots are constantly published only to Maven Central. You can find the latest here:

https://s01.oss.sonatype.org/content/repositories/snapshots/com/arcadedb/arcadedb-package/

Or you can clone the git repository, build it with `mvn clean install -DskipTests` and then get the distribution in `package/target/`

**Comment by JusticeN** [comment]
i can reproduce the issue on Windows.

the only name check in `*` and `..`  and it is the reason why it doesn't work.

@adriancoca after building try to start outsite of the bin directory.

i don't know why but windows add `..` in front of the path when you run it from `\arcadedb\package\target\arcadedb-21.12.1-SNAPSHOT.dir\arcadedb-21.12.1-SNAPSHOT\bin` the path/name will look like `../databases/devdb` and this will fail because `..` ist not allowed

**Comment by adriancoca** [comment]
@JusticeN  @lvca  it seems that when starting from bin it forms a path like ../databases/dbname.  I started using full path and its ok.
 C:\zitro\arcadedb\bin\server.bat
Thanks for the help.

**Comment by lvca** [comment]
Got it. Try running from the home directory `C:\zitro\arcadedb` and run the server with `bin\server.bat`.
