### ISSUE TITLE
java embedded create() works but subsequent open() fails with NoSuchMethodError

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#262]
## Expected behavior
open a created database

## Actual behavior
fails with:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.json.JSONObject.keySet()Ljava/util/Set;
	at com.arcadedb.ContextConfiguration.fromJSON(ContextConfiguration.java:68)
	at com.arcadedb.database.EmbeddedDatabase.open(EmbeddedDatabase.java:172)
	at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:65)
	at com.arcadedb.database.DatabaseFactory.open(DatabaseFactory.java:59)
	at com.kombi.test.ArcadeTest.initDB(ArcadeTest.java:27)

```
## Steps to reproduce
create a database with:

```
       DatabaseFactory databaseFactory = new DatabaseFactory(testDB.getPath());
        try( Database db = databaseFactory.created(); ) {
            // YOUR CODE
            System.out.println("DB successfully created!");
        } catch (Exception e) {
            e.printStackTrace();
        }

```

then try to reopen with:

```
       DatabaseFactory databaseFactory = new DatabaseFactory(testDB.getPath());
        try( Database db = databaseFactory.open(); ) {
            // YOUR CODE
            System.out.println("DB successfully opened!");
        } catch (Exception e) {
            e.printStackTrace();
        }

```

**Comment by grimace** [comment]
my bad! had an old json.jar file in my ~/.m2 repository

**Comment by lvca** [comment]
NP.
