### ISSUE TITLE
should it be possible to open DB in embedded java after editing with studio?

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#263]
## Expected behavior
want to edit schema with studio then use java embedded to populate data

## Actual behavior
PaginatedFile throws and exception trying to parse 'v0' as an Integer:
```

Caused by: java.lang.NumberFormatException: For input string: "v0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.arcadedb.engine.PaginatedFile.open(PaginatedFile.java:220)
	at com.arcadedb.engine.PaginatedFile.<init>(PaginatedFile.java:51)
	at com.arcadedb.engine.FileManager.<init>(FileManager.java:66)
	at com.arcadedb.database.EmbeddedDatabase.openInternal(EmbeddedDatabase.java:205)


```
## Steps to reproduce
try to open a DB in embedded mode after using it in server/studio

**Comment by lvca** [comment]
Are you using both at the same time? Also, the line numbers don't match with the latest 21.12.1 release. Are you running with Docker or as a standalone server?

**Comment by lvca** [comment]
Or was this issue related to the previous one that was invalid because of the mixin of jars?

**Comment by lvca** [comment]
Closing this issue because of no response. If this issue is still valid, please comment here. Thanks.
