### ISSUE TITLE
No enum constant com.arcadedb.schema.Type.LINKLIST on DB import

### ISSUE THREAD

**Issue by grimace** [ArcadeData/arcadedb#34]
## Expected behavior
database should be able to import ( OrientDB 3.2.0 )

## Actual behavior
an exception is thrown on Type.LINKLIST

## Steps to reproduce
import a DATABASE with some RIDs in a LINKLIST

stack trace of exception:

```
java.lang.IllegalArgumentException: No enum constant com.arcadedb.schema.Type.LINKLIST
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.arcadedb.schema.Type.valueOf(Type.java:43)
	at com.arcadedb.importer.OrientDBImporter.createType(OrientDBImporter.java:822)
	at com.arcadedb.importer.OrientDBImporter.createType(OrientDBImporter.java:780)
	at com.arcadedb.importer.OrientDBImporter.parseSchema(OrientDBImporter.java:720)
	at com.arcadedb.importer.OrientDBImporter.parseInputFile(OrientDBImporter.java:272)
	at com.arcadedb.importer.OrientDBImporter.run(OrientDBImporter.java:184)
	at com.arcadedb.importer.format.OrientDBFormatImporter.load(OrientDBFormatImporter.java:44)
	at com.arcadedb.importer.Importer.loadFromSource(Importer.java:92)
	at com.arcadedb.importer.Importer.load(Importer.java:57)
	at com.arcadedb.server.http.handler.ImportDatabaseHandler.execute(ImportDatabaseHandler.java:59)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:110)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
```

**Comment by lvca** [comment]
Are you using links with document database, right? I can fix the importer quickly but I'm wondering if it's better to convert documents with links in graphs

**Comment by grimace** [comment]
fairly sure they are links to Vertexes

**Comment by lvca** [comment]
In OrientDB, each edge can connect only 2 vertices, so if you have used LINKLIST means you're linking documents or you are not using the graph model properly.

**Comment by lvca** [comment]
Just pushed a fix that treats LINKLIST as an embedded list of RIDS, so the behavior should be the same as with OrientDB.
