### ISSUE TITLE
build failing on ConstantsTest

### ISSUE THREAD

**Issue by ChipNowacek** [ArcadeData/arcadedb#360]
## Expected behavior
project would build

## Actual behavior

> [INFO] Running com.arcadedb.ConstantsTest
> [ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! - in com.arcadedb.ConstantsTest
> [ERROR] com.arcadedb.ConstantsTest.getBuildNumber  Time elapsed: 0.003 s  <<< FAILURE!
> org.opentest4j.AssertionFailedError: expected: not <null>
> 	at com.arcadedb.ConstantsTest.getBuildNumber(ConstantsTest.java:58)

## Steps to reproduce
run the build
[com.arcadedb.ConstantsTest.txt](https://github.com/ArcadeData/arcadedb/files/8406637/com.arcadedb.ConstantsTest.txt)

Should I just try another release?

**Comment by lvca** [comment]
How do you run the build?

Try: `mvn clean install -DskipTests` to have a fresh build.

**Comment by ChipNowacek** [comment]
It did build with `mvn clean install -DskipTests`. Thank you. Now from the console I get what's below. Any idea?

```
ArcadeDB Console v.22.2.1-SNAPSHOT - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)
> create database qustions
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: ../log/arcadedb.log.0.lck
java.nio.file.NoSuchFileException: ../log/arcadedb.log.0.lck
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:511)
	at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:278)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
	at java.base/java.lang.Class.newInstance(Class.java:604)
	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
	at com.arcadedb.log.DefaultLogger.installCustomFormatter(DefaultLogger.java:79)
	at com.arcadedb.log.DefaultLogger.<init>(DefaultLogger.java:41)
	at com.arcadedb.log.DefaultLogger.<clinit>(DefaultLogger.java:36)
	at com.arcadedb.log.LogManager.<init>(LogManager.java:31)
	at com.arcadedb.log.LogManager.<clinit>(LogManager.java:29)
	at com.arcadedb.engine.TransactionManager.<init>(TransactionManager.java:54)
	at com.arcadedb.database.EmbeddedDatabase.openInternal(EmbeddedDatabase.java:1643)
	at com.arcadedb.database.EmbeddedDatabase.create(EmbeddedDatabase.java:201)
	at com.arcadedb.database.DatabaseFactory.create(DatabaseFactory.java:90)
	at com.arcadedb.console.Console.executeCreateDatabase(Console.java:342)
	at com.arcadedb.console.Console.execute(Console.java:182)
	at com.arcadedb.console.Console.parse(Console.java:501)
	at com.arcadedb.console.Console.<init>(Console.java:113)
	at com.arcadedb.console.Console.main(Console.java:125)
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: ../log/arcadedb.log.0.lck
java.nio.file.NoSuchFileException: ../log/arcadedb.log.0.lck
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:511)
	at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:278)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
	at java.base/java.lang.Class.newInstance(Class.java:604)
	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
	at com.arcadedb.log.DefaultLogger.installCustomFormatter(DefaultLogger.java:79)
	at com.arcadedb.log.DefaultLogger.<init>(DefaultLogger.java:41)
	at com.arcadedb.log.LogManager.<init>(LogManager.java:31)
	at com.arcadedb.log.LogManager.<clinit>(LogManager.java:29)
	at com.arcadedb.engine.TransactionManager.<init>(TransactionManager.java:54)
	at com.arcadedb.database.EmbeddedDatabase.openInternal(EmbeddedDatabase.java:1643)
	at com.arcadedb.database.EmbeddedDatabase.create(EmbeddedDatabase.java:201)
	at com.arcadedb.database.DatabaseFactory.create(DatabaseFactory.java:90)
	at com.arcadedb.console.Console.executeCreateDatabase(Console.java:342)
	at com.arcadedb.console.Console.execute(Console.java:182)
	at com.arcadedb.console.Console.parse(Console.java:501)
	at com.arcadedb.console.Console.<init>(Console.java:113)
	at com.arcadedb.console.Console.main(Console.java:125)
```

**Comment by lvca** [comment]
What is your OS? Are you starting the console with `bin/console.sh` (or .bat) from the main directory? That error seems about the logging framework being unable to create a file under the `log` folder because the `log` folder doesn't exist.

**Comment by ChipNowacek** [comment]
macOS 12.3.1

```
 % bin/console.sh
ArcadeDB Console v.22.2.1-SNAPSHOT - Copyrights (c) 2021 Arcade Data Ltd (https://arcadedb.com)
> connect qustions
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: ../log/arcadedb.log.0.lck
java.nio.file.NoSuchFileException: ../log/arcadedb.log.0.lck
```

**Comment by ChipNowacek** [comment]
Is everyone working on linux?

**Comment by lvca** [comment]
I'm working with a Mac and the CI tests run on both Windows and Linux. I guess the log configuration file must be fixed. It should work if you run the `console.sh` from the bin directory then:

```shell
cd bin
./console.sh
```
