### ISSUE TITLE
RemoteDatabase: Vertex toMap fail

### ISSUE THREAD

**Issue by mdre** [ArcadeData/arcadedb#501]
### OS: Kubuntu 22.04

NullPointerException in Vertex.toMap()

## Steps to reproduce
```Java
db = new RemoteDatabase("localhost", 2480, "ogm-test", "root", "toortoor");    
        
ResultSet rs = db.query("sql", "select from SimpleVertex");
Vertex sv = rs.next().getVertex().get();
System.out.println("sv: "+sv.toJSON().toString(4));
System.out.println("sv: "+sv.toMap());
``` 
Output: 
``` 
sv: {
    "@out": 0,
    "s": "aaa",
    "@rid": "#33:0",
    "@in": 0,
    "@type": "SimpleVertex",
    "@cat": "v"
}
Exception in thread "main" java.lang.NullPointerException
	at com.arcadedb.database.ImmutableDocument.toMap(ImmutableDocument.java:88)
	at test.DirectConnect.testInicial(DirectConnect.java:69)
	at test.DirectConnect.<init>(DirectConnect.java:37)
	at test.DirectConnect.main(DirectConnect.java:448)
```

**Comment by lvca** [comment]
Fixed
