### ISSUE TITLE
Unknown method `values()`

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#573]
### OS: Ubuntu 20.04

The [`values()`](https://docs.arcadedb.com/#_values) method is seemingly not available.

## Expected behavior
`Cannot execute command Unknown method name: values`
<details><summary>Trace</summary>

```
<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Unknown method name: values
	at com.arcadedb.query.sql.method.DefaultSQLMethodFactory.createMethod(DefaultSQLMethodFactory.java:130)
	at com.arcadedb.query.sql.executor.SQLEngine.getMethod(SQLEngine.java:93)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:130)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:82)
	at com.arcadedb.query.sql.parser.Modifier.execute(Modifier.java:102)
	at com.arcadedb.query.sql.parser.BaseExpression.execute(BaseExpression.java:155)
	at com.arcadedb.query.sql.parser.Expression.execute(Expression.java:117)
	at com.arcadedb.query.sql.parser.ContainsCondition.evaluate(ContainsCondition.java:164)
	at com.arcadedb.query.sql.parser.NotBlock.evaluate(NotBlock.java:61)
	at com.arcadedb.query.sql.parser.AndBlock.evaluate(AndBlock.java:63)
	at com.arcadedb.query.sql.parser.OrBlock.evaluate(OrBlock.java:64)
	at com.arcadedb.query.sql.parser.WhereClause.matchesFilters(WhereClause.java:60)
	at com.arcadedb.query.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:78)
	at com.arcadedb.query.sql.executor.FilterStep$1.hasNext(FilterStep.java:98)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:47)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:40)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:211)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:90)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:74)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:79)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Unknown method name: values
	at com.arcadedb.query.sql.method.DefaultSQLMethodFactory.createMethod(DefaultSQLMethodFactory.java:130)
	at com.arcadedb.query.sql.executor.SQLEngine.getMethod(SQLEngine.java:93)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:130)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:82)
	at com.arcadedb.query.sql.parser.Modifier.execute(Modifier.java:102)
	at com.arcadedb.query.sql.parser.BaseExpression.execute(BaseExpression.java:155)
	at com.arcadedb.query.sql.parser.Expression.execute(Expression.java:117)
	at com.arcadedb.query.sql.parser.ContainsCondition.evaluate(ContainsCondition.java:164)
	at com.arcadedb.query.sql.parser.NotBlock.evaluate(NotBlock.java:61)
	at com.arcadedb.query.sql.parser.AndBlock.evaluate(AndBlock.java:63)
	at com.arcadedb.query.sql.parser.OrBlock.evaluate(OrBlock.java:64)
	at com.arcadedb.query.sql.parser.WhereClause.matchesFilters(WhereClause.java:60)
	at com.arcadedb.query.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:78)
	at com.arcadedb.query.sql.executor.FilterStep$1.hasNext(FilterStep.java:98)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:47)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:40)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:211)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:90)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:74)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:79)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)

```
</details>

## Actual behavior
```json
{
  "result": {
    "vertices": [],
    "records": [
      {
        "@rid": "#25:0",
        "@type": "Actor",
        "@cat": "d",
        "name": {
          "Luke": "Skyw"
        }
      }
    ],
    "edges": []
  },
  "user": "root",
  "version": "22.9.1 (build d082adcc702df85f7fd6f7a707d21aed4c7d0e68/1664822987697/main)"
}
```

## Steps to reproduce
```sql
CREATE DOCUMENT TYPE Actor; /* has to be performed separately first */
INSERT INTO Actor SET name = map("Luke","Skyw");
SELECT FROM Actor WHERE name.values() CONTAINS "Skyw";
```

**Comment by lvca** [comment]
The `values()` method was missing from the codebase when we imported the code from OrientDB. Restored, thanks.
