### ISSUE TITLE
ALIGN DATABASE not working

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#591]
## Expected behavior
?

## Actual behavior
```
ERROR: Align Database not supported
```
<details><summary>Trace</summary>

```
<ArcadeDB_0> Error on command execution (PostCommandHandler)
java.lang.UnsupportedOperationException: Align Database not supported
	at com.arcadedb.database.EmbeddedDatabase.alignToReplicas(EmbeddedDatabase.java:1457)
	at com.arcadedb.query.sql.parser.AlignDatabaseStatement.executeSimple(AlignDatabaseStatement.java:50)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:115)
	at com.arcadedb.query.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:53)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.doExecute(ScriptExecutionPlan.java:97)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.fetchNext(ScriptExecutionPlan.java:57)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:46)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:40)
	at com.arcadedb.database.EmbeddedDatabase.executeInternal(EmbeddedDatabase.java:1296)
	at com.arcadedb.database.EmbeddedDatabase.execute(EmbeddedDatabase.java:1244)
	at com.arcadedb.server.ServerDatabase.execute(ServerDatabase.java:415)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeScript(PostCommandHandler.java:100)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:71)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
```
</details>

## Steps to reproduce
```
ALIGN DATABASE
```
on a single server, using either console or studio.

If this command depends on certain conditions, such as at least one follower exists, then this should be added to the documentation.

**Comment by gramian** [comment]
Further testing results: If the HA module is enabled, `ALIGN DATABASE` can be used from the studio, but not from the console (Error in console `ERROR: Align Database not supported`, no resulting server error though).

1. So this seems to be a console specific issue (triggered from [here](https://github.com/ArcadeData/arcadedb/blob/4987804e130a226d4e24a3439dea8f3b51b0250b/server/src/main/java/com/arcadedb/server/ServerDatabase.java#L112) or [here](https://github.com/ArcadeData/arcadedb/blob/5f4420fc21e10eb4136e91dfcaab2af311d85c1a/engine/src/main/java/com/arcadedb/database/EmbeddedDatabase.java#L1456))?
2. And I guess it should be added to the docu that this command is only available if the HA module is loaded?

**Comment by lvca** [comment]
ALIGN DATABASE makes sense only in a distributed setup. I've added a note in ALIGN DATABASE command docs. About the issue with the console, the command should be fully supported: all the commands go through the HTTP server request. Did you connect the console remotely to the database?

**Comment by gramian** [comment]
I used the console locally.

However, the clear remark in the docu should resolve this.
