### ISSUE TITLE
Import Database with query result

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#601]
## Expected behavior
Succesful import

## Actual behavior
```
Server Error: Error on parsing source 'null'
```

<details><summary>Trace</summary>

```
2022-11-04 22:28:01.922 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D...
2022-11-04 22:28:02.945 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format XML (parsingLimitBytes=9,54MB parsingLimitEntries=0)
2022-11-04 22:28:02.946 INFO  [Importer] <ArcadeDB_0> Checking schema...- Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 0 vertices (0/sec) - 0 edges (0/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Error on importing database
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:61)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:115)
	at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:67)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:90)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:74)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:79)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
Caused by: com.arcadedb.integration.importer.ImportException: Error on parsing source 'null'
	at com.arcadedb.integration.importer.Importer.load(Importer.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:56)
	... 26 more
Caused by: java.lang.IllegalArgumentException: Record type 'DATABASE' is not supported
	at com.arcadedb.integration.importer.AbstractImporter.updateDatabaseSchema(AbstractImporter.java:246)
	at com.arcadedb.integration.importer.Importer.loadFromSource(Importer.java:84)
	at com.arcadedb.integration.importer.Importer.load(Importer.java:53)
	... 31 more
Executing full backup of database to 'test-backup-20221104-222803006.zip'...
Full backup completed in 0 seconds 448,36KB -> 2,51KB (99% compressed)
```
</details>

## Steps to reproduce
I was testing to import results from WikiData with [this](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20%28ps%3AP31%2F%28wdt%3AP279%2a%29%29%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) query, via the [`IMPORT DATABASE`](https://docs.arcadedb.com/#SQL-Import-Database) command and the SPARQL endpoint link as follows, where the query returns [XML data](https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D):
```
IMPORT DATABASE https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
```
Does the XML need to have a certain format?
I read in the command description that "only" OrientDB, Neo4J, GraphML, and GraphSON are supported, yet above in the [Importer](https://docs.arcadedb.com/#Importer) Section it states that also generic XML, CSV, JSON, and RDF files are supported.

**Comment by gramian** [comment]
I tested some more with local files, it seems as soon as the XML contains more than an empty root element the above error is thrown; particularly this line in the stack trace `Record type 'DATABASE' is not supported` lets me suspect that this is more than a (XML) formatting issue.

**Comment by gramian** [comment]
PS: In case there is some minimal formatting required for generic XML, CSV, JSON, and RDF by the `IMPORT DATABASE` command, could you point me to an explanation, so I can destill and add it to the docu?

**Comment by gramian** [comment]
See also https://github.com/ArcadeData/arcadedb/issues/645#issuecomment-1336270713 .

**Comment by gramian** [comment]
Current HEAD https://github.com/ArcadeData/arcadedb/commit/cbfbaa6e1eba754e0946da32223209f6dda64440 yields the following errors for `IMPORT DATABASE` test above:
```
2023-01-08 16:43:17.181 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format XML (parsingLimitBytes=9,54MB parsingLimitEntries=0)
2023-01-08 16:43:17.182 INFO  [Importer] <ArcadeDB_0> Checking schema...- Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 0 vertices (0/sec) - 0 edges (0/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Error on importing database
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:70)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:95)
	at com.arcadedb.query.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:55)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.doExecute(ScriptExecutionPlan.java:96)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.fetchNext(ScriptExecutionPlan.java:60)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:45)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:39)
	at com.arcadedb.database.EmbeddedDatabase.executeInternal(EmbeddedDatabase.java:1730)
	at com.arcadedb.database.EmbeddedDatabase.execute(EmbeddedDatabase.java:1259)
	at com.arcadedb.server.ServerDatabase.execute(ServerDatabase.java:421)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeScript(PostCommandHandler.java:121)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:89)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: com.arcadedb.integration.importer.ImportException: Error on parsing source 'null'
	at com.arcadedb.integration.importer.Importer.load(Importer.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:65)
	... 23 more
Caused by: java.lang.IllegalArgumentException: Record type 'DATABASE' is not supported
	at com.arcadedb.integration.importer.AbstractImporter.updateDatabaseSchema(AbstractImporter.java:252)
	at com.arcadedb.integration.importer.Importer.loadFromSource(Importer.java:84)
	at com.arcadedb.integration.importer.Importer.load(Importer.java:53)
	... 28 more
```

**Comment by lvca** [comment]
Just tried and I can reproduce the issue. From the code that format (sparql) is not supported by the importer. We'd need a new format implementation that recognizes the sparql (from the XML tag) and read the entities from the file.

**Comment by gramian** [comment]
This is not particularly about Wikidata XML as in the example, but i will need to import data from various sources, so this is rather testing to import arbitrary XML (or JSON or CSV)  into ArcadeDB.

**Comment by gramian** [comment]
@lvca I thought about how to import arbitrary JSON files: If the `IMPORT DATABASE` function cannot identify a known formatting; couldn't just be a new document type be created with the JSON `INSERT`ed as `CONTENT`?
For testing here is the above SPARQL query with JSON response:
```
https://query.wikidata.org/sparql?format=json&query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
```

**Comment by lvca** [comment]
Absolutely, but in what type?

**Comment by gramian** [comment]
Would a new document type like:
```
CREATE DOCUMENT TYPE importer IF NOT EXISTS;
```
work?

**Comment by lvca** [comment]
I meant where do you specify the vertex/document type name in the importing? Because it's not taken from the file content itself

**Comment by lvca** [comment]
You could use the `documentType` setting in the importer, like: `IMPORT DATABASE <URL> WITH documentType = 'MyType'`

**Comment by gramian** [comment]
I was just thinking of always using the same (hardcoded) type, for example `importer`, but your suggestion could be better.

**Comment by lvca** [comment]
You can already use the JSON importer, a new entry used to import the large public food database online, you can find it here: https://docs.arcadedb.com/#JSON-Importer. The mapping is very powerful, basically, you tell the importer what kind of documents or graphs to create. Please let me know if this works for you.

**Comment by gramian** [comment]
This looks indeed very powerful, but it looks like I have to know the structure of the incoming response. I won't know what document structure I get just that it is JSON.

**Comment by lvca** [comment]
The you should be able to remove mapping and it should work. Let me do some tests and add some test cases for this usecase first.

**Comment by gramian** [comment]
Great. I tried naively and failed

**Comment by lvca** [comment]
Yep, it needs some work to support the default mapping `{"*":[]}` so it would import anything from the root. I should be able to fix this today.

**Comment by gramian** [comment]
@lvca There is another problem with `IMPORT DATABASE` (maybe related):
```
IMPORT DATABASE https://query.wikidata.org/sparql?format=json&query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
```
It looks like the URL causes a problem, 23.1.2 reports:
```
Cannot execute command Encountered " <IDENTIFIER> "query "" at line 1, column 63. Was expecting one of: <EOF> <WITH> ... ";" ... 
```

**Comment by lvca** [comment]
Try using the backtick around the URL

**Comment by lvca** [comment]
Ok, importing a single object works. This is the test case to get the example:

```
  @Test
  public void importSingleObject() throws IOException {
    final String databasePath = "target/databases/test-import-graph";

    Importer importer = new Importer(
        ("-url file://src/test/resources/importer-one-object.json -database " + databasePath + " -documentType Food -forceDatabaseCreate true").split(" "));
    importer.load();

    try (final Database db = new DatabaseFactory(databasePath).open()) {
      Assertions.assertEquals(1, db.countType("Food", true));
    }

    TestHelper.checkActiveDatabases();
  }
```

So no mapping (by default takes the entire object and save it with the type name 'Food' (it creates the document type if not existent).

**Comment by lvca** [comment]
From SQL. it's just `IMPORT DATABASE <url> WITH documentType = 'Food'`

**Comment by gramian** [comment]
It is not working for me:
```
IMPORT DATABASE `http://maps.googleapis.com/maps/api/geocode/json?address=google` WITH documentType = 'Food'
```
or
```
IMPORT DATABASE `https://query.wikidata.org/sparql?format=json&query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D` WITH documentType = 'Food'
```
ie:
```
 Cannot execute command Encountered " <QUOTED_IDENTIFIER> "`https://query.wikidata.org/sparql?format=json query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20p%3AP31%20%3Fstatement0.%0A%20%20%20%20%20%20%3Fstatement0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ22907102.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D` "" at line 1, column 17. Was expecting one of: <HTTP_URL> ... <HTTPS_URL> ... <FILE_URL> ... <CLASSPATH_URL> ... 
 ```
 Sorry if I am dumb here

**Comment by lvca** [comment]
There was an issue with the encoding of parameters and SQL. Now it's fixed. I was able to run this, but the response is an error from the API:

![image](https://user-images.githubusercontent.com/312606/217702772-473bcc16-a6f1-4624-9cf9-4cb0222ba54a.png)

**Comment by gramian** [comment]
@lvca Most tests work now. Awesome! Though backticks around a URL still do not work. I guess this is the problem in the second test above.

**Comment by lvca** [comment]
I guess I should work on the parser to be more flexible about inputs... Sometimes it takes an Identifier(), other times an expression or a string. In this cases, it should support no quotes, single quotes, double quotes and ticks.
