### ISSUE TITLE
Wildcard escape `\%` produces error

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#603]
## Expected behavior
Filtered results by wildcard and percent sign, ie 10%, 100%. 

## Actual behavior
`Error on command execution (PostCommandHandler)`
<details><summary>Trace</summary>

```
com.arcadedb.query.sql.parser.TokenMgrException: Lexical error at line 1, column 37.  Encountered: "%" (37), after : "\"10%\\"
	at com.arcadedb.query.sql.parser.SqlParserTokenManager.getNextToken(SqlParserTokenManager.java:5724)
	at com.arcadedb.query.sql.parser.SqlParser.jj_scan_token(SqlParser.java:26594)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_461(SqlParser.java:18548)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_331(SqlParser.java:18515)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_149(SqlParser.java:18456)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_275(SqlParser.java:18341)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_122(SqlParser.java:18285)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_174(SqlParser.java:20147)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_351(SqlParser.java:19753)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_166(SqlParser.java:19654)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_635(SqlParser.java:19596)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_550(SqlParser.java:19587)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_451(SqlParser.java:19554)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_322(SqlParser.java:19532)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_145(SqlParser.java:19514)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_410(SqlParser.java:19508)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_269(SqlParser.java:22491)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_121(SqlParser.java:22440)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_341(SqlParser.java:22262)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_165(SqlParser.java:22247)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_91(SqlParser.java:21643)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3_33(SqlParser.java:21495)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_205(SqlParser.java:21478)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3R_62(SqlParser.java:21439)
	at com.arcadedb.query.sql.parser.SqlParser.jj_3_3(SqlParser.java:20426)
	at com.arcadedb.query.sql.parser.SqlParser.jj_2_3(SqlParser.java:16846)
	at com.arcadedb.query.sql.parser.SqlParser.ParseScript(SqlParser.java:311)
	at com.arcadedb.query.sql.executor.SQLEngine.parseScript(SQLEngine.java:108)
	at com.arcadedb.query.sql.executor.SQLEngine.parseScript(SQLEngine.java:102)
	at com.arcadedb.database.EmbeddedDatabase.execute(EmbeddedDatabase.java:1243)
	at com.arcadedb.server.ServerDatabase.execute(ServerDatabase.java:415)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeScript(PostCommandHandler.java:100)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:71)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
```
</details>

## Steps to reproduce
```
INSERT INTO D SET value = "10%"
INSERT INTO D SET value = "100%"
SELECT FROM D WHERE value LIKE "10%\%"
```
Pure wildcard is working:
```
SELECT FROM D WHERE value LIKE "10%"
```
Also not working:
```
SELECT FROM D WHERE value LIKE "10\%"
```

**Comment by gramian** [comment]
I am guessing here, but maybe in the [source file](https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/query/sql/executor/QueryHelper.java) could lie an issue: The cases replacing wildcard characters `%` and `?` cannot know if the previous character was a `\\`?

**Comment by lvca** [comment]
I've just added this test case and works:

```java
  public void test() {
    LikeOperator op = new LikeOperator(-1);
    Assertions.assertTrue(op.execute(null, "100\\%", "100\\%"));
    Assertions.assertTrue(op.execute(null, "100\\%", "100%"));
  }
```

So the operator looks fine. It could be something in the parsing of the SQL. I'm going to write an integration test to reproduce the exact problem you have.

**Comment by lvca** [comment]
Reproduced. The issue seems to be in the SQL parser (JavaCC). Working on it.

**Comment by lvca** [comment]
Found the issue, fixed. The right way is to use `SELECT FROM D WHERE value LIKE "10\%"`. By using `\%` you're escaping `%` to be treated as character, and not as any characters in LIKE.

**Comment by gramian** [comment]
Thank you!
