### ISSUE TITLE
Cypher - string concatenation not supported

### ISSUE THREAD

**Issue by ddiminic** [ArcadeData/arcadedb#618]
### OS: Ubuntu 20.04 as Docker host
Ran as dockerized image (arcadedata/arcadedb:latest)

## Expected behavior
Cypher query successfully ran.
It should be supported according to openCypher v9 grammar.

## Actual behavior
Fails to execute with the following stacktrace:

`<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.QueryParsingException: Error on executing Cypher query
        at com.arcadedb.gremlin.query.CypherQueryEngine.command(CypherQueryEngine.java:72)
        at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
        at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
        at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
        at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
        at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: java.util.concurrent.ExecutionException: groovy.lang.MissingMethodException: No signature of method: org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.cypherPlus() is applicable for argument types: () values: []
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeGremlin.execute(ArcadeGremlin.java:53)
        at org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeCypher.execute(ArcadeCypher.java:63)
        at com.arcadedb.gremlin.query.CypherQueryEngine.command(CypherQueryEngine.java:69)
        ... 16 more
Caused by: groovy.lang.MissingMethodException: No signature of method: org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.cypherPlus() is applicable for argument types: () values: []
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.callGlobal(GremlinGroovyScriptEngine.java:772)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.access$100(GremlinGroovyScriptEngine.java:94)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$3.invokeMethod(GremlinGroovyScriptEngine.java:664)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:76)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
        at Script1.run(Script1.groovy:1)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:678)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:380)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
`

## Steps to reproduce
run `MATCH (a:Person) RETURN a.name+'TESTSTRING'` with Cypher

**Comment by gramian** [comment]
This seems to work meanwhile:
1. Setup via SQL:
```sql
CREATE VERTEX TYPE person;
CREATE PROPERTY person.name STRING;
INSERT INTO person SET name = 'a';
```
2. Test in Cypher:
```cypher
MATCH (x:person) RETURN x.name + 'test'
```
Returns the correct result.

Tested in `23.10.1`, in Studio.
