### ISSUE TITLE
SQL: IS Comparison

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#626]
### OS: MacOS 12.6

Dear Developers,
It seems `IS` in `WHERE` can only be used with `null`, other right-hand side arguments seem to produce an error (see below). It might be that `IS` is meant as a comparison operator to exclusively compare against `null`, but then it could have been named `ISNULL` directly, so I assumed it is a null-safe comparison operator as in [SQLite](https://www.sqlite.org/lang_expr.html#isisnot) (which is pretty useful).

## Expected behavior
1

## Actual behavior
`Error on command execution (PostCommandHandler)`
`Encountered "" at line 1, column 26.
Was expecting one of:`

<details><summary>Trace</summary>

```
Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandSQLParsingException: SELECT FROM mytype WHERE value IS 1;
	at com.arcadedb.query.sql.parser.StatementCache.throwParsingException(StatementCache.java:123)
	at com.arcadedb.query.sql.parser.StatementCache.parse(StatementCache.java:115)
	at com.arcadedb.query.sql.parser.StatementCache.get(StatementCache.java:70)
	at com.arcadedb.query.sql.executor.SQLEngine.parse(SQLEngine.java:97)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:75)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: com.arcadedb.query.sql.parser.ParseException: Encountered "" at line 1, column 26.
Was expecting one of:
    
	at com.arcadedb.query.sql.parser.SqlParser.generateParseException(SqlParser.java:26749)
	at com.arcadedb.query.sql.parser.SqlParser.jj_consume_token(SqlParser.java:26585)
	at com.arcadedb.query.sql.parser.SqlParser.NotBlock(SqlParser.java:7437)
	at com.arcadedb.query.sql.parser.SqlParser.AndBlock(SqlParser.java:7265)
	at com.arcadedb.query.sql.parser.SqlParser.OrBlock(SqlParser.java:7216)
	at com.arcadedb.query.sql.parser.SqlParser.WhereClause(SqlParser.java:7182)
	at com.arcadedb.query.sql.parser.SqlParser.SelectStatement(SqlParser.java:1456)
	at com.arcadedb.query.sql.parser.SqlParser.QueryStatement(SqlParser.java:1167)
	at com.arcadedb.query.sql.parser.SqlParser.StatementInternal(SqlParser.java:977)
	at com.arcadedb.query.sql.parser.SqlParser.Statement(SqlParser.java:894)
	at com.arcadedb.query.sql.parser.SqlParser.parse(SqlParser.java:238)
	at com.arcadedb.query.sql.parser.StatementCache.parse(StatementCache.java:110)
	... 19 more
```
</details>

## Steps to reproduce
```
CREATE DOCUMENT TYPE mytype;
INSERT INTO mytype SET value = 1;
SELECT value FROM mytype WHERE value IS 1;
```

**Comment by gramian** [comment]
Looking through the grammar definition, I understand now that there are the variants `IS NULL`, `IS NOT NULL`, `IS DEFINED`, `IS NOT DEFINED` relating to the `IS` keyword. So, would it be complicated to add `IS` to [`CompareOperator`](https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/grammar/SQLGrammar.jjt#L2450) yielding a null-safe equality comparison operator?

**Comment by lvca** [comment]
Why don't just use the equals (=) operator? What is the use case where `IS` could be useful?

**Comment by gramian** [comment]
The "equal" operator returns `null` if one or either of its operands are `null`:

| **=**    | **0** | **1** | **null** |
|----------|-------|-------|----------|
| **0**    | true  | false | null     |
| **1**    | false | true  | null     |
| **null** | null  | null  | null     |

a null-safe equality operator such as `IS` (aka `<=>` in [MariaDB](https://mariadb.com/kb/en/null-safe-equal/)) would yield only boolean values:

| **=**    | **0** | **1** | **null** |
|----------|-------|-------|----------|
| **0**    | true  | false | false    |
| **1**    | false | true  | false    |
| **null** | false | false | true     |

Note: the first row and columns are supposed to be inputs while the inner 3x3 cells denote outputs.

**Comment by gramian** [comment]
With respect to the example above, using:

```
CREATE DOCUMENT TYPE mytype;
INSERT INTO mytype SET value = null;
SELECT value FROM mytype WHERE value = null;
```

returns no results.

**Comment by lvca** [comment]
Gotcha. The equals operator just returns NULL whether left or right statements are null. I've checked the SQL grammar and IS is not an operator. There are `IS NULL`, `IS NOT NULL`, `IS DEFINED` and `IF NOT DEFINED`, but they are encoded as special operators. So this must be written from scratch. Not sure if @antarcticgiraffe is still available for that

**Comment by gramian** [comment]
I am probably imagining this as way to easy, but couldn't it be sufficient to

1. add a new token, for example `<=>`
2. copy (and adapt) [this block](https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/grammar/SQLGrammar.jjt#L2543) in the grammar
3. add a similar file to [this one](https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/query/sql/parser/EqualsCompareOperator.java) and adapt [this line](https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/query/sql/parser/EqualsCompareOperator.java#L59)

If @lvca or @antarcticgiraffe could weigh in on the feasibility of this approach, I could try it out, when I find some time.

**Comment by lvca** [comment]
All correct, but the actual operation is in this method: https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/query/sql/parser/EqualsCompareOperator.java#L39.

@gramian it's a perfect issue to get your feet wet with ArcadeDB internals. Don't hesitate to ask for help!

A few tips:
- once you change the grammar, run `mvn clean install -DskipTests` from the core package and the parser classes will be generated
- the actual comparison should be the same as `QueryOperatorEquals.equals()` without the initial check for nulls

**Comment by gramian** [comment]
All right, I will take a shot at it.
