### ISSUE TITLE
`include` and `exclude` methods unknown

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#664]
## Expected behavior
?

## Actual behavior
`<ArcadeDB_0> Error on command execution (PostCommandHandler)`
<details><summary>Trace</summary>

```
com.arcadedb.exception.CommandExecutionException: Unknown method name: include
	at com.arcadedb.query.sql.method.DefaultSQLMethodFactory.createMethod(DefaultSQLMethodFactory.java:138)
	at com.arcadedb.query.sql.executor.SQLEngine.getMethod(SQLEngine.java:93)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:130)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:82)
	at com.arcadedb.query.sql.parser.Modifier.execute(Modifier.java:102)
	at com.arcadedb.query.sql.parser.BaseExpression.execute(BaseExpression.java:150)
	at com.arcadedb.query.sql.parser.Expression.execute(Expression.java:114)
	at com.arcadedb.query.sql.parser.ProjectionItem.execute(ProjectionItem.java:147)
	at com.arcadedb.query.sql.parser.Projection.calculateSingle(Projection.java:134)
	at com.arcadedb.query.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:82)
	at com.arcadedb.query.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:57)
	at com.arcadedb.query.sql.executor.ExpandStep.fetchNext(ExpandStep.java:136)
	at com.arcadedb.query.sql.executor.ExpandStep$1.hasNext(ExpandStep.java:59)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:47)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:40)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:211)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:90)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:74)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:79)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
```
</details>

Similarly for `exclude`

## Steps to reproduce

```
SELECT expand( @this.include( 'name' ) ) FROM mytype;
SELECT expand( @this.exclude( 'name' ) ) FROM mytype;
```

**Comment by gramian** [comment]
I can't find any reference in the sources to these methods.

**Comment by lvca** [comment]
For some reason, those 2 methods weren't migrated from the OrientDB code base... Just did it.
