### ISSUE TITLE
java.lang.ClassNotFoundException: org.opencypher.v9_0.util.SyntaxException

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb#715]
## Expected behavior
I build ArcadeDB from the sources into a docker image (see the attached Dockerfile).
Starting a new container with this image should bring up the ArcadeDB server.

## Actual behavior
when the Gremlin plugin gets started the following error occurs:

```
2022-12-28 16:55:06.834 SEVER [ServerGremlinExecutor] Could not invoke constructor on class org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager (defined by the 'graphManager' setting) with one argument of class SettingsException in thread "main" com.arcadedb.server.ServerException: Error on loading plugin from class 'GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin;
	at com.arcadedb.server.ArcadeDBServer.registerPlugins(ArcadeDBServer.java:196)
	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:134)
	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:91)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:97)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:127)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:90)
	at com.arcadedb.server.gremlin.GremlinServerPlugin.startService(GremlinServerPlugin.java:87)
	at com.arcadedb.server.ArcadeDBServer.registerPlugins(ArcadeDBServer.java:189)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:86)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: org/opencypher/v9_0/util/SyntaxException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:63)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:106)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.addGraph(DefaultGraphManager.java:63)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:58)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.opencypher.v9_0.util.SyntaxException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

## Steps to reproduce
in the directory with the Dockerfile run
`docker build -t arcadedb-image/latest . `
then
`docker run -p 2480:2480 -p 2424:2424 -p 6379:6379 -p 5432:5432 -p 8182:8182 arcadedb-image:latest`

[Dockerfile.zip](https://github.com/ArcadeData/arcadedb/files/10315429/Dockerfile.zip)

**Comment by lvca** [comment]
What is arcadedb-image you using with docker?

Try to run this:

```
docker run --rm -p 2480:2480 -p 2424:2424
           -e arcadedb.server.rootPassword=playwithdata
           -e "arcadedb.server.defaultDatabases=OpenBeer[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
           arcadedata/arcadedb:latest
```

**Comment by gfinger** [comment]
Ciao Luca,
my goal was to build the ArcadeDB from the sources. As Tinkerpop supports only Java 11, I run the maven build inside a docker container with this Java version.
I wonder what differences there are with the library versions in your container and mine. Would you mind sending me your dockerfile so that I can see what might be the reason for this error?
Grazie per suo aiuto!
Gregor

**Comment by lvca** [comment]
I'm using the one included in the distribution: https://github.com/ArcadeData/arcadedb/blob/7ce850bd4957f90e14376c197cd4dbb876c98e31/package/src/main/docker/Dockerfile

**Comment by lvca** [comment]
@gfinger any luck with that?

**Comment by gfinger** [comment]
No, that doesn't help. I wonder how you build and run the software without the above shown exception. Basically I run "mvn clean package" in a Java 11 environment on Ubuntu, and than run the server.sh script.
It is only because I have a newer Java version on my Mac that I run the whole thing in a Docker container based on Ubuntu. But inside Docker or not, the issue should basically the same. Strange.

**Comment by lvca** [comment]
Any particular reason why you're using SAP JVM? Have you tried OpenJDK (I know SAP VM is derived from OpenJDK)

**Comment by gfinger** [comment]
Actually in my latest version of the Dockerfile I do not use the SAP JVM but the OpenJDK. The aforementioned error happens when I start the ArcadeDB in my Docker container. The image used by this container is created with the OpenJDK. The JVM is not the cause for the error. I attach the latest Dockerfile version. 
[arcadedb-image.zip](https://github.com/ArcadeData/arcadedb/files/10359068/arcadedb-image.zip)

**Comment by lvca** [comment]
I found the issue: we upgraded to eclipse-temurin:19. The last part is the JDK version, not the version of the distribution itself... Just reverted on github and pushing the docker images to DockerHub in minutes

**Comment by lvca** [comment]
They are all updated now (latest, 23.1.1 and 23.1.2-SNAPSHOT). Sorry for the

**Comment by gfinger** [comment]
Even after a rebuild of ArcadeDB Server v23.1.2-SNAPSHOT from the main branch I still have the same error.

**Comment by lvca** [comment]
If you run this, Cypher works?

```
docker run --rm -p 2480:2480 -p 2424:2424
           -e JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
           arcadedata/arcadedb:latest
```

**Comment by gfinger** [comment]
No, the startup blocks after showing the initial "ARCADEDB" on the console.
But anyway using the ready-made image from the docker registry does not address my issue, as I want to run the ArcadeDB from a local build. My goal is to contribute here and there to the code of thedb, but this requires to build, run and test the code locally.
Perhaps my issue is due to not using the right gremlin libraries? I am using apache-tinkerpop-gremlin-server-3.6.1-bin.

**Comment by gfinger** [comment]
The duplicated-key error results from trying to import the db twice. Now everything looks good. I close this issue.
