### ISSUE TITLE
NPE when executing queries on Studio

### ISSUE THREAD

**Issue by vic0824** [ArcadeData/arcadedb#730]
### JDK Version: openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.1 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode)
## Expected behavior
Queries on Studio are executed correctly, as in previous versions

## Actual behavior
submitting a query on Studio results in an "Internal error" message being displayed.
The arcadedb.log file shows `Error on command execution (PostCommandHandler)
java.lang.NullPointerException
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:55)`

## Steps to reproduce
1. create a class that creates a database using the DatabaseFactory, creates a type with a property and starts the ArcadeDB server in embedded mode
2. open Studio
3. execute a select on the type
4. verify that the server responds with a 500 error to the http://[host]:[port]/api/v1/command/[db_name] request
5. inspect the arcadedb.log0 file:

The attached screenshot shows what I see in the browser.
Below are the relevant log messages:
`2023-01-01 11:46:34.046 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v22.12.1 (build 08eb71f7264ba1eacd872632dcd2162765ddb67e/1671833658668/main) is starting up...
2023-01-01 11:46:34.047 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [Orchestrator] ...
2023-01-01 11:46:34.092 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
2023-01-01 11:46:34.227 INFO  [ArcadeDBServer] <ArcadeDB_0> - Orchestrator plugin started
2023-01-01 11:46:34.228 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=8080)...
2023-01-01 11:46:34.256 INFO  [undertow] starting server: Undertow - 2.3.2.Final
2023-01-01 11:46:34.263 INFO  [xnio] XNIO version 3.8.8.Final
2023-01-01 11:46:34.270 INFO  [nio] XNIO NIO Implementation Version 3.8.8.Final
2023-01-01 11:46:34.371 INFO  [threads] JBoss Threads version 3.5.0.Final
2023-01-01 11:46:34.417 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=8080)
2023-01-01 11:46:34.424 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [java, js, sql]
2023-01-01 11:46:34.425 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started (CPUs=2 MAXRAM=351.88MB)
2023-01-01 11:46:34.425 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://localhost:8080 <ArcadeDB_0> Error on command execution (PostCommandHandler)
java.lang.NullPointerException
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:55)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
        at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:110)
        at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)`

![Studio error](https://user-images.githubusercontent.com/29632118/210169099-e5f0123a-4b16-47f4-9aee-0c6d8744352c.png)

**Comment by vic0824** [comment]
As an additional information, the same query can be executed from the Console (with remote connection) without problems

**Comment by lvca** [comment]
@vic0824 I cannot reproduce your issue with the latest branch. Any chance you can use the latest snapshot? Perhaps building it from the repository is super fast:

```
git pull
mvn clean install -DskipTests
cd package/target
```

Where you can find your freshly built snapshot. If it's an issue, I'll test your case against v22.12.1 in the next days.

**Comment by vic0824** [comment]
Tested it with v23.1.1-SNAPSHOT (build https://github.com/ArcadeData/arcadedb/commit/1b37118321bb5be4377a15ab67b45473242c1e14/1672647527307/main), it does not occur.
It was probably due to me using the front-end part of 23.1.1-SNAPSHOT with the back-end part of 22.12.1

**Comment by lvca** [comment]
Thanks for testing it.
