### ISSUE TITLE
SQL: Multiple `distinct()` functions in a projection fails

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#803]
### OS: MacOS 12.6

If multiple `distinct()` functions are used in a projection, a query fails.

This may be related to an overlap in the grammar due to the function `distinct()` and statement `DISTINCT`?

## Expected behavior
No error.

## Actual behavior
`Error on command execution (PostCommandHandler)`

<details> <summary>Trace</summary>

```
com.arcadedb.exception.CommandExecutionException: Unknown function name 'distinct'
	at com.arcadedb.query.sql.SQLQueryEngine.getFunction(SQLQueryEngine.java:197)
	at com.arcadedb.query.sql.parser.FunctionCall.getFunction(FunctionCall.java:458)
	at com.arcadedb.query.sql.parser.FunctionCall.getCachedFunction(FunctionCall.java:463)
	at com.arcadedb.query.sql.parser.FunctionCall.isAggregateFunction(FunctionCall.java:316)
	at com.arcadedb.query.sql.parser.FunctionCall.isAggregate(FunctionCall.java:259)
	at com.arcadedb.query.sql.parser.LevelZeroIdentifier.isAggregate(LevelZeroIdentifier.java:180)
	at com.arcadedb.query.sql.parser.BaseIdentifier.isAggregate(BaseIdentifier.java:168)
	at com.arcadedb.query.sql.parser.BaseExpression.isAggregate(BaseExpression.java:269)
	at com.arcadedb.query.sql.parser.Expression.isAggregate(Expression.java:383)
	at com.arcadedb.query.sql.parser.ProjectionItem.isAggregate(ProjectionItem.java:193)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.isAggregate(SelectExecutionPlanner.java:606)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.splitProjectionsForGroupBy(SelectExecutionPlanner.java:570)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.optimizeQuery(SelectExecutionPlanner.java:422)
	at com.arcadedb.query.sql.executor.SelectExecutionPlanner.createExecutionPlan(SelectExecutionPlanner.java:131)
	at com.arcadedb.query.sql.parser.SelectStatement.createExecutionPlan(SelectStatement.java:219)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:212)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:92)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:76)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:106)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1248)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:134)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:94)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:123)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Steps to reproduce
While:
```
SELECT distinct(myprop) FROM mytype;
```
works, this:
```
SELECT distinct(myprop), distinct(myprop) FROM mytype;
```
does not.

**Comment by gramian** [comment]
I am trying to emulate the Jaccard index, see https://github.com/ArcadeData/arcadedb/discussions/625, in various attempts the`DISTINCT` statement as well as the `distinct()` function fails to work. Either it just acts as an identity or it throws an error. I will try to provide another test case.

**Comment by lvca** [comment]
This is by design with ArcadeDB (inherited from OrientDB).
