### ISSUE TITLE
Using RemoteDatabase with Gremlin

### ISSUE THREAD

**Issue by JREastonMarks** [ArcadeData/arcadedb#816]
## Expected behavior
To be able to run a Gremlin Query from a RemoteDatabase

## Actual behavior
Throws the following exception:
```
ervlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: 'java.util.Map com.google.gson.JsonObject.asMap()'] with root cause
java.lang.NoSuchMethodError: 'java.util.Map com.google.gson.JsonObject.asMap()'
	at com.arcadedb.serializer.json.JSONObject.toMap(JSONObject.java:196)
	at com.arcadedb.remote.RemoteDatabase.json2Record(RemoteDatabase.java:578)
	at com.arcadedb.remote.RemoteDatabase.json2Result(RemoteDatabase.java:570)
	at com.arcadedb.remote.RemoteDatabase.createResultSet(RemoteDatabase.java:564)
	at com.arcadedb.remote.RemoteDatabase.lambda$query$3(RemoteDatabase.java:252)
	at com.arcadedb.remote.RemoteDatabase.httpCommand(RemoteDatabase.java:379)
	at com.arcadedb.remote.RemoteDatabase.databaseCommand(RemoteDatabase.java:325)
	at com.arcadedb.remote.RemoteDatabase.query(RemoteDatabase.java:252)
	at com.pleiades.atlas.app.controller.TestController.testMe2(TestController.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1010)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:902)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:884)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

## Steps to reproduce
```
RemoteDatabase arcadeDB = new RemoteDatabase("localhost", 2480, "atlasDB", "root", "PASSWORD");
ResultSet result = arcadeDB.query("gremlin", "g.V(\"#1:745877\")");
while (result.hasNext()) {
   Result record = result.next();
}
```

## Down the Rabbit Hole
In RemoteDatabase.createResultSet() the response is type JSONObject that looks like the following:
```
{"result":[{"@rid":"#1:745877","@type":"Compound","@cat":"v","@out":2,"@in":2,"xref":{"chebiId":"132049"},"name":"N-tetracosanoyl-taurine"}]}
```

However in RemoteDatabase.json2Result the result object looks like
```
{"@rid":"#1:745877","@type":"Compound","@cat":"v","@out":2,"@in":2,"xref":{"chebiId":"132049"},"name":"N-tetracosanoyl-taurine"}
```
Which calls RemoteDatabase.json2Record which throws the exception when it tries to convert the result into a map.

The object.asMap() inside com.arcadedb.serializer.json.JSONObject throws the exception on the object.

##  Theory
Could it be the nested object that is causing this?

**Comment by JREastonMarks** [comment]
I was able to resolve this by myself.
The issue was that I had old version of GSON (2.9) that got stuck in my maven repository. I forced Maven to update to version 2.10.1 which has the asMap function and it works now.

Closing

**Comment by lvca** [comment]
@JREastonMarks I'm glad you were able to find the solution. Nice you detailed the issue so users could find this issue and solution if they encounter a similar problem.
