### ISSUE TITLE
Neo4J Import Fails for very large graphs

### ISSUE THREAD

**Issue by bhurley-sayari** [ArcadeData/arcadedb#842]
### OS: (whatever was used in docker container)

When trying to import a very large graph in the neo4j format, the import fails.  I believe the issue is that compaction is causing some sort of race condition where it is trying to write to a file which has already been deleted by compaction

```
2023-02-07 07:24:32.975 INFO  [LSMTreeIndex] Index 'property_4_70255128342074' compacted in 1362ms (keys=539262 values=539262 mutablePages=2 immutablePages=21 iterations=539264 oldLevel0File=property_4_89142850524904(537) newLevel0File=property_4_90099801025450(551) newLevel1File=property_4_89140619817088(533) threadId=52)<arcadedb-0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Error on importing database
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:66)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:63)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:106)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1250)
	at com.arcadedb.server.ha.ReplicatedDatabase.command(ReplicatedDatabase.java:594)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.lambda$execute$0(DatabaseAbstractHandler.java:87)
	at com.arcadedb.server.http.HttpSession.execute(HttpSession.java:58)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:86)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.arcadedb.integration.importer.ImportException: Error on parsing source 'file:///mnt/data0/arcade.jsonl (compressed=false size=583978576503)'
	at com.arcadedb.integration.importer.Importer.load(Importer.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.arcadedb.query.sql.parser.ImportDatabaseStatement.executeSimple(ImportDatabaseStatement.java:61)
	... 21 more
Caused by: com.arcadedb.exception.TransactionException: Transaction error on commit
	at com.arcadedb.database.TransactionContext.commit2ndPhase(TransactionContext.java:574)
	at com.arcadedb.database.TransactionContext.commit(TransactionContext.java:117)
	at com.arcadedb.database.EmbeddedDatabase.lambda$commit$2(EmbeddedDatabase.java:366)
	at com.arcadedb.database.EmbeddedDatabase.executeInReadLock(EmbeddedDatabase.java:1326)
	at com.arcadedb.database.EmbeddedDatabase.commit(EmbeddedDatabase.java:361)
	at com.arcadedb.integration.importer.Neo4jImporter.lambda$parseVertices$3(Neo4jImporter.java:312)
	at com.arcadedb.integration.importer.Neo4jImporter.readFile(Neo4jImporter.java:465)
	at com.arcadedb.integration.importer.Neo4jImporter.parseVertices(Neo4jImporter.java:279)
	at com.arcadedb.integration.importer.Neo4jImporter.run(Neo4jImporter.java:156)
	at com.arcadedb.integration.importer.format.Neo4jImporterFormat.load(Neo4jImporterFormat.java:47)
	at com.arcadedb.integration.importer.Importer.loadFromSource(Importer.java:90)
	at com.arcadedb.integration.importer.Importer.load(Importer.java:53)
	... 26 more
Caused by: com.arcadedb.exception.SchemaException: File with id '547' was not found
	at com.arcadedb.schema.EmbeddedSchema.getFileById(EmbeddedSchema.java:227)
	at com.arcadedb.database.TransactionContext.commit2ndPhase(TransactionContext.java:554)
	... 37 more
```

## Expected behavior
I should be able to import a very large graph in the neo4j format

## Actual behavior
The import dies due to a race condition.

## Steps to reproduce

1. create a very large file in the neo4j export format, our graph has a couple of billion vertices and edges, but this problem occurred with only approx. 25,000,000 vertices imported.
2. download the export file to the container
3. call `import database file://PATH_TO_EXPORT`

**Comment by lvca** [comment]
At first glance, it makes sense that this could be caused by the underlying compaction. Working into a way to reproduce such behavior.

**Comment by lvca** [comment]
I believe I found the issue. The transaction is optimistic, so it gets all the required locks on involved files only at 1st phase of the commit and then start applying the changes on the actual index file. The issue is that the locks are based on file ids (integers), but in the transaction they are kept by name.

So the lock phase could have locked file X1 because associated with index I1, but before applying changes to the index, a compaction task just finished (it must have run during the user TX begin->commit) and right at this time it replaces the old file with the new file. The index name is the same, but the underlying file id is now changed.

I'm checking where this can be fixed avoiding having a big lock during compaction.

**Comment by lvca** [comment]
@bhurley-sayari could you please repeat the huge import with the last version built from the `main` branch and using this settings when you run the server?

`-Darcadedb.typeDefaultBuckets=1`

This forces the type to have only 1 bucket (instead of multiple). This should make the import process smoother and able to complete.

**Comment by bhurley-sayari** [comment]
@lvca I have restarted the process and will let you know how it goes sometime tomorrow (hopefully depending on how long it takes).  In the intervening are you open to external PRs?  Given my use case, it would be great if we could avoid [parsing the entire file 3 times](https://github.com/ArcadeData/arcadedb/blob/main/integration/src/main/java/com/arcadedb/integration/importer/Neo4jImporter.java#L139).  I think getting rid of the first pass should be as easy as (famous last words) adding a flag to skip the schema inference and just relying on the user to input the correct schema in advance?  Happy to take a pass at it if that is something you're open to?

**Comment by lvca** [comment]
@bhurley-sayari absolutely open to PR!

**Comment by bhurley-sayari** [comment]
@lvca I did and it threw some seg fault, so I had gone back to the version in dockerhub, but with one bucket and that did work, but the insert rate was too slow for my purposes.  Ended up using a different tool so I haven't had much chance to look into it further.
