### ISSUE TITLE
SQL: Setting a `SUPERTYPE`

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#862]
### OS: MacOS 12.6

Setting a super type without the `+` character prefixing the super type fails, even though documented to work. However, given the `+` / `-` syntax, is the plain syntax even necessary? If so, this part could just be removed from the documentation.

## Expected behavior
Success

## Actual behavior

`Cannot execute command Encountered " <ALTER> "ALTER "" at line 1, column 1. Was expecting one of: <ALIGN> ... <SELECT> ... <TRAVERSE> ... <MATCH> ... <INSERT> ... <RETURN> ... <CHECK> ... <BACKUP> ... <REBUILD> ... <EXPORT> ... <IMPORT> ... <BEGIN> ... <COMMIT> ... <ROLLBACK> ... <IF> ... <SLEEP> ... <SELECT> ... <SELECT> ... <TRAVERSE> ... <MATCH> ... <INSERT> ... `

<details>

```
<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandSQLParsingException: ALTER TYPE sup SUPERTYPE doc
	at com.arcadedb.query.sql.parser.StatementCache.throwParsingException(StatementCache.java:126)
	at com.arcadedb.query.sql.parser.StatementCache.parse(StatementCache.java:116)
	at com.arcadedb.query.sql.parser.StatementCache.get(StatementCache.java:70)
	at com.arcadedb.query.sql.SQLQueryEngine.parse(SQLQueryEngine.java:207)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:102)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1250)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:91)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.arcadedb.query.sql.parser.ParseException: Encountered " <ALTER> "ALTER "" at line 1, column 1.
Was expecting one of:
    <ALIGN> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <CHECK> ...
    <BACKUP> ...
    <REBUILD> ...
    <EXPORT> ...
    <IMPORT> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <SELECT> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    
	at com.arcadedb.query.sql.parser.SqlParser.generateParseException(SqlParser.java:26917)
	at com.arcadedb.query.sql.parser.SqlParser.jj_consume_token(SqlParser.java:26762)
	at com.arcadedb.query.sql.parser.SqlParser.StatementInternal(SqlParser.java:1359)
	at com.arcadedb.query.sql.parser.SqlParser.Statement(SqlParser.java:1004)
	at com.arcadedb.query.sql.parser.SqlParser.Parse(SqlParser.java:245)
	at com.arcadedb.query.sql.parser.StatementCache.parse(StatementCache.java:111)
	... 16 more
```
</details>

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
CREATE DOCUMENT TYPE sup;
ALTER TYPE sup SUPERTYPE doc;
```
This works as expected:
```
ALTER TYPE sup SUPERTYPE +doc;
```

**Comment by lvca** [comment]
I remember we removed that syntax from ArcadeDB, because using `+` and `-` was easier to do. We can remove from the docs any reference to the old-OrientDB syntax.

**Comment by gramian** [comment]
What about the `SUPERTYPES` keyword for multiple inheritances? I could just use multiple `SUPERTYPE` commands to achieve the same, right? I saw in the grammar that `SUPERTYPES` is still there, but it throws a similar error as above when used.

* Should I remove `SUPERTYPES` from the docu too?
* Should it be removed from the grammar or is there a special purpose for `SUPERTYPES`?

**Comment by lvca** [comment]
SUPERTYPES is not used in ArcadeDB, I'm removing it from the grammar. Thanks, @gramian!

**Comment by gramian** [comment]
https://github.com/ArcadeData/arcadedb-docs/pull/119 fixes this in the docs

**Comment by lvca** [comment]
Thanks
