### ISSUE TITLE
Unable to run database.query Statement

### ISSUE THREAD

**Issue by srp-asach** [ArcadeData/arcadedb#865]
## Expected behavior
Should return ResultSet of the query 

## Actual behavior
Throwing exception as

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.gson.JsonObject.asMap()Ljava/util/Map;
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1086) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.24.jar:5.3.24]

## Steps to reproduce
Create Database 
Add vertex :  ```` create vertex type Customer if not exists; ````
Add Properties : 
````
create property Customer.name if not exists string;
create property Customer.surname if not exists string;
````

Create connection in Java and execute below code

````
ResultSet resultSet = database.query("SQL", "select from Customer");
Map<String, Object> customer = resultSet.stream().findFirst().map(Result::toMap).orElse(Map.of());
````

**Comment by srp-asach** [comment]
The same issue is throwing on JDK 17

**Comment by srp-asach** [comment]
Even tried with ```` database.command ```` it is throwing same exception

**Comment by lvca** [comment]
It looks like you have an old version of the Google GSON library in your classpath that is conflicting with the latest used by ArcadeDB. The solution is to just remove the old library, usually by swiping your pom.xml files and looking for something like:

```xml
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
            <scope>compile</scope>
        </dependency>
```

ArcadeDB uses v.2.10.1.

**Comment by srp-asach** [comment]
@lvca thanks for workaround. This worked for me.
Many thanks.
