### ISSUE TITLE
SQL: Property constraint `notnull` not working correctly

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#885]
### OS: MacOS 12.6

The `notnull` property constraint behaves like the combination of `mandatory` and the expected behavior of `notnull`,
meaning if a document is inserted with a `notnull` property it has to be present. Yet it should be allowed to insert if the `notnull` property is not present (see: https://docs.arcadedb.com/#SQL-Create-Property )

## Expected behavior
Insertion of documents with not-present `notnull` properties.

## Actual behavior
```
Internal error The property 'prop' cannot be null, record: @doc[]
```

<details>

```
Error on command execution (PostCommandHandler)
com.arcadedb.exception.ValidationException: The property 'prop' cannot be null, record: @doc[]
	at com.arcadedb.database.DocumentValidator.throwValidationException(DocumentValidator.java:302)
	at com.arcadedb.database.DocumentValidator.validateField(DocumentValidator.java:49)
	at com.arcadedb.database.DocumentValidator.validate(DocumentValidator.java:37)
	at com.arcadedb.database.MutableDocument.validate(MutableDocument.java:130)
	at com.arcadedb.database.EmbeddedDatabase.createRecordNoLock(EmbeddedDatabase.java:760)
	at com.arcadedb.database.EmbeddedDatabase.lambda$createRecord$15(EmbeddedDatabase.java:731)
	at com.arcadedb.database.EmbeddedDatabase.executeInReadLock(EmbeddedDatabase.java:1326)
	at com.arcadedb.database.EmbeddedDatabase.createRecord(EmbeddedDatabase.java:730)
	at com.arcadedb.database.MutableDocument.save(MutableDocument.java:287)
	at com.arcadedb.query.sql.executor.SaveElementStep$1.next(SaveElementStep.java:59)
	at com.arcadedb.query.sql.executor.InsertExecutionPlan.executeInternal(InsertExecutionPlan.java:65)
	at com.arcadedb.query.sql.parser.InsertStatement.execute(InsertStatement.java:124)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:106)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1250)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:91)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.prop STRING (notnull);

INSERT INTO doc;
```

**Comment by gramian** [comment]
On a related note: Does the `notnull` check precede the `default` check? It seems a not-null default value does not satisfy the `notnull` constraint.

**Comment by gramian** [comment]
@lvca Then this might be console (and studio) only.

**Comment by lvca** [comment]
From the console it's the same, it works notnull + default:

```java
  /**
   * Test case for https://github.com/ArcadeData/arcadedb/issues/885
   */
  @Test
  public void testNotNullProperties() throws IOException {
    Assertions.assertTrue(console.parse("connect " + DB_NAME));
    Assertions.assertTrue(console.parse("CREATE DOCUMENT TYPE doc;"));
    Assertions.assertTrue(console.parse("CREATE PROPERTY doc.prop STRING (notnull, default \"1\");"));
    Assertions.assertTrue(((EmbeddedDatabase) console.getDatabase()).getSchema().getType("doc").getProperty("prop").isNotNull());

    Assertions.assertTrue(console.parse("INSERT INTO doc;"));

    Assertions.assertEquals("1", console.getDatabase().query("sql", "SELECT FROM doc").nextIfAvailable().getProperty("prop"));
  }
```

Unless you're referring to the case of defining a notnull property only, in that case, the property cannot be null, so its implicit that is also mandatory.

**Comment by gramian** [comment]
This answers it. I was referring to the no-default case and was expecting that if a `notnull` property is not set, then it is non-existing (and thus different form `null`).

**Comment by lvca** [comment]
Got it. You're right, if the property is not defined in the document, it shouldn't be checking if it's notnull. Fixing this as a bug.
