### ISSUE TITLE
SQL: `CREATE TYPE` does not automatically create `BUCKET`s

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#892]
## Expected behavior
Non existing buckets are created, see https://docs.arcadedb.com/#SQL-Create-Type

## Actual behavior
```
Internal error Bucket with name 'b1' was not found
```

<details>

```
Error on command execution (PostCommandHandler)
com.arcadedb.exception.SchemaException: Bucket with name 'b1' was not found
	at com.arcadedb.schema.EmbeddedSchema.getBucketByName(EmbeddedSchema.java:261)
	at com.arcadedb.query.sql.parser.CreateDocumentTypeStatement.createType(CreateDocumentTypeStatement.java:52)
	at com.arcadedb.query.sql.parser.CreateTypeAbstractStatement.executeDDL(CreateTypeAbstractStatement.java:84)
	at com.arcadedb.query.sql.executor.DDLExecutionPlan.executeInternal(DDLExecutionPlan.java:60)
	at com.arcadedb.query.sql.parser.DDLStatement.execute(DDLStatement.java:60)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:106)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1250)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:91)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc BUCKET b1, b2
```

**Comment by lvca** [comment]
From OrientDB, this syntax is to assign buckets (clusters in OrientDB) to the type, but I can see why creating the buckets automatically is a good idea. Assigned for the march version!

**Comment by gramian** [comment]
Refactor of #926 in https://github.com/ArcadeData/arcadedb/commit/ce285098054a8940c9c8cc23e738248ba8c4ffd1 . Works!
