### ISSUE TITLE
SQL: Boolean operators with `null` argument

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#895]
### OS: MacOS 12.6

Boolean operators with null arguments produce an error, for example:
```
SELECT (true AND null)
```

## Expected behavior
See https://stackoverflow.com/questions/44318788/null-values-boolean-expression#44318916 and https://en.wikipedia.org/wiki/Three-valued_logic#SQL

## Actual behavior
```
Cannot execute command Encountered " "(" "( "" at line 1, column 8. Was expecting one of: <DISTINCT> ... <DISTINCT> ... <DISTINCT> ... <DISTINCT> ... <DISTINCT> ... <DISTINCT> ... 
```

<details>

```
Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandSQLParsingException: SELECT (null OR true) limit 25
	at com.arcadedb.query.sql.parser.StatementCache.throwParsingException(StatementCache.java:126)
	at com.arcadedb.query.sql.parser.StatementCache.parse(StatementCache.java:116)
	at com.arcadedb.query.sql.parser.StatementCache.get(StatementCache.java:70)
	at com.arcadedb.query.sql.SQLQueryEngine.parse(SQLQueryEngine.java:207)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:102)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1250)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:91)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.arcadedb.query.sql.parser.ParseException: Encountered " "(" "( "" at line 1, column 8.
Was expecting one of:
    <DISTINCT> ...
    <DISTINCT> ...
    <DISTINCT> ...
    <DISTINCT> ...
    <DISTINCT> ...
    <DISTINCT> ...
    
	at com.arcadedb.query.sql.parser.SqlParser.generateParseException(SqlParser.java:26917)
	at com.arcadedb.query.sql.parser.SqlParser.jj_consume_token(SqlParser.java:26762)
	at com.arcadedb.query.sql.parser.SqlParser.Projection(SqlParser.java:4733)
	at com.arcadedb.query.sql.parser.SqlParser.SelectWithoutTargetStatement(SqlParser.java:1481)
	at com.arcadedb.query.sql.parser.SqlParser.QueryStatement(SqlParser.java:1430)
	at com.arcadedb.query.sql.parser.SqlParser.StatementInternal(SqlParser.java:1234)
	at com.arcadedb.query.sql.parser.SqlParser.Statement(SqlParser.java:1004)
	at com.arcadedb.query.sql.parser.SqlParser.Parse(SqlParser.java:245)
	at com.arcadedb.query.sql.parser.StatementCache.parse(StatementCache.java:111)
	... 16 more
```
</details>

## Steps to reproduce
```
SELECT (true AND null)
SELECT (false AND null)
SELECT (true OR null)
SELECT (false OR null)
```

**Comment by gramian** [comment]
This issue could be related to the `BooleanExpression` using `boolean` instead of `Boolean` and thus currently not providing and not allowing comparison against `null`. If it is so and `boolean` is required here, ie for performance, then this won't fix?

**Comment by lvca** [comment]
Reproduced. The possibility of having NULL was not defined in the Or/And conditions blocks at all. Working on it.

**Comment by gramian** [comment]
@lvca Great, thanks for fixing this error. There is one thing that may still need to be changed:

`(null AND true)` yields currently `false` because a `null` input is treated as `false`, but to be consisted with `AND`ing a field, `(null AND true)` should be `true`.

Actually `(true AND null)` and `(false OR null)` should be `null` but I think since the underlying Java type is `boolean` and not `Boolean`, `null` cannot be used here.

**Comment by lvca** [comment]
What should be the correct answer:

SELECT (true AND null) = true
SELECT (false AND null) = false
SELECT (true OR null) = true
SELECT (false OR null) = false

**Comment by gramian** [comment]
I just meantioned this was a possibility, without considering any consequences for `BooleanExpression`s in other contexts. I don't want to invite other problems this way. Anyway here would be the truth table with `null`:
```
(true AND null) = null
(false AND null) = false
(null AND null) = null
(true OR null) = true
(false OR null) = null
(null OR null) = null
```
and here if a `BooleanExpression` has to result in a Boolean:
```
(true AND null) = true
(false AND null) = false
(null AND null) = true
(true OR null) = true
(false OR null) = false
(null OR null) = false
```
The latter is based on the idea that:

* `null` is a symbol for no value, and 
* `AND` is `true` only if all arguments are `true`, and
* `OR` is `false` only if all arguments are `false`.

Given that this is a not too important issue, I am not sure a potentially far reaching change, like the `null` returnable variant should result?

**Comment by lvca** [comment]
I preferred the 1st solution by changing some methods to return Boolean instead of null.
