### ISSUE TITLE
Method fails in filtering `schema:types`

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#991]
### OS: MacOS 12.6

The `replace` method causes an error if used inside filtering (`WHERE`) `schema:types`.

### Expected behavior
`name: doc`

### Actual behavior
`Invalid value for $current: null`

<details>

```
Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Invalid value for $current: null
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:101)
	at com.arcadedb.query.sql.parser.MethodCall.execute(MethodCall.java:77)
	at com.arcadedb.query.sql.parser.Modifier.execute(Modifier.java:96)
	at com.arcadedb.query.sql.parser.BaseExpression.execute(BaseExpression.java:146)
	at com.arcadedb.query.sql.parser.Expression.execute(Expression.java:87)
	at com.arcadedb.query.sql.parser.BinaryCondition.evaluate(BinaryCondition.java:48)
	at com.arcadedb.query.sql.parser.NotBlock.evaluate(NotBlock.java:56)
	at com.arcadedb.query.sql.parser.AndBlock.evaluate(AndBlock.java:70)
	at com.arcadedb.query.sql.parser.OrBlock.evaluate(OrBlock.java:58)
	at com.arcadedb.query.sql.parser.WhereClause.matchesFilters(WhereClause.java:56)
	at com.arcadedb.query.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:72)
	at com.arcadedb.query.sql.executor.FilterStep$1.hasNext(FilterStep.java:91)
	at com.arcadedb.query.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:43)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:46)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:39)
	at com.arcadedb.query.sql.parser.SelectStatement.execute(SelectStatement.java:207)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)
	at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)
	at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:97)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1236)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:92)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

### Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
SELECT name FROM schema:types WHERE 'a_b' = 'a b'.replace(' ','_')
```
However, using a regular type works:
```
SELECT name FROM doc WHERE 'a_b' = 'a b'.replace(' ','_')
```

**Comment by lvca** [comment]
Reproduced.

**Comment by gramian** [comment]
Works!. Cool! Thanks
